core/sdk/src/client.ts
This reverts commit e84a2ea6997965fdbec3c0abd9b71424e2e9a6ae.
(turns out it was a turbo cache thing)
=> Revert "Add defaults to the metadata in the create stream calls (#45)"

core/node/rpc/server.go
The shared library for entitlement checks requires initialization - porting this init call to the stream node.
=> Fix uninitialized client pool on stream node for xchain checks

scripts/node-no-warn.js
This script is used in running jest tests and now for the stress tests.
We will probably want to make a new one for stress.. for now just leave the env setting blank
=> Don’t assign certs if none are available in node-no-warn.js

turbo.json
@serge i think all the protobuf files should be in a single folder under packages. Pretty sure the new structure will break the river-build/proto package that we publish to npm
fixes breakages here: https://github.com/river-build/river/actions/runs/9238352486/job/25416317936?pr=70
=> Exclude the proto package from the turbo cache

core/encryption/src/decryptionExtensions.ts, core/encryption/src/tests/decryptionExtensions.test.ts, core/sdk/src/clientDecryptionExtensions.ts
Currently when we repond to KeySolicitations we first post a KeyFulfillment to the channel. Lots of users can post this fulfillment at the same time, but the node will only accept one of them
After this change, instead of throwing tons of errors polluting all logs, we now pass “optional: true” and check the error in the calling code
=> Use the optional flag when adding events for key fulfillments

core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_cache_test.go, core/node/rpc/get_miniblocks.go, core/node/rpc/info.go, core/node/rpc/node2node.go, core/node/rpc/sync_streams.go
=> node: Support unloading stream view for inactive streams

core/node/events/miniblock.go, core/node/events/minipool.go, core/node/events/stream.go, core/node/events/stream_view.go, core/node/events/stream_view_test.go, core/node/events/stream_viewstate_joinable.go, core/node/events/stream_viewstate_space.go, core/node/events/stream_viewstate_user.go
I want to add updatedAtEventNum for some items in the snapshot so that we can do proper cache invalidation. This refactor is required to keep things consistant when dealing with events past the snapshot
=> Add miniblockNum and eventNum to the forEachEvent iterator

core/proto/package.json, package.json, protocol/package.json, turbo.json, yarn.lock
This PR is part 1 of a series of small PRs to fix the turbo cache, along with a few other recently introduced issues.
- Turns the river/protocol directory into an npm package, so that @river/proto can explicitly depend on it while building. this will ensure proper caching for turbo build
=> adding .proto source files as a package dependency to core/proto

core/sdk/src/client.ts
Current use-case for this PR is to locally identify a message whose attachments are still processing.
=> Add hook to capture local id when sending messages

core/web3/src/entitlement.ts
These test cases broken when I moved entitlement evaluation to stream node for channels, I am updating this to use local base chain id so I can re-enable the tests in harmony.
=> Update token struct used for test cases to use local base chain id

core/web3/src/v3/SpaceDapp.ts
This is the same logic implemented in createEntitlementStruct and will now include the change to not create rule entitlements for empty rule datas, which is what was causing the userops role test to fail in harmony.
=> UserOps IT test fix: Re-use existing method for creating entitlement struct for role updates

packages/sdk/src/streamStateView_UserMetadata.ts
brian/ theo's PR in harmony for fixing the username lookup perf issue included this change. Make the change in the river repo, then pull it over into harmony.
=> export type that will be used by the client for user lookup

core/node/crypto/config.go, scripts/gen-riverchain-config.sh
Currently the default GDM memberschip limit is set to 6. Change this to 48.
=> node: set default GDM memberschip limit to 48

core/node/crypto/config.go, core/node/events/stream_cache.go
Only log when chain config is loaded/changed once.
=> Stop logging chain configuration too much

core/node/auth/banning.go, core/node/auth/banning_test.go, packages/sdk/src/channelsWithEntitlements.test.ts
Some nil pointer exceptions showed up on omega because the banning interface token contract was not properly initialized. This was not showing up in test cases or on gamma because no one was banned anywhere entitlements were checked.
This PR fixes the bug and adds a test case to check for this specific scenario - a banned user should not be able to join a channel, and also banning checks should work when a user is banned. In addition, I added a sanity check test case to the simple cache used by the banning interface for better coverage.
=> Banning fix plus test cases

core/node/crypto/config.go
HNT-6524, increases the max number of chunks to 50 that can be added to a media stream to support media files up to 25mb. It leaves the max chunk size to 0.5mb to prevent events from getting big.
=> code: set default max chunk count for media streams to 50

packages/sdk/src/riverConfig.ts
walking through code with wil and kerem made this seem like a better option than magically picking it up from env in some cases
=> Add ability to just pass in river config environment id

core/node/events/stream_view_test.go
This didn’t return an error here: https://github.com/river-build/river/actions/runs/9521356160/job/26248585342?pr=177
probably the time was too tight.
=> Fix for flaky stream_view test

packages/sdk/src/streamStateView_Channel.ts
there are perf implications here, but i think it’s necessary to get useful information from the stream
=> Update scrollback to go until we have a root message

core/node/cmd/config_cmd.go, core/node/cmd/genkey_cmd.go, core/node/cmd/root_cmd.go
also add `config names` cmd line command to print all possible env var names.
=> Bind all settins to env var, support old __ and new RIVER_

packages/stress/src/mode/chat/joinChat.ts
seeing lots of undecrypted messages in the stress channel
this really slows things down, but will help everybody else
=> make sure we share keys first in stress tests

core/Dockerfile
In a recent code restructuring effort the docker build broke due to packages not being copied. This change adds these missing packages.
=> core: copy cmd and config packages in dockerfile

packages/web3/src/SpaceDappFactory.ts, packages/web3/src/v3/SpaceDapp.ts
I don't know why we have either the generator or the interface for the space dapp, neither are needed, and i don't think people will use them.
=> Move the polling adjustment in the space dapp to the constructor

package.json, packages/react/.eslintrc.cjs, packages/react/.gitignore, packages/react/README.md, packages/react/package.json, packages/react/src/context.ts, packages/react/src/index.ts, packages/react/src/true.test.ts, packages/react/tsconfig.build.json, packages/react/tsconfig.json, turbo.json, vitest.config.ts, vitest.workspace.ts, yarn.lock
Got some stuff from the wagmi monorepo `react` package.
They're some stuff missing, like the lack of auto import from vitest in `.test.ts` files, but _for now_ I don't think it will be a problem (just import expect, test from vitest and you're good to go)
Later we can improve the monorepo, adding the `test:build` to CI to confirm if the package matches what the current JS ecosystem expects.
=> react-sdk: init [HNT-7062]

core/xchain/entitlement/entitlement_test.go
Also fix error messages to print the correct expected duration.
=> Fix entitlement timing tests by loosening tolerance

core/node/crypto/chain_txpool.go
Currently the tx pool registers an callback for every block in the chain monitor. This callbacks checks which pending transactions are included in the chain. If the chain monitor grabs a chain segment with >1 blocks it will still execute the callback for all intermediate blocks which is not necessary.
This change converts the tx pool to use OnHeader. The chain monitor calls OnHeader only for the latest head that it fetched and not for any intermediate blocks. This reduces extra work/rpc calls. In addition it now executes this callback in the background and guards it with a `mutex.TryLock` construction to prevent the logic to run in parallel. This prevents the chain monitor to get blocked when it takes a long time to process pending transactions.
=> core: reduce redundant checking of pending payment status in tx pool

core/node/crypto/blockchain.go, core/node/crypto/blockchain_test.go, core/node/crypto/chain_monitor.go, core/node/crypto/chain_monitor_builder.go, core/node/crypto/chain_monitor_test.go, core/node/crypto/chain_txpool.go, core/node/crypto/chain_txpool_test.go, core/node/crypto/config.go, core/node/crypto/testutil.go, core/node/events/stream_cache.go, core/node/nodes/node_registry.go, core/node/registries/river_registry_contract.go, core/xchain/client_simulator/client_simulator.go, core/xchain/server/server.go
This is the successor of https://github.com/river-build/river/pull/184 that was reverted due to a problem with the block range when retrieving logs. The issue was introduced in a refactoring a while ago that caused the chain monitor to be started twice. With support to subscribe on historical blocks the logic to determine the next block range to poll became more complex. Due to a race condition that was caused by running the same monitor twice it could calculate an invalid block range that caused the rpc get_logs call to fail. The chain monitor never recovered from this and kept on looping on the same invalid range. During unittests the monitor wasn't started twice and therefore the problem wasn't detected.
This is fixed by not starting the blockchain monitor twice. During analysis the …
=> Add support to subscribe to historical and future chain events

.vscode/tasks.json
this builds the code, which requires it to compile, but it was happening after we launch blockchains
if you had code errors, you would start blockchains, deploy contracts, then get the error, forcing you to start over. Fail fast instead.
=> Move the build protobuf task in tasks.json

packages/web3/src/v3/SpaceOwner.ts
i had accidentally named this shim getter function `getNumTotalMemberships`, though the real name should have been `getNumTotalSpaces`
=> changing spaceOwner function shim name: getNumTotalMemberships->getNumTotalSpaces

packages/web3/src/v3/BaseRegistry.ts
Part of the on-chain metrics requirements is to help with detecting discrepancies between nodes and operators on Base vs River.
RiverRegistry's INodeRegistry facet's `getAllNodes()` makes it easy to query the operator of a given node, since `operator` is part of the `Node` struct. However nodes are expressed as addresses only on Base, and we're required to dispatch additional queries to connect the node to its operator.
This PR introduces a new helper function to BaseRegistry. This helper function streamlines this process of getting all nodes along with their operators. We can now use its output to dig into the discrepancies between River and Base.
=> BaseRegistry helper function to connect base nodes to their operators

core/node/rpc/service_test.go
I think inserting a short sleep will fix the flaky getstreamex forwarding test, but if it happens again I will disable it.
=> Add a pause to fix flaky getstreamex forwarding test.

packages/sdk/src/riverConfig.ts
Now with the playground package, we're using those functions in places that doesn't even have `process.env`.
So we need to check if `process` is defined before accessing it, to avoid explosions.
Ideally, we want to remove those `process.env` calls in the sdk package, but that's something for other PR
=> fix: check if process is defined

packages/stress/src/mode/chat/kickoffChat.ts, packages/stress/src/mode/chat/root_chat.ts, packages/stress/src/mode/chat/types.ts, packages/stress/src/start.test.ts
To test minting, and initializing user streams
Ran into a bug with wil, wanted to make for certian this path wasn’t broken (it wasn’t)
=> Stress tests - add a small number of new random clients every run

packages/stress/src/mode/chat/root_chat.ts
Until we have a plan that doesn’t involve adding 5 users to our channel every hour, or until we can support that!
=> Default new stress test clients to 0

core/node/rpc/service_test.go
Adding an Eventually condition with 10s did not fix - I'm wondering if there's an issue aside from the known issue of miniblock consistency, but we don't actually use GetStreamEx right now and fixing it is not as high priority as channel gating work, see https://linear.app/hnt-labs/issue/HNT-7329/fix-getstreamex-endpoint-go-test for follow-up task
I'm disabling this test to give @texuf some relief.
=> Disable flaky forwarding test

core/cmd/register_xchain_node_cmd.go, core/node/crypto/blockchain.go, core/node/crypto/testutil.go, core/node/events/stream_cache.go, core/node/events/stream_cache_test.go, core/node/events/stream_test.go, core/node/events/stream_viewstate_space_test.go, core/node/events/util_test.go, core/node/rpc/archive.go, core/node/rpc/info_mode.go, core/node/rpc/server.go, core/xchain/client_simulator/client_simulator.go, core/xchain/server/server.go
This should fix node registration race in some go tests and make them more stable.
=> Refactor cache tests to use common helpers. Unify ChainMonitor start.

packages/sdk/src/sync-agent/spaces/spaces.ts, packages/web3/src/ISpaceDapp.ts, packages/web3/src/types.ts, packages/web3/src/v3/SpaceDapp.ts
Branched off [g/hnt-7247](https://github.com/river-build/river/pull/276). Fixes to the river web3 packages to align with your spaceInfo contract changes. 
Locally tested. Builds clean. Integration tests passed.
=> SpaceDapp changes for shortDescription, longDescription to align with the contract changes

contracts/test/river/registry/stream/StreamRegistry.t.sol
`test_streamCountOnNode` was only testing `getStreamCount`. this pr adds a new test case just for getStreamsOnNode(). i'm also extending the getStreamCount() test to involve multiple nodes
=> adding explicit test cases for getStreamsOnNode()

core/node/rpc/metrics_interceptor.go
Add prom metrics for grpc calls:
- `grpc_unary_inflight` count the number of in progress unary calls
- `grpc_open_client_streams` number of open streams where node is receiving from a remote server
- `grpc_open_server_streams` number of open streams where node is streaming to client
=> core: add metrics for in-flight grpc requests and open streams

packages/sdk/src/persistenceStore.ts
This caused an error when running the code in node where `navigator` is not defined. 
The fix adds the check to ensure that the code runs without errors in all environments.
=> sdk: check if navigator is defined

packages/sdk/src/channelsWithEntitlements.test.ts, packages/sdk/src/client.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/util.test.ts
The final step of react-reply "backend" support - the client self-filters invalid messages based on whether or not it has entitlements to post to the channel.
=> Client checks for entitlements before channel posts

core/node/rules/can_add_event.go, packages/sdk/src/channelsWithEntitlements.test.ts
I'm removing the stream node feature to boot users after losing permission to write to channels for two reasons:
- the client now self-audits and does not send unpermitted messages, so we're unlikely to hit this code path anymore from good actors
- the implementation was wrong - a user should be booted if they lose read entitlements, not write entitlements. a user often loses both at the same time, but we weren't checking here to make sure they did in fact lose the read entitlements. however, since good clients don't even send writes anymore once the entitlement is lost, i think it doesn't make sense to fix this.
=> Remove channel booting on message write

packages/generated/scripts/make-config.sh
kerem removed it here https://github.com/river-build/river/commit/7ca785024ff6cb5814d12750398138b28f471b00
i use it in harmony in different places, it’s still useful
=> Put back in make-config.sh

core/node/rpc/http_handler.go, core/node/rpc/metrics_interceptor.go, core/node/rpc/server.go, core/node/rpc/service.go
Add the following metrics:
- `grpc_unary_status_code[proc,status]`, unary calls grouped by procedure and status
- `grpc_server_stream_status_code[proc,status]`, server streams grouped by procedure and status
Client streams are more complicated to capture the status code. Since we don't those client streams metrics are not enhanced with status.
=> node: add status code support to gRPC metrics

.github/workflows/ci.yml
This PR sends notifications to the new `@river-ci-alerts` slack group, instead of `@infra-goalie`. I'm adding @bas-vk @brianathere @clemire @texuf and @sergekh2 to this new group. Feel free to remove yourself from the group if you don't wish to get notified on ci failures.
=> sending ci alerts to the RIVER_CI_ALERTS slack group

packages/sdk/src/sync-agent/spaces/models/space.ts, packages/sdk/src/sync-agent/spaces/spaces.test.ts
I got overzealous and set up the space to preload the default channel, but then forgot that it could get wiped out during initialization and used the wrong check when adding new channels. I think this is better.
=> re-enable spaces.test.ts, fix logic in space observable

core/xchain/server/server.go
Currently the entitlement tx id's are logged as raw bytes. This makes it difficult to search for in logs. Change this to log them as hex strings.
=> xchain: log entitlement tx id as hex

packages/sdk/src/unauthenticatedClient.ts
Prevents unnecessary requests by checking if the required content is available before fetching.
=> Skip redundant scrollback

core/node/rpc/sync/client/syncer_set.go, core/node/rpc/sync/operation.go
The old sync stream implementation used a buffer of 256 messages. This capacity was lowered to 128 and might cause issues when clients start syncing and are retrieving a lot of events.
=> node/rpc/sync: set sync message buffer size to old value

packages/web3/src/v3/SpaceDapp.ts
The getMembershipPrice always returns the current price of the membership, regardless of prepaid seats.
However, if a space has any prepaid seats left, a user won't be charged this price.
When grabbing this price via getMembershipInfo, I think it makes more sense to return the price considering prepaid seats. Easier to reason about at the UI level - a user sees 0, they'll pay 0.
Alternatively I can just call getJoinSpacePrice where appropriate for UI.
=> SpaceDapp: use getJoinSpacePrice as membershipPrice in getMembershipInfo

scripts/publish-to-npm.sh
Remove `nightly` tag from npm builds, such that consumers of sdk packages can pull in latest build below version 1.0.0 with `"^0.0.0"` in package.json.
=> remove nightly tag

core/node/events/stream_cache.go
Is this necessary? It seems like the cache will get flushed imediately if not, but maybe i missed something.
=> Set lastAccessedTime when initializing streams

core/config/config.go, core/node/events/stream.go, core/node/rpc/archive.go, core/node/rpc/debug.go, core/node/rpc/info_mode.go, core/node/rpc/server.go
pprof is disabled by default.
text-only endpoints are enabled.
=> Enable extra /debug endpoints by default, add settings per endpoint

core/node/rpc/server.go
There seems to be a problem with the http.Server for http2 that could cause the stream to hang.
- https://github.com/golang/go/issues/42534
Proxy projects ([caddy](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/app.go#L412)/[traefik](https://github.com/traefik/traefik/blob/bd93e224deb434b4cd8ffe5c85e52c8b0f54f57a/pkg/server/server_entrypoint_tcp.go#L678)) switched over to use `http2.Server` with success.
=> core/node/rpc: Use x/http2.Server instead of http.Server

core/Dockerfile
Upgrading go/libs to see if it helps with https://github.com/river-build/river/issues/640
=> Just build go 1.22.6 from our dockerfile (copied from oficial dockerfile)

contracts/src/diamond/facets/introspection/IIntrospectionBase.sol, contracts/src/diamond/facets/introspection/IntrospectionBase.sol, contracts/src/factory/facets/architect/Architect.sol, contracts/src/factory/facets/architect/ArchitectBase.sol, contracts/src/factory/facets/architect/pricing/PricingModulesBase.sol, contracts/src/spaces/facets/entitlements/EntitlementsManagerService.sol, contracts/src/spaces/facets/gated/EntitlementGatedBase.sol, contracts/src/utils/Factory.sol, contracts/test/diamond/erc721a/ERC721A.t.sol, contracts/test/diamond/introspection/IntrospectionSetup.sol, contracts/test/diamond/loupe/DiamondLoupe.t.sol
Replaced internal `IERC165` imports with those from OpenZeppelin, and renamed a local interface for better clarity. Additionally, refactored `IntrospectionHelper` contract initialization to improve code readability and consistency.
Refactor internal deploy functions to use memory-safe assembly and add explicit reverts on failure. Integrate `LibClone` for address prediction to improve clarity and reliability.
Refactor loops to improve performance by reducing redundant evaluations and increasing readability. Added `unchecked` blocks for vote counting to minimize gas usage. Streamlined the fetching of rule data directly within return statements.
Modified function parameters to use `calldata` over `memory` for better gas efficiency. This change impacts functions in both `Architect.sol` and …
=> perf(contract): Optimizations and clean ups

packages/generated/package.json
When adding `@river-build/sdk` with other packages managers such as `pnpm`, I was getting an error since the preinstall command uses `yarn`.
This commit inlines the preinstallation command to avoid the usage of a package manager script indirection call.
Previously:
```
node_modules/.pnpm/@river-build+generated@0.0.32/node_modules/@river-build/generated: Running preinstall script, failed in 289ms
.../node_modules/@river-build/generated preinstall$ yarn make-config
│ Usage Error: The nearest package directory (/Users/miguel/dev/hnt/www/node_modules/.pnpm/@river-build+generated@0.0.32/node_modules/@river-build/generated) doesn't seem to be…
│ - If /Users/miguel/dev/hnt/www isn't intended to be a project, remove any yarn.lock and/or package.json file there.
│ - If /Users/miguel/dev/hnt/www is …
```
=> generated: fix preinstall script

packages/stress/src/utils/stressClient.ts
Example of filename: `stress-0x95D7701A0Faa5F514B4c5B49bf66580fCE9ffbf7-local_single.json`
Closes #658
=> stress: follow filename convention for exported encryption device

core/node/rpc/service_sync_streams.go, core/node/rpc/sync/handler.go, core/node/rpc/sync/operation.go
While service doesn't lock up anymore (#640), notification service still fails to receive all expected data.
=> Log sync start/exit, add syncId to callstacks

contracts/test/crosschain/RuleEntitlement.t.sol, contracts/test/crosschain/RuleEntitlementV2.t.sol, contracts/test/utils/TestUtils.sol
Refactor entitlement deployment and upgrade tests.
Refactor `RuleEntitlement` tests for efficiency and clarity.
Enhance `removeEntitlement` tests.
Remove unused import and add entitlement rule test.
Add assertions for removal of V1 rule data.
Refactor rule entitlement setup and validation.
=> test(contract): enhance `RuleEntitlement` tests 

contracts/src/spaces/entitlements/rule/IRuleEntitlement.sol, contracts/src/spaces/entitlements/rule/RuleEntitlement.sol, contracts/src/spaces/entitlements/rule/RuleEntitlementV2.sol, contracts/test/crosschain/RuleEntitlement.t.sol, contracts/test/crosschain/RuleEntitlementV2.t.sol, contracts/test/utils/TestUtils.sol
Removed redundant struct to streamline the codebase. Simplified conditional checks and optimized loops for consistency. Updated entitlement storage from `memory` to `storage` where appropriate for efficiency.
Switch from `abi.decode` to direct `calldata` decoding using assembly for `RuleData` and `RuleDataV2`. This optimizes structs handling by reading directly from calldata, improving efficiency and reducing gas costs.
=> perf(contract): refactor rule entitlement contracts

contracts/src/base/registry/facets/checker/EntitlementChecker.sol
Refactor `getNodesByOperator` to use memory-safe assembly for updating the array length and improve loop efficiency. Enhance `_getRandomNodes` by using the more efficient unchecked block and streamline random selection and node updating logic.
=> perf(contract): Optimize node retrieval and random selection logic

packages/dlog/src/dlog.ts, packages/dlog/src/tests/dlog.test.ts, packages/stress-testing/Dockerfile, packages/stress/scripts/start.sh
Change of behavior here. Previously, we would use multiline logs only in dev mode. Now, multiline logs are the default, and if you want single line ones, set using SINGLE_LINE_LOGS.
Currently, we want singe line logs on the stress test, that’s why I set on the Dockerfile.
This should close #722
=> dlog: support SINGLE_LINE_LOGS env

packages/sdk/src/client.ts, packages/sdk/src/space.test.ts, protocol/payloads.proto, services/fetch-image/src/handleImageRequest.ts
We don’t need this value to be derived. The chunked media payload itself is encrypted with a derived key, we don’t need to make any changes around uploading media in our client.
(Event if it is derived, we derive secret and iv so we should just use those values in this payload)
=> Remove derived encryption as an option in the chunked media message

packages/stress/scripts/localhost_chat.sh, packages/stress/scripts/localhost_demo.sh, packages/stress/scripts/start_redis.sh, packages/stress/src/demo.ts, packages/stress/src/mode/chat/sumarizeChat.ts, packages/stress/src/utils/storage.ts
The param is REDIS_HOST because aws only provides a host, there is no protocol or port. Mimic the same thing for localhost and do the right thing.
=> stress clients: Remove localhost hack for redis storage

.vscode/tasks.json
it’s started in the stream node now (one wasn’t called, the other was orphaned)
pairs with https://github.com/river-build/river/pull/730
=> Remove xchain from tasks.json

packages/sdk/src/userSettings.test.ts
seeing this fail a lot lately
https://github.com/river-build/river/actions/runs/10363799599/job/28688037477
we’re having issuses with the stream subscription backing up, i think the message wasn’t getting there in time.
fix: explicitly wait for all three messages before unblocking alice
=> Fix for flaky DMMessagesAreBlockedDuringBlockedPeriod test

core/node/crypto/chain_txpool.go
There is no need to claim the tx pool lock when estimating gas.
=> core: don't lock tx pool on estimate gas

contracts/src/spaces/facets/entitlements/extensions/EntitlementDataQueryable.sol, contracts/src/spaces/facets/gated/EntitlementGatedBase.sol, contracts/test/spaces/entitlements/EntitlementDataQueryable.t.sol
Replaced pre-increment operators for better performance and utilized unchecked blocks to optimize arithmetic operations. Additionally, fixed a typo in a comment and updated a test function name for clarity.
=> perf(contract): Use `unchecked` where appropriate and cache storage pointer

.coderabbit.yaml
Included path_filters to exclude 'packages/generated/**' paths. This update ensures auto_review ignores generated files, keeping the review process focused on relevant code changes.
=> chore: Add path_filters to .coderabbit.yaml

core/node/storage/pg_storage.go
PromoteBlock is not called as part of RPC, and as such doesn't timeout set.
=> Add timeout to PromoteBlock

core/node/storage/migrations/000004_alter_miniblock_candidates_pk.down.sql, core/node/storage/migrations/000004_alter_miniblock_candidates_pk.up.sql, core/node/storage/pg_storage.go, core/node/storage/pg_storage_test.go
I've reviewed all of the queries that were resulting in serialization errors and I'm unable to figure out why we would be having any errors in the first place. It's a red flag that our transaction order, which is quite small, is causing a serialization error.
Along the way I found two queries that we doing some table level access that should have been index only. This fixes those cases.
=> Change the miniblock_candidate primary key to be covering for the queries we run. Change one fetch to avoid a sort

packages/sdk/src/syncedStreams.test.ts, packages/sdk/src/syncedStreams.ts
Try to flush out any race in sending and receiving pings. Could be useful to run while also running a stress test.
=> Add PingSync tests

packages/stress/package.json, packages/stress/scripts/localhost_chat_setup.sh
Closes #746 
I added a random throw statement around the code to test. Results:
prev:
```
stress:run:0:error unhandled error: Error: not implemented at StressClient.sendMessage 
(/Users/miguel/dev/hnt/river/packages/stress/dist/start.cjs:174697:11)     at process.processTicksAndRejections 
(node:internal/process/task_queues:95:5) at async kickoffChat 
(/Users/miguel/dev/hnt/river/packages/stress/dist/start.cjs:174846:46) at async startStressChat 
(/Users/miguel/dev/hnt/river/packages/stress/dist/start.cjs:175460:5) at async run 
(/Users/miguel/dev/hnt/river/packages/stress/dist/start.cjs:175564:7)
```
with sourcemap
```
stress:run:0:error unhandled error: Error: not implemented at StressClient.sendMessage 
(/Users/miguel/dev/hnt/river/packages/stress/src/utils/stressClient.ts:252:15) …
```
=> stress: add `--enable-source-maps` in start/demo script

packages/web3/src/entitlement.ts
Updated multiple functions to use `ethers.providers.BaseProvider` instead of `StaticJsonRpcProvider` for broader compatibility. This change ensures a more flexible provider usage across different wallet operations.
=> refactor(sdk): Switch to `BaseProvider` in entitlement.ts

packages/sdk/src/sync-agent/streams/streams.test.ts, packages/web3/src/v3/RiverRegistry.ts
Really useful to just go to the stream registry to see if a stream exists instead of an “optional” get stream request.
=> Add streamExists function on the RiverRegistryDapp

packages/sdk/src/client.ts
waitForStream was accepting a string or uint8array and was then comparing to a string. It was never called with a uint8array, but that was a bug waiting to happen
it also didn’t timeout, so if the stream never initialized, initStream would hang forever.
add timeout so that the ui can continue and not hang on loading screens.
=> bugfix(sdk) Udpate client.waitForStream

packages/web3/src/entitlement.ts
1) logically group the type definitions
2) use typescript to infer the supported logical operations type so when we implement another we only need to add it in one place
3) fix up the other cast to be the of the supported type
=> Fixup typescript in entitlement.ts

packages/stream-metadata/src/node.ts, packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/src/routes/health.ts, packages/stream-metadata/src/routes/spaceImage.ts, packages/stream-metadata/src/streamRegistry.ts
my logger statements only print the 1st argument strings, and ate up the subsequent arguments. Turns out that pino logger expects the arguments in the reverse order. First argument has to be the object; the 2nd argument is the message string.
**does not work (2nd arg eaten):**
```typescript
const obj = { fruit: 'apple' }
logger.info('print this', obj) // output: "print this"
logger.info(spaceContractAddress, 'the space contract address') // output: 0x12345
```
**this works:**
```typescript
const obj = { fruit: 'apple' }
logger.info(obj, 'print this')
// output: "print this"
//                    fruit: "apple"
logger.info({ spaceContractAddress }, 'the space contract address')
// output: "the space contract address"
spaceContractAddress: 0x12345
```
=> fix pino logger printing

packages/stream-metadata/src/environment.ts, packages/stream-metadata/src/node.ts
line 77 had a reference to `server` directly whereas the other routes used the `srv` param. this pr attempts to simplify and standardize
=> removed parameter in setupRoutes

packages/sdk/src/makeStreamRpcClient.ts
this was lingering from the very first implementation, it gets in the way when we want to override it with an http2 client in node.
=> chore(sdk) remove unused transport type on makeStreamRpcClient

packages/sdk/src/client.ts, packages/stress/src/mode/chat/joinChat.ts
We recently started seeing a few clients get dropped from the stress tests. 
Also I recently added a timeout in waitForStream. I guess 15 seconds wasn't enough, this is where the clients are dying.
Up the timeout for the join chat section where we wait for the announcement channel
=> Increase stress test timeout waiting for initial stream

core/node/crypto/chain_txpool.go, core/xchain/server/server_test.go
The current transaction pool has several tasks:
- submit new transactions
- track submitted transactions for inclusion in the chain
- send a replacement transaction when needed
Because all tasks operate on the pending transactions list they share a mutex to prevent race issues. This mutex is also used to prevent nonce collisions. This causes lock contention and can lead to delays when submitting and retrieving transaction confirmations. This change splits the logic into a transaction pool that is used to submit transactions and an internal pool that deals with pending transactions.
The mutex in the transaction pool is only used to prevent nonce collisions on submit. The pending tx pool uses `sync.Map` that allows concurrent use and therefore allows for parallel inclusion of newly …
=> core: remove lock contention in transaction pool

packages/sdk/src/client.ts, packages/sdk/src/syncedStreams.ts, packages/sdk/src/syncedStreamsLoop.ts
Add sync stats to bad_prev_miniblock_hash message
I ran the stress tests locally and confirmed that when I get a "RETRYING event after BAD_PREV_MINIBLOCK_HASH response" message
I DO NOT have any stream responses queued, which implies that the streams are getting backed up in the node.
=> Add sync stats to bad_prev_miniblock_hash message

packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/src/streamRegistry.ts
@mechanical-turk and I went through a DataDog Log viewer exercise and created a debug view for stream-metadata that keeps the log messages simple without requiring template strings. Relevant values are shown as column data.
https://app.datadoghq.com/logs?query=service%3Astream-metadata%20env%3Aomega&cols=%40url%2C%40streamId%2C%40req.url%2C%40spaceAddress&fromUser=true&index=%2A&messageDisplay=expanded-md&refresh_mode=sliding&saved-view-id=2897198&storage=hot&stream_sort=desc&viz=stream&from_ts=1724264295799&to_ts=1724267895799&live=true
=> [stream-metadata] remove literal string values in log message

contracts/scripts/interactions/InteractSetDefaultUri.s.sol
Introduce `InteractSetDefaultUri` script to set the default URI for spaceFactory contracts. This script ensures the consistent URI configuration by using the `setDefaultUri` method from `ISpaceOwner` interface and validating it with a requirement check.
=> chore(contract): Add `InteractSetDefaultUri` script

packages/react-sdk/src/internals/useAction.ts, packages/react-sdk/src/useChannel.ts, packages/react-sdk/src/useCreateChannel.ts, packages/react-sdk/src/useJoinSpace.ts, packages/react-sdk/src/useObservable.ts, packages/react-sdk/src/useReaction.ts, packages/react-sdk/src/useRiver.ts, packages/react-sdk/src/useRiverAuthStatus.ts, packages/react-sdk/src/useSendMessage.ts, packages/react-sdk/src/useSpace.ts, packages/react-sdk/src/useTimeline.tsx, packages/react-sdk/src/useUserSpaces.ts, packages/react-sdk/src/utils.ts
This PR adds support for config parameters in all observable hooks. The implementation is based in two utils:
```ts
export declare namespace ObservableConfig {
export type FromObservable<Observable> = ...
export type FromData<Data> = ...
}
```
Making it easy to create those `ObservableConfig` objects.
=> react-sdk: support config in all hooks

packages/sdk/src/observable/observable.ts
before:
stress:run:0:error unhandled error: Error: Timeout waiting for condition at Timeout._onTimeout (/Users/austinellis/hnt/river/packages/sdk/src/observable/observable.ts:50:21)     at listOnTimeout (node:internal/timers:573:17)     at process.processTimers (node:internal/timers:514:7)
after:
stress:run:0:error unhandled error: Error: Timeout waiting for condition at Observable.when (/Users/austinellis/hnt/river/packages/sdk/src/observable/observable.ts:47:30) at Channel2.sendMessage (/Users/austinellis/hnt/river/packages/sdk/src/sync-agent/spaces/models/channel.ts:84:37) at StressClient.sendMessage (/Users/austinellis/hnt/river/packages/stress/src/utils/stressClient.ts:143:24) at kickoffChat (/Users/austinellis/hnt/river/packages/stress/src/mode/chat/kickoffChat.ts:35:65)     at …
=> Fix callstack on syncAgent observable timeout error

core/node/rules/can_create_stream.go
I missed this in the initial rename
=> Rename lingering device key functions to user metadata

packages/sdk/src/sync-agent/members/members.ts, packages/sdk/src/sync-agent/members/models/member.ts, packages/sdk/src/sync-agent/members/models/membership.ts, packages/sdk/src/sync-agent/members/models/metadata/displayName.ts, packages/sdk/src/sync-agent/members/models/metadata/ensAddress.ts, packages/sdk/src/sync-agent/members/models/metadata/metadata.test.ts, packages/sdk/src/sync-agent/members/models/metadata/nft.ts, packages/sdk/src/sync-agent/members/models/metadata/username.ts, packages/sdk/src/sync-agent/river-connection/riverConnection.ts
Previously, all member metadata models were listening to the stream initialized event, causing unneeded subscriptions.
`Membership` model was listening to `streamNewUserJoined`, which is an unneeded listening, since this model lives in the `Member` model, which lives in the `Members` model, which gets the `streamNewUserJoined` too to update the member state.
=> sdk(sync-agent): flatten member onStreamInitialized 

.vscode/tasks.json, scripts/kill-watches.sh
For some reason it wasn’t working with cursor for me, and it’s nice to have this all as a bash command
=> Extract kill-watches from tasks.json

packages/sdk/package.json, packages/sdk/src/client.ts, packages/sdk/src/syncedStreamsExtension.ts, yarn.lock
we don’t use it any more and all telemetry is captured in app
=> Remove datadogRum from the sdk

packages/react-sdk/src/useDisplayName.ts, packages/react-sdk/src/useEnsAddress.ts, packages/react-sdk/src/useNft.ts, packages/react-sdk/src/useUsername.ts, packages/sdk/src/sync-agent/members/members.ts, packages/sdk/src/sync-agent/members/models/myself.ts
Previously, the Myself model was extending a Member model, which required some special treatment to avoid creating it twice.
Now, the `Myself` model is wrapping a Member with some set actions, removing the cognitive overhead when changing the `Members` model, since we dont need to keep the special myself case in mind when doing changes.
=> sdk(sync-agent): don't treat Myself model as special

packages/sdk/src/client.ts
I’m seeing this in the stress test logs
```
2024-08-28T20:07:41.449Z stress:run:2:error client22:0xFCc3..887d error calling joinChat Error: waitForStream: timeout waiting for 10a38bcf15ab6b94d404c201dee9f67c6428c0ecb10000000000000000000000 at TransactionalClient.waitForStream (/monorepo/packages/sdk/src/client.ts:1075:30) at TransactionalClient.initStream (/monorepo/packages/sdk/src/client.ts:1221:33) at TransactionalClient.joinStream (/monorepo/packages/sdk/src/client.ts:1681:35) at <anonymous> (/monorepo/packages/sdk/src/sync-agent/spaces/models/space.ts:88:26) at RiverConnection2.call (/monorepo/packages/sdk/src/sync-agent/river-connection/riverConnection.ts:108:20) at Space3.join (/monorepo/packages/sdk/src/sync-agent/spaces/models/space.ts:87:36) at process.processTicksAndRejections …
```
=> Improve waitForStream error message and cleanup streams after failed createStreamAndSync

packages/sdk/src/signerContext.ts, packages/sdk/src/sync-agent/syncAgent.test.ts, protocol/payloads.proto
If you control the signer for a private key that owns a river user you can
- pick an expiration date
- create a new delegate wallet
- sign the new delegate wallets public key and expiration date with your signer
- export the private key, signature, and expiry as a hexified binary representaion of an AuthToken protobuf
Now you can create a signer context anywhere.
This auth token can be used to sign events and add them to river streams, but it can’t be used to make blockchain transactions.
it prints out a string like this:
```
0a4230786637666335656233636636633633376432326461393730363937316639326264313930336335663966643835306166373534353635626166623766366463663612414465bfdd7b9c56ebfcf93bf6e1767ac497d7fc0820589f2d3e3d61415d9e13060c7acd80b991281ce8fc31e0d2553298b20e2eb828abc31a93dcc64812a4f356 …
```
=> Add helper functions to generate and parse “auth token”

packages/sdk/src/signerContext.ts, packages/sdk/src/sync-agent/syncAgent.test.ts, protocol/payloads.proto
According to google an authToken is a type of bearerToken, I don’t want anyone to assume the wrong thing so we’re going with the more formal sounding name.
=> Change name of new AuthToken to BearerToken to emphasis significance

packages/web3/src/ISpaceDapp.ts, packages/web3/src/v3/SpaceDapp.ts
This could replace the default `createChannel` eventually, but this would be a breaking change
=> DApp: Add create channel with permission overrides

packages/web3/src/Utils.ts, packages/web3/src/utils.test.ts, packages/web3/src/v3/SpaceDapp.ts, packages/web3/tsconfig.json
This underlying call now uses a promise.any and throws an error for a non-entitled result to ensure the promise will terminate as soon as an entitled wallet is found.
=> Short-circuit ruleData evaluation when first good result is found

packages/sdk/src/client.ts, packages/stress/src/utils/rpc-http2.ts, packages/stress/src/utils/stressClient.ts
We're seeing nodes fail to fetch spaces. Maybe it's always the same node.
=> Improve stress client log when selecting node url

packages/web3/src/entitlement.test.ts
...and repair exposed broken test cases.
positive results were expecting a "truthy" response, which could be any nonempty string, including the zero address. This PR fixes tests to expect a valid non-zero address instead, wherever we expect an entitled wallet to be computed.
=> Fix broken unittest positive condition for typescript entitlement checks

packages/sdk/src/client.test.ts, packages/sdk/src/client.ts, protocol/payloads.proto
Without the `updated_at` field, protobuf with empty bio field was failing to encrypt.
=> sdk: allow empty bio in UserBio by adding updatedAt field

packages/web3/src/v3/SpaceDapp.ts
causes
```
invalid arrayify value (argument="value", value="20f05e4ad4edbd5480a3602f249abd3dc767327dbd0000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.7.0)
```
Not sure how we missed this, maybe the client is converting it somewhere? anywho.
=> Fix missing channelId hex prefix in space dapp

packages/stream-metadata/src/routes/userBio.ts
Since empty string is a falsy value, it was returning 404.
=> stream-metadata: allow return of empty bio

packages/stream-metadata/src/node.ts, packages/stream-metadata/src/routes/media.ts, packages/stream-metadata/src/routes/profileImage.ts, packages/stream-metadata/src/routes/spaceImage.ts
Moving the media fetching to another endpoint and redirecting to it when we try to get using `/user/../image` & `/space/../image`
With this change, we can permanently cache the result of `/media/{mediaStreamId}?key&iv` since the media stream content will never change.
=> move fetch media to `/media/{mediaStreamId}?key&iv`

packages/sdk/src/sync-agent/spaces/models/channel.ts
We will want a better workflow around this, but for now this keeps the user from having to do weird things to wait for streams.
=> Update syncAgent pinning functions to use withStream

packages/stream-metadata/src/routes/media.ts, packages/stream-metadata/src/routes/profileImage.ts, packages/stream-metadata/src/routes/spaceImage.ts
this pr adds `Cache-Control` to the the happy paths of stream-metadata service core routes:
a) successful profile image redirects: 5 minutes
b) successful space image redirects: 5 minutes
c) successful media resolution: 1 year
Work remains on the following routes
- `/space/:spaceAddress`
- `/space/:spaceAddress/refresh`
- `/user/:userId/bio`
- `/user/:userId/refresh`
And edge cases (4xx & 5xx on all routes)
=> happy path cache headers for stream-metadata service

packages/sdk/src/sync-agent/spaces/models/space.ts
Because we want to pre load everything, we should allow the system to make channel objects even if we don’t have local data for them yet. We do the same thing with members.
=> Playground: remove unnecessary check

.github/workflows/ci.yml
Tests are failing again due to 30min timeout after I extended E2E tests for ETH balance. Earlier last week, I discussed this issue with Austin - this was the recommendation.
=> Increase timeout for e2e tests

packages/sdk/src/observable/persistedObservable.ts, packages/sdk/src/store/store.ts, packages/sdk/src/sync-agent/members/members.ts, packages/sdk/src/sync-agent/river-connection/models/riverChain.ts, packages/sdk/src/sync-agent/river-connection/riverConnection.ts, packages/sdk/src/sync-agent/spaces/models/channel.ts, packages/sdk/src/sync-agent/spaces/models/space.ts, packages/sdk/src/sync-agent/spaces/spaces.ts, packages/sdk/src/sync-agent/user/models/userInbox.ts, packages/sdk/src/sync-agent/user/models/userMemberships.ts, packages/sdk/src/sync-agent/user/models/userMetadata.ts, packages/sdk/src/sync-agent/user/models/userSettings.ts
a transaction can have side effects which can spawn a new transaction, in the meantime a new transaction group could have been started already. Just piggyback on the existing transaction group if it exists.
=> Fix race in syncAgent store

contracts/src/utils/libraries/CustomRevert.sol
Adds a new `CustomRevert` library to streamline and optimize custom error handling by using efficient assembly code.
=> feat(contract): Introduce `CustomRevert` library for efficient reverts

packages/stream-metadata/src/opensea.ts
I was using the networkId by mistake, the chainId prop from the `web3Config.base` is the right one.
=> stream-metadata: fix opensea invalidation url

.github/workflows/Bytecode_diff_report.yml, .github/workflows/Upgrade_network_facets.yml
To prevent these actions from running on every branch in ci. They will be replaced / implemented in https://github.com/river-build/river/pull/1008/files.
=> add workflow dispatch rule on gh actions

packages/stream-metadata/src/routes/spaceMetadata.ts
Previously:
```json
{
"name": "My fancy space",
"description": "idk ;-;",
"image": "https://gamma.river.deliveryspace/0x9e5318618c141f3f9949250bf73fb98a9b22b03e/image"
}
```
This PR fix the url
=> stream-metadata: fix base url in space metadata endpoint

contracts/src/spaces/facets/owner/SpaceOwnerBase.sol, contracts/test/spaces/owner/SpaceOwner.t.sol
Updated space URI validation to accept empty URIs, defaulting to `${defaultUri}/${spaceAddress}`. Modified the test case to handle the new behavior and added assertions to verify the correct default URI is set.
Fully solves https://github.com/HereNotThere/harmony/pull/7942.
=> fix(contract): refactor space URI validation to allow empty URIs

packages/stream-metadata/src/logger.ts
pino log levels were showing up as `30` for `info` and `50` for `error`, but this causes all logs to appear as if they were info logs. this pr formats the level field so that we can properly categorize and visualize all error logs.
=> formatting stream-metadata log levels as strings instead of numbers

packages/sdk/src/mediaWithEntitlements.test.ts
One stray test was not migrated to branch on which space version to create depending on test suite, and is always making legacy spaces. This PR fixes that test to use the space determined by environment variables to E2E suites run locally and in CI can correctly exercise both legacy and v2 spaces.
=> Fix media entitlement test that mistakenly always created legacy spaces

scripts/bytecode-diff/README.md, scripts/bytecode-diff/cmd/root.go, scripts/bytecode-diff/cmd/run_util.go, scripts/bytecode-diff/scripts/upgrade-facets.sh, scripts/bytecode-diff/templates/header.html, scripts/bytecode-diff/templates/report.html, scripts/bytecode-diff/utils/diff.go, scripts/bytecode-diff/utils/ethereum.go, scripts/bytecode-diff/utils/utils.go
Small enhancements to report.html (see gamma-reports.river.build)
- refactors "origin" to "source" to reflect source environment for clarity
- add header to html with source, target environment fields
- adds column to visually illustrate when hash differs between source and target env for facet
=> NET-82 update enhancements to diff report.html

core/node/events/stream_cache.go, core/node/events/util_test.go, core/node/rpc/create_stream.go, core/node/rpc/node2node.go
River chain provider frontend used by node B can be behind frontend used by node A, so even if tx is observed as committed by node A, it's not necessary true for node B yet. This adds waiting with timeout for record to get initialized if requested stream is unknown.
Fixes #1059
=> Add waiting for the stream replica to be created with timeout

packages/sdk/src/persistenceStore.ts
the error log was overwriting the log level of the log log.
=> fix level of csb:persistence

core/node/nodes/node_registry.go
I believe this is the only needed stream node change to capture the operator field when detecting NodeAdded events.
branched off of https://github.com/river-build/river/pull/1089
=> Stream node to capture operator address on NodeAdded event

packages/stream-metadata/src/node.ts, packages/stream-metadata/src/routes/spaceMemberMetadata.ts, packages/stream-metadata/tests/integration/spaceMemberMetadata.test.ts
Should close TOWNS-12131
Example:
https://testnets.opensea.io/assets/base-sepolia/0xfc4c8ab90d7b43e1a3b316c400e53b53640f132b/0
```json
{
"name": "pls opensea - Member",
"description": "Member of pls opensea",
"image": "<stream-metadata-service>/space/0xfc4c8ab90d7b43e1a3b316c400e53b53640f132b/image",
"attributes": [
{
"trait_type": "Renewal Price",
"display_type": "number",
"value": 0
},
{
"trait_type": "Membership Expiration",
"display_type": "date",
"value": 0
},
{
"trait_type": "Membership Banned",
"display_type": "string",
"value": "false"
}
]
}
```
https://testnets.opensea.io/assets/base-sepolia/0x9bd136d3155316d5d6dfcd4f87d5ee1a3ea8f22d/755
```json
{
"name": "HNT ALPHA - Member",
"description": "Member of HNT ALPHA",
"image": …
```
=> stream-metadata: space member metadata

packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/src/routes/profileImage.ts, packages/stream-metadata/src/routes/spaceImage.ts, packages/stream-metadata/src/routes/userBio.ts
This PR improves our `undefined` and `try-catch` hygiene. I originally intended this PR to take care of various http status codes and cache-control header edge cases. But that work-item requires a good understanding of our varying failure modes - which this PR aims to simplify. A common theme: the differences between expected errors, unexpected errors, and the meaning of missing data. A followup PR will improve error handling by having library code communicate its error modes to the api layer not via throws but via extended return types. This will help with custom cache-control and http status handling, instead of blanket 404'ing on everything with the exact same cache control headers.
a) The type information on `sv: StreamStateView` indicates that it can't be undefined. And in the past …
=> stream metadata service - internal api improvements

core/go.mod, core/go.sum, core/node/events/miniblock_producer.go, core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_sync_task.go, core/node/events/stream_view.go, core/node/events/stream_view_test.go, core/node/events/util_test.go, core/node/registries/river_registry_contract.go, core/node/rpc/add_event.go, core/node/rpc/forwarder.go, core/node/rpc/miniblocks.go, core/node/rpc/node2node.go, core/node/rpc/repl_test.go, core/node/storage/pg_storage.go, core/node/storage/storage.go
With stream replications it is possible that a local stream advances when the node is down. 
This change adds support to the node that at boots it will compare streams from its local database with the streams registry. When the database is out of sync the node requests missing blocks from peers and write them to the database bringing the database and contract in sync.
closes #494
=> core/node: reconcile streams with peers on node start

core/node/protocol/protocol.pb.go, core/node/protocol/protocolconnect/protocol.connect.go, core/node/rpc/service_sync_streams.go, protocol/protocol.proto
Add RPC endpoint that accepts a list of streams to add/remove to/from a pending sync subscription and add them one by one as fast as possible and report any failures back to the client.
=> core/node: Add RPC endpoint to add multiple streams at once to sync operation

contracts/src/tokens/river/base/River.sol, contracts/test/river/token/base/RiverBase.t.sol
- remove extra transferVotingUnits call in River.sol _update hook.
- updates test
=> remove extra transferVotingUnits call in base River

contracts/src/tokens/river/base/River.sol, contracts/test/river/token/base/RiverBase.t.sol
Added a test to ensure vote delegation works correctly for River tokens. The test verifies the consistency of current and past vote counts and checks vote transfer behavior through multiple assertions and emitted events. Included additional logging to aid in debugging.
=> test(contract): add vote delegation test

contracts/src/spaces/facets/membership/metadata/MembershipMetadata.sol, packages/sdk/src/spaceDapp.test.ts
So that we can render the member metadata for each member properly
the service returns this
```
return {
name: `${name} - Member`,
description: `Member of ${name}`,
image: `${config.streamMetadataBaseUrl}/space/${spaceAddress}/image`,
attributes: [
{
trait_type: 'Renewal Price',
display_type: 'number',
value: renewalPrice.toNumber(),
},
{
trait_type: 'Membership Expiration',
display_type: 'date',
value: membershipExpiration.toNumber(),
},
{
trait_type: 'Membership Banned',
display_type: 'string',
value: String(isBanned),
},
],
}
```
=> Add /token/:tokenId to the end of the space member tokenUri

packages/stream-metadata/src/riverStreamRpcClient.ts
Wait a bit and retry if we get ~~any error~~ a bad connection error from the rpc node. 
This will introduce a overhead in the unhappy path, but hopefully we can convert some possible unhappy response to happy responses :D (especially around the `getStream` errors)
=> stream-metadata: add retry to rpc client

packages/sdk/src/rpcInterceptors.ts
This updates cause the retryInterceptor to retry if we find a `DB_OPERATION_FAILURE` error
=> sdk: allow retry in db operation failure

packages/stream-metadata/src/routes/profileImage.ts, packages/stream-metadata/src/routes/spaceImage.ts, packages/stream-metadata/src/routes/userBio.ts
We create the space on-chain before creating the stream.
With the 404 cache, we could accidentally hit `/space/{spaceAddress}/image` before the stream creation, causing and error and caching it. We don't want this for now.
=> stream-metadata: remove cache for 404 (stream not found/image not found)

core/node/auth/auth_impl.go, packages/sdk/src/disableChannel.test.ts, packages/sdk/src/disableSpace.test.ts
In authorization checks:
- update space and channel isEnabled check to propogated isEnabled, error state back to entitlement check
- in entitlement check, only return a disallowed result if the space or channel is disabled. If there was an error in evaluating either state, return the error.
These changes should prevent users from being booted from channels in the event of partial or total base availability outages.
As part of this PR, I added some happy path e2e tests for disabled channels and spaces. This does not check the specific bug I was fixing but should help prevent regressions in general.
=> Space, channel isEnabled errors propagate back to caller

core/xchain/entitlement/check_operation.go, core/xchain/entitlement/entitlement.go, core/xchain/entitlement/entitlement_test.go
Logical AND and ORs were dropping errors and causing false negatives for entitlement evaluations. This PR makes changes Logical operand evaluation to ignore errors only when we definitely know the user was or was not entitled.
specifically, for AND operations:
- if a single child evaluates to false, return false
- otherwise, if either errors, return an error
For OR operations:
- if a single child evaluates to true, return true
- otherwise, if either child operation errors, return an error
=> Update AND and OR operation evaluation to properly propagate errors

contracts/scripts/interactions/InteractSetDefaultUriLocalhost.s.sol, contracts/src/spaces/facets/owner/SpaceOwnerUriBase.sol, contracts/test/spaces/owner/SpaceOwner.t.sol, packages/sdk/src/spaceDapp.test.ts
#1156 set this as `/{spaceAddress}` and `/{spaceAddress}/token/{tokenId}`
but the endpoint on the stream metadata service uses the `/space` prefix
so its supposed to be: `/space/{spaceAddress}` and `/space/{spaceAddress}/token/{tokenId}`
=> fix: add /space prefix to space owner default tokenURI

packages/sdk/src/client.ts, packages/sdk/src/sign.ts, packages/sdk/src/tags.test.ts, packages/sdk/src/tags.ts, protocol/protocol.proto
i added a react/reply indicator
a group mention type, which at the moment is just @channel but could support @everyone or @here or @role later
a mentions array for users mentioned
a participating array that grabs people who have replied to a thread or emoji'd the original message
work i expect the notification service to do
- figure out who gets notified for @channel
- figure out if this is a dm or gdm and notify accordingly
things i just skipped
- there's all this weird code about attachment notifications, i.e. "attachmentUsersTagged" that seems like it should just never happen, so i've ignored all that. 
- attachment mime types... seems like you should just decrypt things to figure that out.
=> Add tags message to StreamEvent, populate with channel message data

core/scripts/docker-compose.yml
Background: individual deployments (e.g. multi) deploy up to 10 servers at once, and each is provisioned to expect solo access to it's own database with 1000 connection limit.
Increase max connections on local postgres to 30k to accommodate up to 30 nodes deployed and in high usage simultaneously.
=> Increase connections count for local postgres to support local dev

packages/sdk/src/client.ts
During ci this occasionally gets hit. I’m assuming that we stop the client and clear the streams but an async task finishes and broadcasts on stream initialize.
Callstack:
```
stream not found
15 |
16 | export function throwWithCode(message?: string, code?: Err, data?: any): never {
> 17 |     const e = new CodeException(message ?? 'Unknown', code ?? Err.ERR_UNSPECIFIED, data)
|               ^
18 |     log('throwWithCode', e)
19 |     throw e
20 | }
at throwWithCode (../../../river/packages/dlog/src/check.ts:17:15)
at check (../../../river/packages/dlog/src/check.ts:31:9)
at scrollbackUntilContentFound (../../../river/packages/sdk/src/client.ts:1303:13)
at Client.onStreamInitialized (../../../river/packages/sdk/src/client.ts:1311:14)
at Client.<anonymous> …
```
=> Fix for flaky test: Update check in onStreamInitialized

contracts/src/spaces/facets/owner/SpaceOwnerUriBase.sol, contracts/test/spaces/owner/SpaceOwner.t.sol, packages/sdk/src/spaceDapp.test.ts
This reverts commit 45cd228b0c6333219465cf2c22b6118a42fad5df.
Caused `/space/space/` as a side effect.
=> revert: /space prefix to space owner default tokenURI #1183

packages/sdk/src/updateRole.test.ts, packages/sdk/src/util.test.ts, packages/web3/src/entitlement.ts
https://linear.app/hnt-labs/issue/TOWNS-12637/%5Balpha%5D%5Buser-feedback%5D-unable-to-update-membership-of-a-town-gated-by was caused by towns with empty rule datas being initialized with an encode no-op rule data instead of empty bytes. This is an issue because the RuleEntitlementV2 contract will ignore NoOpRuleDatas when set on the contract, but the architect considers the rule data to be a valid entitlement if it is a non-empty byte array.
The most surgical change here is to encode `NoopRuleData`s as empty byte arrays. This allows us to continue using NoopRuleData as a placeholder for the empty RuleDataV2 which is consistent with what CreateRole expects on the spaceDapp, as well as the API/logic we exposed to create legacy spaces.
Follow up PR to revert when setEntitlement sets an …
=> [TOWNS-12637] Encode no op rule datas as empty bytes

contracts/src/spaces/entitlements/rule/RuleEntitlementV2.sol, contracts/test/crosschain/RuleEntitlementV2.t.sol, packages/sdk/src/updateRole.test.ts, packages/sdk/src/util.test.ts, packages/web3/src/entitlement.ts
Previously setEntitlement RuleEntitlementV2 ignored empty rule datas, but this created a bit of confusion with createSpace when the architect assumed a rule data was set when creating the minter role.
Here we update the contract to just always revert when setEntitlement doesn't actually set an entitlement as an extra guard to avoid creating spaces with an invalid view of entitlements on the minter role.
=> [TOWNS-12637] Update RuleEntitlementV2 to revert when zero length rule data is passed in

contracts/test/crosschain/RuleEntitlementUtil.sol
Initialize the operations array with size 1 instead of 0. Add a no-op entry to the operations array to ensure it is correctly populated. This addresses potential issues with operations array being empty.
=> test(contract): fix initialization of `RuleDataV2` operations array

packages/stream-metadata/src/environment.ts, packages/stream-metadata/src/routes/health.ts
in the event of a hanging request, the health check failure is not registered by the stream metadata service, but it is registered by the load balancer. this causes the service to get terminated, but the service is unable to detect the failure and log the error. this PR allows us to capture and log the error so that we can respond to it better
=> adding a timeout to stream metadata health checks to increase failure visibility

packages/sdk/src/streamStateView_Space.ts, packages/stream-metadata/src/routes/spaceImage.ts
We're seeing a lot of spaceImage failures, adding this to add more context to help investigation
=> stream-metadata: add logs when stream view is not space content

packages/stream-metadata/src/node.ts
This PR will allow us to run aggregate o11y queries based on request parameters. For example:
- What specific urls resulted in a specific error log
- What's the distribution of requests with respect to route, where an error was logged (and even narrow down based on a specific space id)
- What's the distribution of requests with respect to route, where a `Missing Cache-Control header` warning was logged? (so that we can detect them proactively)
=> adding more request details to the stream metadata logger

packages/stress/src/mode/chat/root_chat.ts
structured logs suck for humans
=> Fix for logging at the end of localhost stress tests setup

packages/stream-metadata/src/node.ts
fastify's default logging reports status codes of responses, without showing anything about the original request. this PR removes the default logger and replaces it with one that standardizes everything
=> custom logging logic for stream metadata service

packages/stream-metadata/src/node.ts
we're seeing multiple requests hitting the same `/media` endpoint, which should never happen. and there are a few other routes that are supposed to be cached and should not make it to the server, but we're still seeing them. i'm adding cache-control headers to the logger just to see if there's a pattern
=> adding cache-control headers to response logs in stream metadata

core/node/rpc/add_event.go, core/node/rpc/get_stream.go, core/node/rpc/scrub_test.go, core/node/rpc/service_sync_streams.go, core/node/scrub/stream_scrub_task.go
Also, ensure syncStreams is only scheduling scrubs for local streams.
#8232
=> convert TryScheduleScrub interface to take a SyncStream

contracts/src/diamond/facets/governance/votes/enumerable/VotesEnumerable.sol, contracts/src/tokens/lock/ILock.sol, contracts/src/tokens/lock/LockBase.sol, contracts/src/tokens/river/base/River.sol, contracts/src/tokens/river/mainnet/River.sol, contracts/test/river/token/base/RiverBase.t.sol
Eliminated the token threshold mechanism from the `River` contract, including the removal of the `MIN_TOKEN_THRESHOLD` variable and the `setTokenThreshold` function. Updated related tests to reflect these changes, ensuring consistent functionality throughout the contract.
Replaced `IntrospectionBase` and `LockBase` with `IntrospectionFacet` and `LockFacet` for better modularization. Removed redundant lock methods and corrected minor typos in comments for improved code clarity and maintainability.
Update logic in `_setDelegators` to handle edge cases for delegate assignment more efficiently. Simplify `River._delegate` by reusing the current delegate storage.
Fix delegation lock and add tests.
=> fix(contract): remove token delegation threshold and fix lock

core/config/config.go, core/config/testdata/databaseconfig_json.txt, core/env/local/common/common.yaml, core/node/storage/pg_storage.go
Can be set with "RIVER_DATABASE_ISOLATIONLEVEL" env var.
Allowed values: "serializable", "repeatable read", "read committed".
If not set or value can't be parsed, defaults to "serializable".
Intention is to migrate to "read committed" for performance reasons after testing is complete.
=> Add configuration for transaction isolation levels

core/node/events/stream_cache_test.go
temp disable flacky test. Passes locally, often fails on CI.
=> Disable flaky test "TestStreamUnloadWithSubscribers" 

packages/sdk/src/syncedStream.ts
Client init performance tweak. 
We're performing scrollbacks hoping to pick up renderable events. By skipping cached scrollbacks when the loaded miniblocks already contain a renderable event, we can return early.
Lowers the duration of `loadStreamsFromPersistence` on my machine with my user's streams from ~7500ms to ~6500ms.
This logic could also be tweaked to _guarantee_ that a stream contains a top-level renderable event.
=> avoid cached scrollbacks if stream contains a renderable event

packages/sdk/src/bob.test_util.ts, packages/sdk/src/client.ts, packages/sdk/src/restart.test.ts, packages/sdk/src/sign.test.ts, packages/sdk/src/sign.ts, packages/sdk/src/streamRpcClient.test.ts, packages/sdk/src/syncWithBlocks.test.ts, packages/sdk/src/syncedStreams.test.ts, packages/sdk/src/syncedStreamsLoop.ts, packages/sdk/src/unauthenticatedClient.ts, packages/sdk/src/util.test.ts, packages/sdk/src/workflows.test.ts, packages/stream-metadata/src/riverStreamRpcClient.ts
This pr doesn’t change behavior, just provides more flexibility when parsing streams
=> Update options to disable expensive validation during envelope parsing

packages/sdk/src/streamStateView_Members_Solicitations.ts
I don’t know if this caused any actual issues, but I’m going to be modifying this structure and it seems weird that we didn’t preserve the sort here.
=> Key solicitation correctness fix - key local and dispatched solicitations in sync

packages/sdk/src/clientDecryptionExtensions.ts
I have more and larger refactors coming, but this seemed useful to call out
participants includes left users, and instantiates a new set every time with joined, invited, and left users. And it is called inside a pretty hot loop.
I will optimize the hot loop in an upcoming pr
=> clientDecryptionExtensions, bugFix/perf improvement

contracts/src/tokens/river/base/River.sol, contracts/test/river/token/base/RiverBase.t.sol
Rearranged imports for better readability and added missing interfaces to the River contract. Updated test file to include checks for the new interfaces supported by the River contract.
Interface ID does not include inherited functions. Therefore `type(IERC5805).interfaceId` is 0.
=> chore(contract): use proper interface IDs in River contract

contracts/scripts/deployments/facets/DeployEIP712Facet.s.sol, contracts/src/diamond/utils/cryptography/signature/EIP712Facet.sol
Added external view functions `DOMAIN_SEPARATOR` and `nonces` to `EIP712Facet` for easier access. Updated deployment script to include new selectors in constructor.
Required for #878.
=> feat(contract): add convenience methods to `EIP712Facet`

packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/tests/decryptionExtensions.test.ts, packages/sdk/src/client.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/sign.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/streamStateView_Members.ts, packages/sdk/src/streamStateView_Members_Solicitations.ts, packages/sdk/src/sync-agent/river-connection/models/transactionalClient.ts, packages/sdk/src/sync-agent/river-connection/riverConnection.ts, packages/sdk/src/sync-agent/spaces/models/channel.ts, packages/sdk/src/sync-agent/syncAgents.test.ts
If we signature validation was disabled, run signature validation before sharing keys
I don't feel like we can safely turn off signature checks otherwise
=> Add signature validation checks to decryption extensions

packages/sdk/src/client.ts, packages/sdk/src/persistenceStore.ts, packages/sdk/src/streamUtils.ts, packages/sdk/src/syncedStream.ts
when scrolling backwards, we don’t care about any “state” events that have already been snapshotted, so don’t write them. we really only care about channel messages so that we don’t have to refetch them
=> Persistence Store - be more perscriptive about what we store in local storage

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/streamEvents.ts, packages/sdk/src/streamStateView_Members_Solicitations.ts
create targeted loop that does all work on high priority streams first (previously we were prioritizing decryption, but key solicitation was just whatever came first
optimize initialization and adding key solicitations. this is a really hot loop for large towns and these small changes help us out with cpu utilization
=> Improve performance of decryption and keysharing

contracts/src/tokens/river/base/delegation/MainnetDelegation.sol, contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol
Simplify and streamline delegation management by introducing helper functions `_removeDelegation` and `_addDelegation`. Ensure consistency in delegation-related operations and improve code readability. Also, add validation checks and update iteration style.
Consolidate delegation update functions and refactor logic for replacing and adding delegations. Simplify the `removeDelegations` process by removing the helper function.
=> refactor(contract): mainnet delegation for improved clarity and efficiency

packages/encryption/src/decryptionExtensions.ts, packages/stream-metadata/src/riverStreamRpcClient.ts
long term we should figure out a way to turn this back on
=> Optimize stream metadata service by skipping validation

packages/stream-metadata/src/opensea.ts, packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/src/routes/media.ts, packages/stream-metadata/src/routes/profileImage.ts, packages/stream-metadata/src/routes/spaceImage.ts, packages/stream-metadata/src/routes/spaceMemberMetadata.ts, packages/stream-metadata/src/routes/spaceMetadata.ts, packages/stream-metadata/src/routes/spaceRefresh.ts, packages/stream-metadata/src/routes/userBio.ts, packages/stream-metadata/src/routes/userRefresh.ts, packages/stress/src/mode/chat/root_chat.ts
https://getpino.io/#/docs/api?id=logging-method-parameters
Pino by default only serializes errors that: is the only param, like `logger.error(error)` or is in a err key like `logger.error({ err: new Error('oops') })`
=> use pino default err key

packages/sdk/src/bob.test_util.ts, packages/sdk/src/makeStreamRpcClient.ts, packages/sdk/src/streamRpcClient.test.ts, packages/sdk/src/syncWithBlocks.test.ts, packages/sdk/src/syncedStreamsLoop.ts, packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stress/src/utils/rpc-http2.ts
default to 30 seconds
we're seeing cases where get or create stream will hang forever
i want to be very generous with the timeout to allow long running requests to finish
I updated all syncStream requests to have -1 timeout which resets the value to undefined if i'm reading this code correctly https://github.com/connectrpc/connect-es/blob/f154e67629c4553a232c15c45f5f7bf5c7a1b02d/packages/connect-web/src/connect-transport.ts#L330
=> Add default timeout to our connect rpc handlers

core/node/events/stream_cache.go, core/node/rpc/tester_test.go
Should help to start with overloaded DB.
=> If reconciliation worker pools size set to 0, disable reconciliation.

contracts/test/base/registry/RewardsDistribution.t.sol, contracts/test/utils/TestUtils.sol
Changed the internal utility functions in `TestUtils` to be pure, adding randomness via `_callVm` for consistency. This also updated string comparison to use `LibString.eq` and simplified the `_createAccounts` method.
=> test(contract): make `TestUtils` pure and random

packages/web3/src/ContractTypes.ts, packages/web3/src/ISpaceDapp.ts, packages/web3/src/v3/SpaceDapp.ts
When disabling channels, passing names and roles is not required. To ensure the contract accepts this exception, the metadata param should be encoded to 0 bytes.
=> dApp: Enable empty metadata when updating channel status only

packages/sdk/src/persistenceStore.ts
Any key solicitation loaded from a previous version of the db will fail to validate. I didn’t think this would cause much of an issue but it turns out to mess up decryption a lot.
=> Bump version of persistence store to fix decryption

packages/sdk/src/legacySpace.test.ts, packages/sdk/src/mediaWithEntitlements.test.ts, packages/sdk/src/membershipManagement.test.ts, packages/sdk/src/spaceDapp.test.ts, packages/sdk/src/sync-agent/spaces/spaces.ts, packages/sdk/src/util.test.ts, packages/sdk/src/withEntitlements.test.ts, packages/stream-metadata/tests/integration/spaceMemberMetadata.test.ts, packages/stream-metadata/tests/integration/spaceMetadata.test.ts, packages/web3/src/ISpaceDapp.ts, packages/web3/src/v3/ISpaceArchitectShim.ts, packages/web3/src/v3/SpaceDapp.ts
There could be multiple SpaceCreated events in a single tx if you are using 4337, passing the sender to correctly match.
=> SpaceDapp: add senderAddress param to getSpaceAddress

packages/stream-metadata/src/aws.ts, packages/stream-metadata/src/constants.ts, packages/stream-metadata/src/environment.ts, packages/stream-metadata/src/node.ts, packages/stream-metadata/src/routes/refreshStatus.ts, packages/stream-metadata/src/routes/spaceRefresh.ts, packages/stream-metadata/src/routes/userRefresh.ts
We need to wait for refresh to finish before emitting `refreshMetadata` for space members nft.
Previously we tried polling both space and space member metadata and waiting eventId of the image to be equal
The previous attempt didn’t worked and also increased the load on the service. 
This PR solves it, adding a `/refreshStatus/:invalidationId` route. 
Now after a refresh we get the invalidationId, which we can use to poll `/refreshStatus/:invalidationId` on the client until the refresh is completed.
We dont need `/event` in the space image route anymore. I'll create a PR later
=> stream-metadata: add support for `/refreshStatus/:invalidationId`

packages/sdk/src/client.ts, packages/sdk/src/stream.ts
we have this nasty flaky test that happens very regularly now https://github.com/river-build/river/actions/runs/11509558048/job/32039872496?pr=1350
[Error: waitFor timeout waiting for streamMembershipUpdated]
It always seems to affect the spaceWithV2Entitlements, but i’ve seen it elsewhere, its actually been around since i first wrote these tests.
I have two theories:
1. the stream is getting initialized and updated before we add a listener to streamMembership updated
2. the stream is getting re-initialized while we are listening to a membership changed event, and the new state has the membership already set, so it doesn’t fire a new event
This Fix:
1. in waitFor, always pass a condition, check the condition before adding any listeners
2. in waitFor, also listen to the streamInitialized …
=> Attempt to fix flaky wait for membership tests

core/scripts/generate-certs.sh
We don’t need to print the certs into the logs.
=> Drop the -x in generate-certs.sh

core/env/local/common/common.yaml, core/node/storage/pg_storage.go
Deadlocks typically occur at read committed isolation level, at serializable they would manifest as serialization errors, which we already retry on. However we do plan to move back to read committed in the near future, and should retry on these anyway.
revert to serializable isolation level until we take row locks on es table for stream operations.
Note this PR only updates isolation level for local deployments, alpha / gamma / omega will need to be handled separately.
=> Switch local deployments to use serializable isolation level and retry txns on deadlock

contracts/src/tokens/drop/DropFacet.sol, contracts/src/tokens/drop/DropFacetBase.sol
Refactored `DropFacetBase` and `DropFacet` contracts to minimize redundant mapping lookups and optimize function calls. The changes enhance code efficiency and maintainability by reducing the number of parameter fetches and utilizing `unchecked` to avoid unnecessary safety checks.
=> perf(contract): refactor to reduce duplicate mapping lookup

packages/web3/src/ContractTypes.ts, packages/web3/src/ISpaceDapp.ts
- enable passing `UpdateChannelAccessParams` to `updateChannel` transaction (i.e. omitting roleIds)
- rename Status -> Access
=> DApp: nit UpdateChannel types

core/node/rpc/archiver.go, core/node/rpc/archiver_test.go
for the Continuous test case, streams are added because they are detected in the registry, and the call to ReadMiniblocks on the stream node may result in a stream not found since the stream node may not have yet allocated the stream node in storage.
This PR adds a retry in the archiver when a NOT_FOUND error is returned and extends test waits to accommodate the longer execution time.
=> Fix archiver race condition

packages/sdk/src/util.test.ts
These are always failing when they go through this utility
Our sync startup code is wild. Really hard to trace it all. My gut tells me there is a race where we either subscribe to a stream too soon or too late and we don’t get the push that the membership event was added to the space stream, but I can’t figure out where it is. If this fixes it we should burn all that code down and make something simpler.
=> Another attempt at fixing the flaky waitFor timeout waiting for streamMembershipUpdated

core/node/auth/permissions.go, core/node/rules/can_add_event.go, packages/sdk/src/client.ts, packages/sdk/src/spaceWithEntitlements.test.ts, packages/web3/src/ContractTypes.ts
Banning only worked for space owners
- contract uses Permission.ModifyBanning. Updates both TS and go code to match
- calling removeUser on space recursively calls removeUser for each channel, but the entitlement check for booting from channel was failing for a non-owner user w/ banning permission. Fixes so that in the case of ModifyBanning, the channel entitlement check will check space permissions
=> banning: change to Permission.ModifyBanning and fix entitlement check

packages/sdk/src/util.test.ts
legacy tests for space entitlements were incorrectly running against v2 spaces. This change fixes that and also adds error throwing to catch this issue anywhere else it may occur.
=> Fix space entitlement tests to properly create legacy spaces when configured to do so

packages/playground/src/components/blocks/timeline.tsx, packages/playground/src/routes/m/dm-timeline.tsx, packages/playground/src/routes/m/gdm-timeline.tsx, packages/playground/src/routes/t/channel-timeline.tsx, packages/react-sdk/src/useSendMessage.ts, packages/react-sdk/src/utils.ts
It was getting confusing and not ergonomic to work with union types on the UI everytime, every new change was touching this and just making it more complex.
=> react-sdk: runtime check streamId instead of union type

contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol
Replace the try-catch block with inline assembly for the permit call to reduce gas costs and improve efficiency. The new approach directly uses the selector and memory allocation, removing unnecessary overhead.
=> perf(contract): refactor `permit` call to use inline assembly

packages/web3/src/entitlement.test.ts, packages/web3/src/entitlement.ts
Add a builder for DecodedCheckOperations that can be used in harmony for constructing rule datas. Eventually I'd like to move all DecodedCheckOperation code to harmony.
This is part of a planned set of PRs to consolidate logic for constructing rule datas and harden them with better library-provided validation.
=> Add DecodedCheckOperationBuilder for validating constructed check ops

contracts/deployments/gamma/base/addresses/tieredLogPricing.json, contracts/src/spaces/facets/membership/pricing/tiered/TieredLogPricingOracle.sol, contracts/test/spaces/membership/pricing/TieredLogPricing.t.sol
The issue was that we were resetting the logarithmic scale at each tier boundary by subtracting the tier threshold. This caused the price to drop when moving to a new tier because we were essentially starting the logarithmic scaling from 1 again.
=> fix(contract): Tiered log pricing module bug

core/config/config.go, core/node/rpc/debug.go, core/node/rpc/multi.go, core/node/rpc/render/templates/debug/multi.template.html, core/node/rpc/render/templates/debug/storage.template.html, core/node/rpc/render/types.go, core/node/rpc/statusinfo/node_status.go, core/node/storage/pg_storage.go
The PostgresStatusResult for the local node was incorrectly being reported for all nodes in the network on the debug/multi and debug/multi/json endpoints. This PR does the following:
- remove local postgres status result from external nodes on the json page
- remove the pg status column from the debug/multi table, since we can't compute it for external nodes
- add a separate storage debug endpoint for inspecting these metrics
We also add the following stream-related metadata to our postgres metrics:
- MigratedStreams
- UnmigratedStreams
- NumPartitions
=> Refactor storage stats to have it's own debug endpoint and add stream-related metadata

contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol
Updated events in `IRewardsDistribution` to include the owner address, ensuring more detailed event logging. Modified corresponding implementations and tests to reflect this change, improving traceability in contract interactions.
=> fix(contract): add owner address to `RewardsDistribution` events

packages/web3/src/entitlement.ts
Tested against harmony and should fix the river merge.
=> Fix harmony userOps tests by changing default chainId back to 1n for DecodedCheckOps

contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol, contracts/src/base/registry/facets/distribution/v2/StakingRewards.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol
Adjusted reward calculation to maintain fractional precision by scaling rewards correctly. Renamed `currentReward` to `currentRewardScaled` to indicate the scaling operation. Updated event naming and applied necessary changes across functions and tests to support the new reward scaling logic.
=> fix(contract): refactor reward scaling to keep dust

core/node/crypto/delegate.go, core/node/notifications/auth.go
1) return errors everywhere so it’s possible to debug things
2) make sure we check `len(delegateSig) > 0` before checking delegateExpiryEpochMs
3) use crypto.RecoverEthereumMessageSignerPublicKey which does magic bit toggling to support ethereum signing spec
=> Notification Service: Fix bugs in challenge signing

core/config/config.go, core/env/common/config.yaml
that’s the default, no need to introduce snake case
=> Use camelCase everywhere for notifications config and fix sessionToken !== session_token

core/node/notifications/auth.go
We have the option to not expire delegate signatures, so accept that as a valid case
=> fix for delegate expiration check in notification service auth

packages/docs/mint.json
not useful for the final user
prev:
now:
=> docs: remove mintlify dashboard link on header

contracts/scripts/deployments/facets/DeployMainnetDelegation.s.sol, contracts/src/tokens/river/base/delegation/MainnetDelegation.sol, contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol
Implemented `getDepositIdByDelegator` in `MainnetDelegation` to retrieve deposit IDs by delegator. Updated related deployment script and delegation base contract to support this new function.
=> feat(contract): add `getDepositIdByDelegator` to `MainnetDelegation`

contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/StakingRewards.sol, contracts/test/base/registry/BaseRegistry.t.sol, contracts/test/base/registry/MainnetDelegation.t.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol, contracts/test/base/registry/StakingRewards.t.sol
This commit introduces a test to check for overflow scenarios in the stake function of the RewardsDistributionV2 contract. It simulates an overflow condition using stdError and ensures that the correct revert behavior is triggered.
Change the `totalStaked` and `stakedByDepositor` data types from `uint256` to `uint96` across multiple contracts to optimize storage. Ensure that the test suite properly bounds values within the new `uint96` range.
=> fix(contract): fix possible staking overflow

core/node/rpc/archiver.go
Continues integration tests fail [often](https://github.com/river-build/river/actions/runs/11854195132/job/33035852339#step:17:116) because get miniblock response error handling doesn't cover all paths.
=> rpc/archiver: ensure response exists after fetching  mini-blocks

packages/stream-metadata/package.json, packages/stream-metadata/src/riverStreamRpcClient.ts, yarn.lock
I think this is a first step before adding a LRU cache outlined here: https://github.com/river-build/river/pull/1345
This service is super bursty, if we have lots of traffic coming into it hopefully this will serve everything with the same resources.
Decrypting the space image is already debounced at the StreamStateView level, so this should make a visible impact.
=> Don’t allow more than one simultaneous stream/media/client request in stream-metadata service

.vscode/tasks.json
I’ve been wondering why i was failing to check in go protobuf definitions lately.
=> Fix build protobufs task in tasks.json to build all protobufs

core/node/http_client/client.go
This enables http2 ping on idle connections that haven't received a single frame in 20s. Connection is closed when pong isn't received in 15s.
=> node/http_client: enable http2 pings on idle connections

contracts/src/diamond/facets/ownable/token/TokenOwnableBase.sol, contracts/src/spaces/facets/membership/MembershipFacet.sol
Refactor the `joinSpace` function to use a properly initialized `ReferralTypes` struct instead of passing explicit default values. This change enhances code readability and follows best practices for struct initialization.
=> perf(contract): aesthetic touch

contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol, contracts/test/base/registry/MainnetDelegation.t.sol
Moved delegation and currentOperator extraction to method parameters, simplifying the control flow. Unified delegation setting steps to avoid redundant condition checks and ensure consistency in state updates.
Modify `MainnetDelegationBase` to remove delegation when quantity is zero. Add tests to ensure delegations with zero amounts are properly handled and to verify the correct functionality of remove and re-add scenarios.
=> fix(contract): refactor `MainnetDelegation` and handle zero delegation amount

core/env/local/common/common.yaml, core/node/rpc/info.go, packages/sdk/src/streamRpcClient.test.ts
I think we have these off because when we set them up there wasn't a great local config that we could put them into right?
=> Enable test apis when running locally by default

packages/sdk/src/client.ts, packages/sdk/src/syncedStreams.ts
I don’t think this is happening, but want to rule it out.
=> Add checks for defined stream ids

core/node/rpc/info.go, packages/sdk/src/makeAuthenticationRpcClient.ts, packages/sdk/src/makeNotificationRpcClient.ts, packages/sdk/src/makeStreamRpcClient.test.ts, packages/sdk/src/makeStreamRpcClient.ts, packages/sdk/src/rpcInterceptors.ts, packages/sdk/src/rpcOptions.ts, packages/sdk/src/util.test.ts, packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stress/src/utils/rpc-http2.ts
Previously a timeout would trigger the global abort signal and subsequent requests would die imediately and trigger weird errors on the node. Use a local abort signal in the interceptor, but still respect the global abort signal. Set timers and clean everything up properly.
Test plan:
Wrote a test and improved logs
=> Fix the retry interceptor

packages/sdk/src/client.ts
I guess I forgot that this function was here, because I’m not sure who else would have written it, but apparently we have a test that calls resetCrypo in a loop, and I noticed in the new vite tests its throwing warnings about 10+ listeners added to the same event https://github.com/river-build/river/actions/runs/11942779116/job/33290511830?pr=1582
this pr fixes this issue. This function isn’t called anywhere but the tests.
=> stop current decryption extensions in “resetCrypto” function

packages/playground/package.json, packages/playground/vite.config.ts, yarn.lock
This fix the warnings around using `@river-build/sdk` and  `@river-build/react-sdk` from `workspace:^`
=> playground: use tsconfig path vite plugin

contracts/scripts/deployments/facets/DeployRiverPoints.s.sol, contracts/src/spaces/facets/membership/join/MembershipJoin.sol, contracts/src/tokens/points/IRiverPoints.sol, contracts/src/tokens/points/RiverPoints.sol, contracts/test/airdrop/RiverPoints.t.sol
Created `IRiverPoints` interface to standardize points management across contracts. Moved point calculation logic to `RiverPoints` contract and updated `MembershipJoin` to use the new interface. Adjusted tests to reflect these changes.
=> refactor(contract): move calculation of river points

packages/stream-metadata/src/streamRegistry.ts
why did this start failing?
looking at fei's new space here https://fast-app.towns.com/t/0x2f104bd8e48ad006f2a6ce1a2a07d283a310543a/
this space exists, i can query the river registry for it and pull data from the river network, but when the stream registry tries to do it, it errors from the contract with NOT_FOUND
so far I think i've verified that
the stream registry address is the same
the calls to the stream registry haven't changed
can anybody think of other places to look?
here's the log
https://app.datadoghq.com/logs?query=env%3Aomega%20service%3Astream-metadata%20%40req.params.spaceAddress%3A0x2f104bd8e48ad006f2a6ce1a2a07d283a310543a&agg_m=count&agg_m_source=base&agg_t=count&cols=env%2Cservice%2Ccontainer_index&event=AwAAAZNWLm3Nb5dUOwAAABhBWk5XTG5jSkFBQ3RUYjRQdWFhOTJnQUMAAAAkMDE5MzU …
=> Call riverRegistry.getStream with streamIdAsBytes

contracts/scripts/deployments/facets/DeploySpaceDelegation.s.sol, contracts/src/base/registry/facets/delegation/SpaceDelegationFacet.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol, contracts/test/base/registry/BaseRegistry.t.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol, contracts/test/base/registry/SpaceDelegation.t.sol
Introduce reward sweeping when updating space operators. This ensures that any unclaimed rewards are properly transferred to the current operator. Additionally, refactored validations and removed redundant checks for enhanced readability and maintainability.
=> fix(contract): add reward sweeping in `SpaceDelegationFacet`

core/go.mod, core/node/crypto/chain_txpool.go, core/node/crypto/chain_txpool_test.go, core/node/crypto/main_test.go, core/node/crypto/testutil.go
Clean shutdown is required so it's possible to simulate node restarts in the test.
This is first PR fixing shutdown cleanup across packages.
=> Fix goroutine leaks in core/node/crypto

core/config/config.go
We expect this to reduce the base rpc call volume significantly, perhaps up to 4x.
=> Increase scrub period to 4 hours

packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/src/routes/media.ts, packages/stream-metadata/src/routes/spaceImage.ts, packages/stream-metadata/src/streamRegistry.ts, packages/stream-metadata/src/types.d.ts
ref TOWNS-15132
we’re still seeing issues looking up nodes for spaces and I don’t really get what’s going on, but this bit can’t be helping. I’m assuming somewhere we either add an extra 0x or miss an 0x? either way we don’t need it.
=> Get rid of goofy conversions in the stream-metadata service

packages/create-river-build-app/src/modules/clone-playground.ts, packages/docs/sdk/react-sdk/getting-started.mdx, packages/playground/package.json, packages/playground/src/App.tsx, packages/playground/src/components/dialog/env-switcher.tsx, packages/playground/src/components/form/channel/create.tsx, packages/playground/src/components/form/space/create.tsx, packages/playground/src/components/form/space/join.tsx, packages/playground/src/config/wagmi.ts, packages/playground/src/routes/auth.tsx, packages/playground/src/routes/t/space-channels.tsx, packages/playground/src/utils/viem-to-ethers.ts, packages/react-sdk/README.md, packages/react-sdk/src/useAgentConnection.ts, yarn.lock
With `create-river-build-app`, we're now handling new projects setups. We dont want to use outdated dependencies in our projects, and we dont want to suggest this to the world.
This PR updates wagmi & viem dependencies in the playground (which is a template in the `create-river-build-app` script)
=> playground: update viem & wagmi

core/node/events/notifications_stream_tracker.go, core/node/notifications/event_processor.go, core/node/notifications/push/push.go, core/node/notifications/push/push_test.go, core/node/notifications/sync/streams_tracker_worker_connectgo.go, core/node/notifications/user_preferences_store.go, core/node/rpc/notification_test.go, core/node/storage/pg_notification_store.go
When the notification service tries to send a webpush notification and receives a `410 - Gone` the subscription is expired. This indicates that either:
- the user unsubscribed from notifications in the browser
- the browser has renewed the subscription and the notification service didn't got an update with the new endpoint.
This change deletes the expired subscription from the database. It takes the endpoint into considering meaning that in case the user refreshed the subscription with the new endpoint there is no race condition that deletes it immediately due to the 410 error.
=> notifications: delete expired webpush subscription automatically

core/node/rules/can_add_event.go
#1643 
This change updates the entitlement check for a adding a user to the space stream to check for space membership instead of looking for the READ permission. Since the requested auth was previously of kind `chainAuthKindSpace`, previously the authorization module would look for at least 1 role on the space with READ permission that the wallet satisfied in order to allow the join event, which makes no sense. However, we ended up satisfying this in practice because the member role is typically an EVERYONE User Entitlement role, and it has the READ permission attached.
The new check is a a chainAuthArgs of kind `chainAuthKindIsSpaceMember`, which does not check any entitlements at all, it just validates that the user is a space member.
This permissions check actually relaxes the …
=> Update space membership join to use isSpaceMember

core/node/rpc/archiver_test.go, core/node/rpc/notification_test.go, core/node/rpc/shutdown_test.go, core/node/rpc/tester_test.go
This PR adds subtest setup & support to serviceTester (so `t`, `require` and `ctx` are correct).
It's used in notification tests, and also makes notifications tests parallel, making them significantly faster.
Additionally `Never` timeout is reduced to 1 second.
=> Speed up notifications tests

core/cmd/stream_cmd.go
Adds support to the river_node binary to dump a stream event. This is useful for debugging purposes.
```
$ ./env/omega/run.sh stream event 88a126f40682b1f7ea23a387822e210e74b5ea820909822e60153c0d2d049605 1c0fef8a81be6661bb7aee269e9d8d4e268a94acd171eb208f3c5a5645221129 50
{
"creatorAddress": "6YCbyIuHD3Q2Hskfo1c3NKIG/sw=",
"delegateSig": "bABTh/Pw3J/sclGv27XA+9KZFr40SGUemy5sOguqQ3shzmxYPKs7226kcCdB9ztAG/Ik9NfKY1lI5CAn6GNN8xs=",
"salt": "5Fnr/mz8RacmI1+Q3gX97g==",
"prevMiniblockHash": "1PprwlOjbdYRwuyXwjo6FAWEa6d+XCxJL4yxeDCt9qI=",
"createdAtEpochMs": "1732697450905",
"tags": {
"messageInteractionType": "MESSAGE_INTERACTION_TYPE_POST"
},
"dmChannelPayload": {
"message": {
"ciphertext": "AwjGARLAEvJ9pFV9pmhu/4oW6cXl3Ow+M8lTd+augXq3NmH9HNxpcMJmU1Ai9rukvEAyQiWsjRSMdUPjuK6GjwnVjXqV1mLxcl3HP26g0G …
```
=> river_node: add support to dump stream event

packages/playground/src/components/dialog/env-switcher.tsx, packages/playground/src/components/form/channel/create.tsx, packages/playground/src/components/form/space/create.tsx, packages/playground/src/components/form/space/join.tsx, packages/playground/src/utils/viem-to-ethers.ts, packages/react-sdk/README.md, packages/react-sdk/src/useAgentConnection.ts
in #1647 I changed `useEthersSigner` to `getEthersSigner`, moving from a hook to a action. But this introduces `@wagmi/core`, which tbh we dont want.
Moving back to the hook approach
=> playground: dont use `@wagmi/core` to get ethers signer

core/config/config.go, core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_cache_test.go, core/node/events/util_test.go, core/node/rpc/add_event.go, core/node/rpc/get_stream.go, core/node/rpc/scrub_test.go, core/node/rpc/server.go, core/node/rpc/service.go, core/node/rpc/service_sync_streams.go, core/node/rpc/tester_test.go, core/node/scrub/stream_scrub_task.go
This eliminates the need for separate scrubbing calls across the codebase (and simplifies other refactorings) and efficiently checks if scrubbing should be performed while lock is taken.
=> Refactor scrubbing to be triggered on getting a view for local stream

packages/sdk/src/sync-agent/syncAgent.ts, packages/stress/src/utils/stressClient.ts
This cuts way down on the amount of cpu that they need to run.
=> Add unpackEnvelopeOpts to the stress client

core/node/rpc/sync/client/syncer_set.go, core/node/rpc/sync/operation.go
seeing this in CI here: https://github.com/river-build/river/actions/runs/12148899395
A stream that is in the messages as add sync, but is not in the initial cookies will get subscribed to twice if these two calls race. Because addstream adds a new syncer to the sync map and initiates a sync - and then Run() loops over the sync map and initiates a sync… again
`go Run()`
and `select msg, ok` race…
Add stream starts a receiver for a specific stream
Then run starts all the receivers, leading to a double receive.
It fixes my issue locally, I had a 100% repro rate before.
```
==================
WARNING: DATA RACE
Write at 0x00c000d88318 by goroutine 9335:
connectrpc.com/connect.(*ServerStreamForClient[go.shape.a7910b12a1f7e21c2031c35e486da9da719560dc54d80219f7b879d3ee7e8afb]).Receive() …
```
=> Fix race condition in syncer_set startup

packages/playground/src/components/blocks/timeline.tsx, packages/react-sdk/src/index.ts, packages/react-sdk/src/useAdminRedact.ts, packages/sdk/src/sync-agent/dms/models/dm.ts, packages/sdk/src/sync-agent/gdms/models/gdm.ts, packages/sdk/src/sync-agent/spaces/models/channel.ts, packages/sdk/src/sync-agent/timeline/timeline.test.ts
Example of admin redact will be add later - we need to have an example of what is an admin and how you can add someone as an admin (aka permissions - future priority)
=> react-sdk: useRedact should call `sendChannelMessage_Redaction`

core/node/crypto/client.go, core/node/crypto/contract_names.go
- fixed msg.Data length check to capture calls with no parameter data
- register ierc5313 contract selectors for space ownership checks
=> [BUGFIX] - Contract names fix for parameterless calls with ethCall metrics

scripts/generate_sdk_index.sh
We moved the tests in to a folder, let's not export the helper scripts
=> Exclude */tests/* from generate_sdk_index.sh

core/node/crypto/chain_txpool.go, core/node/infra/metrics_publisher.go, core/node/rpc/metrics_interceptor.go, core/node/storage/pg_storage.go, core/xchain/entitlement/evaluator.go, core/xchain/server/server.go
I partnered with @mechanical-turk to discuss our highest cardinality metrics and to shave down cost while maintaining observability where possible. Here is a proposal to reduce the granularity of buckets for several histogram metrics.
=> Reduce histogram buckets and tune bucket range and intervals

.github/workflows/ci.yml
This update ensures that the BASE_RPC_URL secret is available during the execution of unit tests in the CI workflow. Including this environment variable is necessary for tests that depend on a specific RPC endpoint configuration.
=> chore: add `BASE_RPC_URL` environment variable to unit tests

core/node/notifications/types/preferences.go, core/node/rpc/notification_test.go, core/node/storage/pg_notification_store.go
I don’t have a good api to “unset” a channel setting.
The RemoveChannelSetting seems unused, wired it up to fire when i post unspecified for a channel.
Does this seem okay? Alternatively I could just keep the change in preferences.go that ignroes the unspecified channel setting.
=> Notifications service, remove channel setting when updating to unspecified

contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol, contracts/src/tokens/river/base/delegation/IMainnetDelegation.sol, contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol, contracts/test/base/registry/MainnetDelegation.t.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol
Updated the rewards claiming logic to improve clarity and include mainnet delegation via `MainnetDelegationBase`. Adjustments were made to distinguish between authorized claimers for operators and beneficiaries, enhancing the contract's maintainability and security.
=> fix(contract): refactor rewards claiming logic for mainnet delegation

.vscode/tasks.json
this kills the log tail task which frees up the window to accept the next launch
the restart just task doesn't work for me, the server isn't available to my tests after restart, and also i want to see the logs.
=> Fix the restart cacablanca vscode task

contracts/src/spaces/facets/membership/join/MembershipJoin.sol
Ensure the correct receiver address is passed and used throughout the membership join process. This fixes an issue where points were minted to the sender instead of the intended receiver.
=> fix(contract): mint points to membership receiver

core/node/events/miniblock.go, core/node/events/minipool.go, core/node/events/stream_view.go
I have a new case where I’d like to return early from a forEachEvent function.
I returned `false, nil` from my inner lambda, and that exited the current iteration, but then just skipped to the next miniblock.
This was not the behavior that I was expecting.
Update all loops to have the same behavior, returning error or continue=false will exit the iteration.
=> Change forEachEvent functions to be consistant

core/node/events/stream.go
- Clarify thread-safety of each method in comments so it will show up on mouse hover in IDEs.
- rename a couple of methods for clarity
- refactor to remove unused parameters
=> StreamImpl comments, method renames, cleanup

scripts/publish-to-npm.sh
this should be a no-op, but it keeps us from making human errors and keeps this directory up to date with the source of truth
=> Update publish to npm script to keep contract addresses up to date

packages/playground/package.json, packages/playground/vite.config.ts, packages/sdk/package.json, packages/stress/esbuild.config.mjs, packages/stress/package.json, yarn.lock
- adds `mls-rs-wasm` as a dependency of `sdk`,
- fixes packaging for `stress`, and
- fixes packaging for `playground`.
=> Add mls-rs-wasm as dependency and fix WASM packaging

packages/web3/src/ISpaceDapp.ts, packages/web3/src/v3/Space.ts, packages/web3/src/v3/SpaceDapp.ts
I thought it made more sense to be able to pass receiver here. But after writing some tests, I realized the membership nft could be in any linked wallet - and that is where the tip is going to go.
It's confusing to have a parameter called receiver, then internally fetch linked wallets, and have the tip go potentially to another address. So instead callers can pass the tokenId using getTokenIdOfOwner
=> SpaceDapp: change tip to receive tokenId instead of receiver address

contracts/scripts/interactions/InteractAlphaSparse.s.sol, contracts/scripts/interactions/InteractRiverAlphaSparse.s.sol, contracts/scripts/interactions/helpers/AlphaHelper.sol
Fixes bug in Interact*Sparse facet upgrade scripts. Foundry requires struct fields to be defined in solidity in alphabetical order as a BTree is constructed of the raw json file prior to parsing.
=> fix: alphabetically order struct fields for foundry json parser

packages/sdk/src/sync-agent/river-connection/riverConnection.ts
the client wasn’t made to retry “initializeUser()”
if we get an error in that function, the retry loop will always fail because “user is already initialized”
move the client instantiation to the login group.
=> change oder of login operations in the syncAgent.riverConnection

packages/sdk/src/client.ts, packages/sdk/src/makeStreamRpcClient.ts
we're seeing a perf regression on towns, not sure if this is it, but it could be a problem.
the cached and non-cached blocks were getting inserted in the wrong order, original order here  https://github.com/river-build/river/commit/ecefe239ca21a1e383c975e634a8f7f5578cdb8f
if for some reason the node didn’t return any streams, the client could get stuck in a while loop
=> Fixes for new getMiniblocks function

contracts/scripts/deployments/facets/DeployRewardsDistributionV2.s.sol, contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionStorage.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol
Introduced functions to set and retrieve the period reward amount in the `RewardsDistributionFacet`. Updated related storage, events, and deployment script to support the new functionality, along with corresponding tests for validation.
=> feat(contract): add period reward amount to `RewardsDistribution`

packages/sdk/src/client.ts, packages/sdk/src/makeStreamRpcClient.ts, packages/sdk/src/unauthenticatedClient.ts
We're seeing the route return 0 for the response.fromInclusive when it shouldn't be...
Revert "Updated SDK to paginate miniblocks (#1790)"
This reverts commit ecefe239ca21a1e383c975e634a8f7f5578cdb8f.
Revert "Fixes for new getMiniblocks function (#1840)"
This reverts commit cd79d8d922d4eed424afd7e87737f7f95b4753a7.
=> Revert changes to paginate miniblocks

core/node/rpc/create_stream.go, core/node/rules/can_create_stream.go
When we create a space we also imediately create a channel
In a replicated streams scenerio, it is tricky to get the membership event for the space join replicated in time in order to pass the checks for creating the channel stream
There are ways to do this, we thought about passing a block number of the user stream event with the create channel event, but this will slow down space creation event more.
Depend instead on the existing blockchain check that gates channel creation
Add new checks that make sure streams exist for any derived event that will be added after channel creation
=> Remove space membership check on user stream when creating channel

core/config/config.go, core/node/crypto/client.go, core/node/crypto/config.go, core/node/rpc/archiver.go
The archive nodes were becoming unhealthy after reporting a panic in the logs:
```
panic: interface conversion: interface {} is nil, not string
```
This error turned out to arise from a method to convert blockchain errors into readable strings. After fixing it, we get
```
Error: archiver.start: (56:CANNOT_CALL_CONTRACT) Contract Returned Error | StreamRegistry.GetPaginatedStreamsGetPaginatedStreams smart contract call failed base_error: request timed out
```
This issue was arising when the start go routine encountered an error while reading paginated streams from the registry. if this call fails, the archiver will shut down. To fix, I reduced the default page size to 1k and added retries on the GetPaginatedStream call.
=> [BUGFIX] - Fix crash-looping archiver and log panic

core/node/auth/auth_impl.go, core/node/rules/can_add_event.go
This reverts commit 42b4c3a8e46538f39a426d4302922de407111f94.
Instead i want to validate the receit matches the metadata, then i'll do the linked wallet check against the from in the metadata
=> Revert "experiment with parsing logs for sender (#1870)"

core/node/rules/can_add_event.go
creator to sender, not from to sender, oops
couldn’t figure out how to test this locally
=> fix parameters for tip linked wallet check

core/node/events/snapshot.go, core/node/rules/rule_builder.go
when i converted these from `fmt.Errorf` it didn’t pick up the formatting. just putting the content in the log doesn’t do what i want.
=> Fix river errors with missing info in %T

contracts/src/river/registry/facets/stream/StreamRegistry.sol
With https://github.com/river-build/river/pull/1923/commits/1c63faedffe99c6574a75645c1b9ecb79c406fae the genesis block is never removed because `stream.lastMiniblockNum` is updated before the check it's `0`. Do this check and deletion before the update.
=> river stream registry: delete genesis when stream advanced

core/node/base/test/context.go, core/node/events/miniblock_producer.go, core/node/events/stream.go, core/node/rpc/forwarder.go, core/node/rpc/repl_test.go, core/node/rpc/tester_test.go, core/node/storage/pg_stream_store.go
This PR separates out some additional logging and population of error metadata in returned errors that mostly only occurs in the case of error conditions, and should not affect total log volume overly. The additional metadata has been helpful in tracking down what may be happening when searching for race conditions in the code.
It also adds a service tester configuration to enable logging for specific test cases.
=> Add logging metadata to help debug race conditions in replication

core/mls/mls-tools/Cargo.lock, core/mls/mls-tools/crates/mlslib/Cargo.toml, core/mls/mls-tools/crates/protocol/Cargo.toml
Remove some unused dependencies and add missing entries to mlslib Cargo.toml.
=> cleanup mls-tools cargo workspace

core/config/config.go, core/node/rpc/debug.go, core/node/rpc/render/templates/debug/stream.template.html, core/node/rpc/render/types.go, core/node/storage/pg_stream_store.go, core/node/storage/storage.go
Add a debug endpoint for printing stream debug statistics:
- latest miniblock number
- last snapshot block number
- minipool length
- candidate hashes and block numbers
=> [RIVER-1950] Stream debug endpoint

packages/sdk/src/streamEvents.ts
Events are matching MLS-specific messages from protocol.proto.  In addition, we are adding MLS-specific event for processing new encrypted content, so that we can have a separate code path for MLS downstream.
=> Add MLS-specific events to StreamEncryptionEvents

contracts/scripts/deployments/facets/DeployMainnetDelegation.s.sol, contracts/src/tokens/river/base/delegation/IMainnetDelegation.sol, contracts/src/tokens/river/base/delegation/MainnetDelegation.sol, contracts/test/base/registry/MainnetDelegation.t.sol, contracts/test/base/registry/RewardsDistribution.t.sol, contracts/test/fork/ForkRewardsDistribution.t.sol
Removed legacy delegation methods in `IMainnetDelegation.sol` and replaced their usage in test contracts with mocked implementations. This improves maintainability and aligns with the latest delegation interface. Updated related test logic to use the new mock functions where applicable.
=> refactor(contract): remove deprecated mainnet delegation functions

packages/metrics-discovery/src/metrics-discovery.ts
we don't use these, and they increase our cardinality and thus metrics bills
=> remove operator + node address from prometheus labels

core/node/events/notifications_stream_tracker.go, core/node/notifications/sync/streams_tracker_worker_connectgo.go, core/node/rpc/notification_test.go
Currently the notification service doesn't handle sync updates that include miniblocks. The result is that once events are dropped from the minipool calculating the stream membership must be done from `snapshot + blocks + minipool` but is done from `snapshot + minipool`.
For notifications this is not an issue because these are handled immediately when the notification service receives them through a sync update. For user membership it needs to respect join/leave events in miniblocks.
This PR adds an unittest that hits the problem and introduces the `ApplyBlock` function that is called for incoming miniblocks.
=> notification service: bugfix tracking membership in new towns

scripts/launch-ci-tests.sh
This script will launch the specified number of CI tests for a particular branch. By default only go tests are enabled, but to change the specific workflows anyone can just edit the script according to the comments.
=> Add tool for launching a suite of ci tests

core/node/notifications/sync/streams_tracker.go, core/node/notifications/sync/streams_tracker_worker_connectgo.go, core/node/rpc/notification_test.go
```
--- FAIL: TestNotifications (0.74s)
--- FAIL: TestNotifications/DMNotifications (35.77s)
--- FAIL: TestNotifications/DMNotifications/MessageWithDefaultUserNotificationsPreferences (30.80s)
```
Not able to reproduce the issue locally but a possible scenario is:
- Notification service listens for StreamAllocated event. This is done by polling the chain for these events and can take some time. After it got the event it subscribes for sync updates and ignores all miniblocks/events that it got from the sync reset and starts only processing new incoming updates/events for notifications. This is to prevent sending duplicate notifications for events.
- During test initialisation a new stream is allocated and immediately events are sent to it. The test starts listening for notification for …
=> unittest: fix flaky notifications test

packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/encryptionDevice.ts, packages/encryption/src/groupEncryption.ts, packages/encryption/src/olmLib.ts, packages/sdk/src/tests/multi_ne/userInboxMessage.test.ts
we don't need these goofy defines, just use enums
=> Group Encryption Refactor 2: Split the alogrithms into basic/group, remove goofy defines

.prettierignore
Running `yarn prettier:check` will give false positives if `mls-tools` was built.
=> Ignore Rust target directory

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/client.ts
1. Use miniblockInfo.max instead of .min. this was a typo
2. Only send one key fulfillment. For the case of isNewDevice, any subsequent key fulfillment will get rejected, and this is more effecient all around.
=> Hybrid group encryption fixes

core/config/config.go, core/config/config_test.go
Bonus: add some test coverage for the top-level config.
=> [RIVER-2085] Omit sensitive fields from notifications config

core/cmd/archive_cmd.go, core/node/logging/sampling.go
This sampler will drop 95% of logs after a threshold of 10 logs of the same message has been met within a 10 second interval. Note that the sampler disregards context keys, e.g. two logs with the same message and different fields count towards the same threshold.
@mechanical-turk let me know if this looks reasonable, I can tune these numbers. The goal is to not filter on datadog because we want to guarantee we're seeing all of the errors.
I tested this locally by printing 50 log messages from the archiver on start, I see exactly what I expect. Sampling appears to work!
```
{"level":"INFO","timestamp":"2025-01-17T15:28:58.674-0800","msg":"Is this log message filtered?","instanceId":"bDlEpM3hKR0T","mode":"archive","nodeType":"stream","i":0} …
```
=> [RIVER-2049] Add sampling for archiver logs

core/justfile
fixes
```
ld: library not found for -lmls_lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
=> fix just file “run-go” command for new mls requirements

core/node/mls_service/mls_service.go
Remember to build Rust library using `just build`.
=> Fix CGO so that testing from VSCode work

core/node/rpc/add_event.go, core/node/rpc/create_stream.go, core/node/rpc/membership_scrub_test.go, core/node/rules/rule_builder.go, core/node/scrub/stream_membership_scrub_task.go
Tags allow us to signal to the notification service to deliver notifications.
In the case of tips, we add an event to the user stream, which adds an event to the recipient's stream, which adds an event to the channel
I will update the derived events created by the rules to forward the tags so that the notification server can properly deliver notifications
=> Update event tags to allow tag forwarding

packages/sdk/src/tests/multi/sync-agent/timeline.test.ts, packages/web3/src/v3/SpaceDapp.ts
Seeing new flakyness in the sdk tests. Seems like the build machine is either faster or slower.
The timeline test fails locally for me, forcing some miniblocks makes scrollback more preditable
The space is failing to mint in some instances, i feel like this will give us a better error message
=> Fixes and better errors for tests

core/node/rpc/add_event.go, core/node/rpc/create_stream.go
1) follow convention when creating new pointers to slices
2) check for nil on the returned Msg payload (i already checked for error)
3) don’t pre allocate the derived events slice, i don’t actually know how big it will be
=> Small fixes to the new returned event refs

core/node/events/stream_sync_task.go
There is an error in how the logging API is called in sync streams that is causing errors on the river node to print strangely in the logs, and may also be the source of a panic.
=> [BUGFIX] Logging fix for sync streams error message

core/node/infra/metrics_publisher.go
The current grpc duration distribution isn't suitable to get insights in longer lasting grpc calls such as `CreateStream` that submit and wait for a chain transaction. This change chooses a different distribution by adding a bucket and widening the current bucket sizes.
=> node: change grpc call duration metrics bucket distribution

packages/sdk/src/client.ts, packages/sdk/src/utils.ts
trying to figure out what's causing 15 second initialize user
quick tests on local, there's def some funky stuff going on outside of stream creation, i.e. initializeFromPersistence can take > 2 seconds
=> return durations in sdk intializeUser

core/xchain/entitlement/entitlement_test.go
Tests were flaking due to time deltas slightly > 50ms, increase to 100ms.
=> Increase threshold for measuring entitlement evaluation times to account for CI slowness

packages/encryption/src/base.ts, packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/groupEncryption.ts, packages/encryption/src/groupEncryptionCrypto.ts, packages/encryption/src/hybridGroupEncryption.ts, packages/encryption/src/tests/decryptionExtensions.test.ts, packages/sdk/src/client.ts, packages/sdk/src/mls/coordinator/coordinator.ts, packages/sdk/src/mls/epoch/epochSecretService.ts, packages/sdk/src/types.ts
this ended up being a large change - but mostly to just get the persistence layer changed over.
Olm still encrypts and decrypts strings…
For new encrypted data code where `version > 0`
- accept bytes to encode, use bin_toHex to convert to string before encrypting
- after decrypting, convert back to bytes with bin_fromHex before returning
For old data
- after decrypting, return string
=> Part 2 - Encryption: Add version to EncryptedData and switch to binary channel payload encoding

core/node/notifications/event_processor.go
use BytesToAddress in stead of hex string (it gives us the fancy capitalization.
fixes TOWNS-17847
=> Fix for sender name not showing in notifications

core/node/rpc/archiver.go
There are about 30 streams that were accidentally created when some nodes were running under their operator addresses, and these streams will consistently come up as unable to archive since the node the stream was allocated, but these errors are uninformative. They come up repeatedly because we retry stuff to self-heal the corrupted streams list, so let's just ignore this error type altogether.
=> Reduce the largish log volume for a small set of corrupt streams we've deemed not worthy of repair

.github/workflows/ci.yml, packages/sdk/src/tests/multi/sync-agent/timeline.test.ts
It can be flaky if it runs too fast, all the events end up in the same bock.
Force snapshots so that when alice calls get stream she is only returned the last few events.
=> skip the sdk timeline scrollback test

packages/sdk/src/client.ts
So it doesn’t get confused with a product feature for nicknames
=> Rename userNickname to logId

core/node/notifications/sync/streams_tracker.go
See @bas-vk 's comment [here](https://github.com/river-build/river/pull/2140#pullrequestreview-2572667064)
=> Reduce log noise for NS by downgrading logs for the known corrupt streams

packages/sdk/src/memberMetadata_Usernames.ts
I think we still need throttling here, but now that the new encryption is in I want to clear the way for new spaces to scale up.
fixes TOWNS-17886
=> Remove the limit on number of usernames decrypted in one go

core/node/storage/pg_notification_store.go, core/node/storage/pg_stream_store.go
As part of investigating the pg code for archiver go test flakes, I noticed and fixed the following:
- whenever we iterate over a result set using `rows.Next()` and `rows.Next()` returns false, according to the pgx documentation we are supposed to check for an error on `rows.Err()` before assuming we correctly ran through the entire result set, but we weren't doing this in several places. So, I swapped the file's predominant row iteration pattern with a pattern that uses the `pgx.ForEachRow` function, which automatically closes the result set stream and checks for errors during and after row scans.
- In some places in the code we were checking to see if `err == context.Canceled` or `err == pgx.*`  instead of checking it's unwrap tree with `errors.Is` - this was unlikely to produce error …
=> [BUGFIX] Error handling fixes in pg stream store, notifications store

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/mls/queue/queueService.ts, packages/sdk/src/syncedStreamsExtension.ts, packages/sdk/src/syncedStreamsLoop.ts
set timeout to push to next frame and allow previous run to get garabage collected
prevents memory leaks
=> Prevent ultradeep callstacks on decription extensions tick

packages/xchain-monitor/src/index.ts, packages/xchain-monitor/src/xchain.ts
Also, limit local block cache size to help prevent container OOMs.
=> Add start message to xchain monitor service

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/client.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/persistenceStore.ts, packages/sdk/src/streamUtils.ts, packages/sdk/src/syncedStream.ts, packages/sdk/src/syncedStreams.ts, packages/sdk/src/syncedStreamsExtension.ts, packages/sdk/src/syncedStreamsLoop.ts, packages/sdk/src/tests/multi_ne/syncedStreams.test.ts
keeps us from getting the “buffer full” messages
=> Update synced streams loop to “modify stream” and add a few streams at a time

core/node/rpc/archiver_test.go
We're seeing occasional TestArchiveContinuous failures that appear to occur because the test timeout is just a hair too tight for the test to complete, for example we see 9/10 miniblocks on a stream in 10 seconds. This PR increases the timeouts for a check that consistently causes failures, and another check in the same test, to hopefully reduce archiver test flakes.
=> Update archiver continuous test timeouts to be more forgiving

core/node/events/notifications_stream_tracker.go, core/node/rpc/tester_test.go, core/node/testutils/dbtestutils/db.go
This is a low priority bugfix of test case cleanup. Sometimes schemas were not being deleted because the context used for schema deletion would be cancelled since it was derived from a context created for the lifetime of a particular test object, and that object was cleaned up before the schema was deleted. For simplicity of reasoning, I swapped the argument ctx with context.Background() and added a panic to ensure that schemas are always properly deleted.
=> [BUGFIX] - Fix test schema cleanup and enforce proper cleanup by test writers

core/cmd/is_entitled_cmd.go, core/cmd/list_channels.go, core/contracts/types/channel_data.go, core/node/auth/space_contract.go, core/node/auth/space_contract_v3.go
Usage: 
```
./env/omega/run.sh is-entitled channel 107ce9312cf40ce89426e8262de3f6701b0e27d8220000000000000000000000 207ce9312cf40ce89426e8262de3f6701b0e27d822f2e4b86c478928c2742315 0xeb59fF9fF1384eC05f3dFBee403d6640635d19bb --config ~/Desktop/omega-alchemy-config.yaml
ld: warning: ignoring duplicate libraries: '-ldl', '-lmls_lib'
{"level":"INFO","timestamp":"2025-02-04T12:20:39.626-0800","function":"github.com/river-build/river/core/node/crypto.(*onChainConfiguration).processRawSettings","msg":"OnChainConfig: applied","settings":{"FromBlockNumber":0,"MediaMaxChunkCount":50,"MediaMaxChunkSize":500000,"RecencyConstraintsAge":11000000000,"RecencyConstraintsGen":5,"ReplicationFactor":1,"MinSnapshotEvents":{"Default":100,"UserInbox":10,"UserSettings":10,"User":10,"UserDevice":10},"StreamMiniblo …
```
=> Implement CLI entitlement evaluation for read (join) permission on channels

packages/encryption/package.json, packages/encryption/src/groupDecryption.ts, packages/encryption/src/hybridGroupDecryption.ts, yarn.lock
loading them from index db every time is slow, especially now that we just use the same key over and over
=> Add lru cache to keep session keys in memory

core/node/auth/auth_impl.go
Shillr is gated by a role with a rule data that has 43 token's OR'ed together, and calls to AddEvent for membership events to add members to channels were sometimes timing out on the node. Investigation showed that these timeouts often occur 5-6s into an AddEvent call, and that the chain_auth limits the duration of the segment of code that makes contracts queries in order to evaluate an entitlement to a maximum of 5s by default. Furthermore, I wrote a CLI tool to test evaluating channel entitlements locally and I see that this Shillr channel's role entitlements can sometimes can take >5s to evaluate.
=> [BUGFIX] Double auth_impl entitlements timeout

core/cmd/is_entitled_cmd.go, core/node/rpc/server.go, core/xchain/entitlement/client_pool.go, core/xchain/entitlement/entitlement_test.go, core/xchain/entitlement/evaluator.go, core/xchain/server/server.go
Clients created by the client pool used by the entitlement evaluator were not reporting metrics. This PR wraps those clients so that metrics and, optionally, tracing can be measured on the clients used by the entitlements module.
=> [BUGFIX] Fix lack of metrics for entitlement evaluations

packages/sdk/src/memberMetadata_Usernames.ts, packages/sdk/src/tests/multi_ne/client.test.ts
dear god
i broke this here: https://github.com/river-build/river/commit/07f33f01abd1fe590d742bf9269f808c279d7905, oops
=> Fix bug that was causing us to re-decrypt all usernames and clogging the queue

contracts/package.json, contracts/scripts/common/DeployHelpers.s.sol, contracts/src/diamond/facets/token/ERC20/permit/ERC20PermitBase.sol, yarn.lock
Upgraded key dependencies such as OpenZeppelin, Solady, and @river-build/diamond for improved features and compatibility. Fixed `_approve` method usage in `ERC20PermitBase` and added `view` modifier to the `exists` function in `DeployHelpers`. These changes ensure better consistency and compliance with updated standards.
=> chore(contract): update OpenZeppelin, Solady and diamond contracts

packages/sdk/src/tests/multi_ne/client.test.ts
the pattern is waitFor(():void => expect(...)), not waitFor(():bool => {}
so the wait for is always immediately returning the result
=> Fix rogue waitFor’s in client.test.ts

core/node/rpc/repl_multiclient_test.go, packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/clientDecryptionExtensions.ts
if lots of keys have come in in the meantime we will not download them until the user refreshes the page. If a key comes in via sync, we would reset the indexes in the stream and never download them.
This is probably the long standing bug where some random message doesn’t sync randomly.
=> Cover edge case where we lose sync and recover and re-initialize the user inbox stream

packages/sdk/src/mls/utils/mlsutils.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/sync-agent/timeline/models/timeline-types.ts, packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts, packages/sdk/src/tests/multi_ne/client.test.ts, packages/sdk/src/tests/multi_ne/mls/mls.test.ts, packages/sdk/src/tests/multi_ne/space.test.ts, packages/stream-metadata/tests/integration/spaceImage.test.ts
we could probably do this with even more events, just this cuts our memory usage in half on my machine running locally
=> Stop saving miniblock headers in the timeline

packages/sdk/src/mls/utils/mlsutils.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/sync-agent/timeline/models/timeline-types.ts, packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts, packages/sdk/src/syncedStreamsExtension.ts, packages/sdk/src/tests/multi_ne/client.test.ts, packages/sdk/src/tests/multi_ne/mls/mls.test.ts, packages/sdk/src/tests/multi_ne/space.test.ts, packages/sdk/src/tests/multi_ne/syncedStream.test.ts, packages/stream-metadata/tests/integration/spaceImage.test.ts
basically hand rolls the concurrent thing but this actually allows us to update the page. 5 at a time is still pushing it, but 1 is way too slow.
=> Better queueing algo for synced streams

packages/stress/src/start.ts
why does pino have to be like this?
=> Fix error log order on stress test

contracts/scripts/deployments/utils/DeployTownsMainnet.s.sol
we run both multi and multi_ne environments locally, this causes both to be deployed at the same address which doesn’t work
=> Remove salt in towns mainnet deployer to fix local dev

packages/sdk/src/streamStateView.ts
I need the signatures, i accidentally left in the whole event, which doubles our memory usage in browser.
=> Fix bug in stream state view holding on to unnecessary memory

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/syncedStream.ts, packages/sdk/src/syncedStreamsLoop.ts
Firgured out that in local stress tests at least we get into a local ddos situation when you’re not syncing but you’re still processing key requests, you start spamming the node with fulfillments for keys that have already been fulfilled and it all goes pear shaped.
This code sets these streams as not up to date and clears the up to date list in the encryption loop, which will prevent them from processing until they receive another update.
=> Stop decryption when sync errors out

packages/sdk/src/syncedStreamsLoop.ts
=> If modify sync fails and we’re still syncing with the same syncid, re-add streams to sync

.github/workflows/Publish_npm_packages.yml, scripts/publish-to-npm.sh
Now that npm publish CI job is fixed, revert back to just allowing it to run on `main`.
=> NPM ci fix final

packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/tests/decryptionExtensions.test.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/streamStateView_UserInbox.ts
This only really became a problem when blocks weren’t getting created, but tbh i put this in thinking it would protect the user from bad events, but we have nothing on the node that re-checks the event after sending it to the user before confirming it anyway so this was just dead time
also i think i was passing the wrong emitter so it’s possible we were missing a few of these events during initialization, which is news to me
and we used to have custom code to retry events that had pending sessions and that code has been deleted, so this is probably a good change all around.
=> Remove artifical delay before processing keys in user inbox

core/node/rules/can_add_event.go, packages/sdk/src/tests/multi_ne/client.test.ts
Sadly some clients are requesting empty session ids over and over (tracked general down to caroline’s client)
Need to track down the actual cause, this will prevent the streams from blowing up.
=> Block clients from uploading key solicitations with empty session ids

core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_ephemeral.go
1) Restructure code to always use defer for unlock.
2) Do not call Scrub multiple times in the same time period.
3) Do not call Scrub under lock.
4) Remove unnecessary lock on putting stream in a map.
=> Refactor GetView & so on

contracts/scripts/interactions/InteractAlphaSparse.s.sol
I added try..catch blocks and caught the error we were seeing in [CI](https://github.com/HereNotThere/harmony/actions/runs/13295919423/job/37127735707) with more context. The script through out of gas evm error when deploying the spaceOwner contract helper. Pausing gas metering around the helper contract deployments in the constructor allowed me to run the InteractAlphaSparse script locally without any error.
=> pause gas metering for helper contract deployment to prevent oog errors

packages/encryption/src/decryptionExtensions.ts
I have seen solicitations in the streams with [“”] and I don’t think this is the cause, but it should prevent it. I have added a check in the node to block it.
=> Add an error if the sessionId is 0 so that we don’t attempt to push a key solicitation for it

packages/sdk/src/client.ts, packages/sdk/src/sync-agent/river-connection/models/transactionalClient.ts, packages/sdk/src/sync-agent/river-connection/riverConnection.ts, packages/sdk/src/sync-agent/syncAgent.ts, packages/sdk/src/syncedStreamsExtension.ts, packages/stress/src/utils/stressClient.ts
somewhere in here the stress clients are dying or hanging without any errors
push the log ids into the client to get better reporting and filtering capabilities
=> More logs for stress

core/node/rpc/sync/client/syncer_set.go, core/node/rpc/sync/operation.go, core/node/rpc/sync_test.go
When the client initiates a sync session it passes a set of sync cookies that it wants to get updates for. Currently these updates are send to an internal channel and when all streams are internally added the node starts sending these updates to the client. If there are more updates available than the capacity of the channel it ends up in buffer too full and the sync session is cancelled.
This change starts adding the streams to sync and immediately starts sending updates to the client. This should not yield to a buffer full as long as the client can keep up.
As a side effect the time it takes for a client to receive the first update is decreased because the node starts sending them immediately.
There is a unittest that hit the buffer too full problem reliable with the old implementation …
=> node/sync: add initial stream to sync session one by one

packages/sdk/src/sync-agent/river-connection/models/riverChain.ts, packages/sdk/src/sync-agent/river-connection/riverConnection.ts, packages/sdk/src/sync-agent/syncAgent.ts
saw an interesting error in the logs
Error: Timeout waiting for condition
at RiverChain2.when (/monorepo/packages/sdk/src/observable/observable.ts:48:30)
at RiverChain2.urls (/monorepo/packages/sdk/src/sync-agent/river-connection/models/riverChain.ts:50:20)
at RiverConnection2.start (/monorepo/packages/sdk/src/sync-agent/river-connection/riverConnection.ts:86:29)
at SyncAgent.start (/monorepo/packages/sdk/src/sync-agent/syncAgent.ts:123:36)
at async makeStressClient (/monorepo/packages/stress/src/utils/stressClient.ts:88:5)
at async Promise.all (index 9)
at async startStressChat (/monorepo/packages/stress/src/mode/chat/root_chat.ts:33:21)
at async run (/monorepo/packages/stress/src/start.ts:46:13)
=> more logs for the stress tests

contracts/test/spaces/review/ReviewFacet.t.sol
Add additional assumptions to ensure the `user` is neither the founder nor holds membership tokens. This enhances test robustness by better isolating the non-member scenario.
=> test(contract): strengthen non-member check in addReview test

packages/dlog/src/dlog.ts
matches the api of the dlog
not sure why you don’t just pass this as the ns, but allows for easy composability i guess.
=> Add “extend” to the combined dlogger

contracts/deployments/gamma/base/addresses/reviewFacet.json, contracts/makefile
Add the deployment address for reviewFacet and update the Makefile to include additional deployment flags, such as verifier URL and Etherscan API key. This ensures smoother deployment processes with enhanced verification capabilities.
=> deploy(contract): add reviewFacet deployment address and fix makefile

contracts/deployments/gamma/base/addresses/rewardsDistributionV2Facet.json, contracts/deployments/omega/base/addresses/rewardsDistributionV2Facet.json, contracts/scripts/deployments/facets/DeployRewardsDistributionV2.s.sol, contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistribution.sol, contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol
This introduces a new function `permitAndIncreaseStake` that allows users to stake with EIP-2612 permits and increase the stake of existing deposits. It refactors related logic into reusable internal functions `_permitStakeToken` and `_increaseStake` for better maintainability. Comprehensive tests have been added to ensure correct behavior.
=> feat(contract): add `permitAndIncreaseStake` function

packages/sdk/src/tests/multi/transactions_Tip.test.ts, packages/sdk/src/tests/testUtils.ts
I want to be able to extract data from this function, wondering if this has any side effects
=> Update the test util “waitFor” to be more explicit about return types

packages/sdk/src/streamUtils.ts
this was a bad idea, i need to flip these to explicitly leave out stuff, or explicitly decide on every event
=> Update the persisted event switches for new member events that we should preserve

contracts/test/airdrop/DropFacet.t.sol, contracts/test/base/registry/RewardsDistributionV2.t.sol, contracts/test/spaces/BaseSetup.sol
EIP712Utils was removed from unnecessary test files and added only to `BaseSetup` to centralize its usage. This reduces redundancy and simplifies contract inheritance structures for better maintainability.
=> test(contract): refactor `EIP712Utils` usage across test contracts

packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/tests/decryptionExtensions.test.ts, packages/sdk/src/client.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/streamEvents.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/streamStateView_Members.ts, packages/sdk/src/streamStateView_Members_Solicitations.ts, packages/sdk/src/types.ts
approx half of our events are miniblock headers
i stopped saving them and saved a whole bunch of memory, but it broke signature validation
https://github.com/towns-protocol/towns/pull/2290
this fixes signature validation to pass the required info along with the solicitation, instead of programming a loopdyloop where we go back into the view for it.
much better imo
=> Reduce memory by not saving miniblock signatures in memory

core/node/events/miniblock_producer.go
When stream details can't be fetched from the smart contract the error handling logs the issue and continue the flow that uses the uninitialised returned value which results in a nil panic.
=> node/repl: correct error handling on MB candidate promotion

packages/sdk/src/client.ts, packages/sdk/src/syncedStreams.ts, packages/sdk/src/syncedStreamsLoop.ts
Kinda Reverts https://github.com/towns-protocol/towns/commit/135ee8e77eff77ce38b2ae31ed35ad7d35ebc87f (there were subsequent changes to logging)
=> Add option to enable Modify Sync

protocol/payloads.proto
=> Update attachment static info to allow ens name

packages/stream-metadata/src/node.ts, packages/stream-metadata/src/routes/spaceMemberMetadata.ts
We're getting overflows
example error: https://app.datadoghq.com/logs?query=status:error%20service:stream-metadata&agg_m=count&agg_m_source=base&agg_q=service,env&agg_q_source=base,base&agg_t=count&clustering_pattern_field_path=message&cols=service&event=AwAAAZVajzZftyDhDAAAABhBWlZhanp2TkFBQWJBdEtmcG5id0lnQVIAAAA1MDE5NTVhZjItNzI2Zi00NjQ3LTlmY2UtNjgyMGRkMzJlNjEwLXN5bnRoZXRpYy1saXN0LTAAAdCO&fromUser=false&messageDisplay=inline&sort_m=,&sort_m_source=,&sort_t=,&storage=hot&stream_sort=desc&top_n=10,10&top_o=top,top&viz=pattern&x_missing=true,true&from_ts=1739817261843&start=1741023442604&end=1741027042604&to_ts=1741026861843&live=true&paused=false
log: Failed to fetch space contract info
```
code | NUMERIC_FAULT
-- | --
fault | overflow
message | overflow [ See: …
```
=> Fix big number error when fetching token member metadata

packages/sdk/src/streamStateView_Members.ts, packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts, packages/sdk/src/tests/multi/transactions_SpaceReview.test.ts, packages/web3/src/v3/IReviewShim.ts
The added/updated/deleted event is not the only event
for smart wallets receipt.from !== senderAddress
=> Fix for reivew receipt parsing in IReviewShim, pass proper sender address

packages/docs/towns-token/delegation.mdx
Hi! I fixes a dead link in the delegation.mdx file. The original link pointing to Optimism's documentation for the L1CrossDomainMessenger contract was outdated and has been updated to the correct URL.
=> docs: fix dead link in `packages/docs/towns-token/delegation.mdx`

contracts/src/utils/StringSet.sol, contracts/test/utils/StringSet.t.sol
- Add unit tests for `StringSet` library
- Refactor `StringSet` to use assembly for index management
- Refactor `StringSet` to use `Uint256Ref` for cleaner indexing
- Refactor `StringSet` to optimize array length handling
- Refactor `StringSet` to remove private helper functions
- Add `clear` function to `StringSet` and refactor tests
- Add `_delete` function to handle string deletion in storage
- Fix storage clearing logic in `StringSet` delete operation
- Refactor `add` and `remove` functions to use named returns
=> perf(contract): refactor `StringSet` and add tests

contracts/package.json
The `account-abstraction` package was relocated from dependencies to devDependencies, likely reflecting its use only in development or testing. This change optimizes the dependency structure and ensures the production build remains minimal.
=> chore(contract): move `account-abstraction` to `devDependencies`

core/node/rpc/app_registry_test.go, core/node/rpc/media_stream_test.go, core/node/rpc/node2node_ephemeral_test.go, core/node/rpc/node2node_test.go, core/node/rpc/repl_mc_norace_test.go, core/node/rpc/repl_multiclient_test.go, core/node/rpc/service_test.go, core/node/rpc/stream_test.go, core/node/rpc/tester_test.go
With this change each time when test clients are instantiated a stream sync session is started. When `testClients#createChannelAndJoin` is called all clients will subscribe for updates on the created stream though modify sync. When the test calls `testClients#compare(StreamId)` not only the stream are compared between clients but also ensured that all clients received the same updates through the sync session.
=> repltest: ensure sync works in replicated scenario testing

packages/web3/src/chain.ts
Define configurations for Towns Mainnet and Testnet, including chain IDs, RPC URLs, block explorers, and multicall contract details. These additions enable interaction with both networks in the application.
=> feat(web3): add Viem config for Towns Mainnet and Testnet chains

contracts/scripts/interactions/InteractRiverAlpha.s.sol
Now all facets are redeployed when running InteractRiverAlpha which is the desired behavior.
https://testnet.explorer.towns.com/address/0x44354786EacBEBf981453A05728E1653Bc3c5def?tab=read_contract
=> Set deployment override for InteractRiverAlpha

core/node/events/stream.go
seems like best practice is that we shouldn’t be panicing the nodes if we can avoid it.
=> Remove runtime panic from sync subscription

packages/sdk/src/syncedStreamsLoop.ts
seems like this is all we need to do…
though we might want to detect when we’re getting updates for streams we’re not subscribed to and call modify sync again here:
```
if (streamRecord === undefined) {
this.log('sync got stream', streamId, 'NOT FOUND')
}
```
=> Switch removeStreamFromSync to use the modifySync call

core/node/auth/auth_impl.go
We cannot test the delegate wallets feature fully locally because we rely on delegate contracts deployed to sepolia. There is probably a more hermetic solution, but this is the fastest way to get to the bottom of this that I can figure out.
The token seems to be minted, but joining the space is failing, and it's the IsSpaceMember chain auth kind that's failing. I'd like to get to the bottom of why.
=> Add logs to alpha in order to debug the entitlement failures for delegated wallets

contracts/src/utils/StringSet.sol, contracts/test/utils/StringSet.t.sol
Replaced raw storage references with `StringWrapper` to improve clarity and safety in string operations. Refactored key contract methods to utilize the new abstraction, reducing direct assembly usage. Simplified tests by eliminating mock contracts and directly leveraging `StringSet.Set`.
=> refactor(contract): use `StringWrapper` and reduce assembly

contracts/test/crosschain/EntitlementGated.t.sol, contracts/test/fork/ForkProxyBatchDelegation.t.sol, contracts/test/spaces/membership/unit/MembershipJoinSpace.t.sol, contracts/test/utils/EntitlementTestUtils.sol, contracts/test/utils/LogUtils.sol
Add `LogUtils` as a reusable utility for log matching to simplify and optimize log-related operations. Refactor `EntitlementTestUtils` and associated tests to utilize `LogUtils`, reducing repetitive code and enhancing readability. Reorganize contract inheritance and refine test assertions for better maintainability and efficiency.
=> test(contract): improve log handling with `LogUtils` utility

core/node/storage/pg_app_registry_store_test.go
I discussed with Grok this morning, and it seems likely that the deadlock coming up in CI is due to unit tests overlapping within the same schema.
In particular you can look at the database logs in the go tests for [this run](https://github.com/towns-protocol/towns/actions/runs/13850076345) and you'll find only one deadlock record in the pg logs:
```
2025-03-14 04:50:35.964 UTC [998] ERROR:  deadlock detected
2025-03-14 04:50:35.964 UTC [998] DETAIL:  Process 998 waits for RowExclusiveLock on relation 41612 of database 16384; blocked by process 1002.
Process 1002 waits for AccessExclusiveLock on relation 41600 of database 16384; blocked by process 998.
Process 998:    INSERT INTO app_session_keys (device_key, stream_id, session_ids, ciphertexts)
VALUES ( 'deviceKey0' , …
```
=> Disabling flaky tests to unblock PR merging

packages/sdk/src/persistenceStore.ts
this thing only retrys clear texts… not sure why it’s there, history is lost. add log to see if it is happening.
=> Add a warn to the persistence store retrier

packages/sdk/src/persistenceStore.ts, packages/sdk/src/sign.ts
these are used in the `initializeFromResponse` function in syncedStream.ts
the result of this would be that usernames and dispaly names wouldn’t decrypt imediately, they’d be pushed in the decryption queue. They items would not be decrypted a second time, it would hit the cache again before trying to decrypt, but still this clogs the queue and slows everything down.
=> pull eventIds from snapshot when parsing sync reset

core/node/storage/pg_app_registry_store_test.go
I ran these tests 100x in CI and was unable to reproduce the deadlock error, so I'm re-enabling them.
=> Re-enable pg store tests for app registry

contracts/scripts/common/DeployBase.s.sol
This allows the versionName to have a subfolder for example `facets/tippingFacet` which will save the address in the facets subfolder
=> allow subfolders for version names

packages/sdk/src/persistenceStore.ts, packages/sdk/src/streamUtils.ts
this doesn’t go as far as i’d like it, but it takes the memory footprint way down and should help temporarily until i can get my major refactors in.
reasoning: users will have to re-download all miniblocks. All but the most recent will not store snapshots, which will take less space
test plan: tested in harmony running against omega. seemed fine.
=> Reduce indexdb memory footprint

packages/encryption/src/decryptionExtensions.ts, packages/encryption/src/tests/decryptionExtensions.test.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/streamEvents.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/streamStateView_Members.ts, packages/sdk/src/streamStateView_Members_Solicitations.ts
and simplify the function signatures
we were passing the sig bundle of the last person who fulfilled a solicitation instead of the miniblock header, this was wrong and would cause lots of extra checks
remove the unused eventid param
Trying to simplify things to make a bigger refactor of the stream state view
=> Fix for wrong sigBundle update on fulfillment

core/contracts/river/stream_registry_v1_ex.go, core/node/events/miniblock.go, core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_ephemeral.go, core/node/nodes/stream_nodes.go, core/node/registries/river_registry_contract.go, core/node/registries/river_registry_contract_test.go, core/node/rpc/archiver.go, core/node/rpc/stream_test.go, core/node/track_streams/streams_tracker.go
Switches the node over to use the new StreamUpdated event that was introduced in https://github.com/towns-protocol/towns/pull/2578
The StreamUpdated event is a tuple of the type of event it represents and abi.encoded data. The node decodes this data based on the event type. For stream miniblock updates this is an slice of updates (batch) but abi decoding in the node currently fails. A workaround is used that json marshals the decoded input and marshals it back it which works. This workaround is a todo that needs to be fixed.
=> node: move node to unified eventing model

contracts/package.json, contracts/test/base/registry/RewardsDistributionV2.t.sol, contracts/test/spaces/BaseSetup.sol, yarn.lock
Moved contract initializations into the `setUp` function to ensure proper configuration before each test. This improves test reliability and reduces redundancy by centralizing setup logic. Additionally, updated dependencies in `package.json` and `yarn.lock` for compatibility.
=> test(contract): initialize deployment contracts in `setUp` function

contracts/.env.example, contracts/.env.localhost
Added new RPC URL entries and updated RIVERSCAN URLs in both `.env.example` and `.env.localhost`. This ensures consistency and provides better support for different environments. Removed unused `RIVERSCAN_API_KEY` for cleanup.
=> chore(contract): update RPC and explorer URLs in .env example

packages/metrics-discovery/.eslintrc.json
We dont have tests on metrics-discovery package, and we're not using jest anymore. 
Removing it from eslint rules to fix CI
=> remove jest from eslint rules in metrics discovery package

core/node/events/stream_view.go
the sync resets are expected. the space stream updates so much that people checking in once a day will have an out of date cookie for large space.
=> Downgrade GetStreamSince warning to debug

core/node/storage/pg_metrics.go
Uniquely generated random node ids for tests sometimes contain hyphens, and these node ids are used to compose schema names for the database. If the schema name contains a hyphen, then the schema must be quoted in double quotes wherever  it's referenced directly in queries.
This change updates the statistics calculation function to quote the schema in double quotes everywhere it occurs.
=> Add quotes around schema name for stats query function

packages/sdk/src/tests/multi_ne/streamRpcClientGetSince.test.ts
Not sure when this started happening, but it makes sense that we can have a new block header here 
Example failure: https://github.com/towns-protocol/towns/actions/runs/14257837404/job/39963612469?pr=2740
=> Fix Flaky streamRpcClientGetSince test

packages/encryption/src/decryptionExtensions.ts
when multiple people attempt to send the same key fulfillment it can return a NOT_FOUND error
=> Update solicitation error message to exclude expeted case

contracts/src/river/registry/facets/stream/StreamRegistry.sol, contracts/src/river/registry/libraries/RegistryStorage.sol
Replaced repetitive node-iteration logic with `_addStreamIdToNodes` and `_removeStreamIdFromNodes` utility functions to improve code reuse and readability. Additionally, deprecated an unused storage slot by introducing `deprecatedSlot` as a placeholder in `RegistryStorage.sol`.
=> refactor(contract): shift `streamIdsByNode` by one slot

scripts/yarn-clean.sh
Updated the yarn-clean script to retain the .idea directory during cleaning. This change prevents accidental deletion of IDE files, enhancing convenience for developers using IntelliJ-based tools.
=> chore: exclude .idea directory in git clean

packages/stress/esbuild.config.mjs, packages/stress/package.json, packages/stress/src/demo.ts, packages/stress/src/notifications.ts
This was testing code that lasted for about 6 months without issue.
If we run ci while the notification service is deploying this will fail.
=> Move the notification service call out of the stress test demo

.github/CODEOWNERS
Adjusted the CODEOWNERS file to reflect the updated path for the contracts directory from `/contracts/` to `/packages/contracts/`. This ensures proper code ownership management for the new directory structure.
=> chore: update CODEOWNERS path for contracts directory

core/node/app_registry/event_processor.go, core/node/app_registry/testutil.go, core/node/events/events.go, core/node/rpc/app_registry_test.go
The session_id field is actually deprecated and I just missed that from the doc reading. I believe this should fix the issue and make the service compatible with the client.
=> [BUGFIX] Switch app registry service to reading session id from the session_id_bytes field of channel messages

.github/CODEOWNERS
Moved `/packages/contracts/` entry to prevent unintended overrides. This ensures proper ownership assignments in the CODEOWNERS file.
=> chore: reorder CODEOWNERS entries for correct ownership mapping

scripts/start_dev.sh
The start_dev script broke after contracts were moved. Here is a one-line change that repairs local dev.
=> Update start_dev script to work with contracts under packages.

packages/sdk/src/sync-agent/timeline/timeline.ts
Typo...
Events wasn't getting properly replaced
Previously, if I had edited a message, the `eventId` of message in timeline would change, and that's not the desired behavior.
We would like keep the original eventId, since it can hold reaction references, and only update the `latestEventId` to be the new one from the latest edit
=> fix(sync-agent): timeline event replace

packages/sdk/src/tests/multi/entitlements/channelsWithEntitlements.test.ts, packages/sdk/src/tests/multi/entitlements/spaceWithEntitlements.test.ts, packages/web3/src/EntitlementCache.test.ts, packages/web3/src/EntitlementCache.ts, packages/web3/src/ISpaceDapp.ts, packages/web3/src/Keyable.ts, packages/web3/src/SimpleCache.test.ts, packages/web3/src/SimpleCache.ts, packages/web3/src/v3/SpaceDapp.ts
This PR significantly optimizes the performance of checking and retrieving banned wallet information in `SpaceDapp` by introducing caching and utilizing multicall.
Before this PR, loading AX1 would result in ~1300 rpc calls related to banned wallets. Now, dependent on the user and their linked wallets, it will make a maximum of 10 calls.
Can probably further clean up banning/tokenId logic across this package and consumers in harmony, but this is enough for now imo.
**Key Changes:**
*   **Added Caching:** Implemented `SimpleCache` for:
*   `bannedTokenIds`: Caches the list of banned token IDs for a space.
*   `ownerOfToken`: Caches the owner address for a specific token ID.
*   `isBannedToken`: Caches the banned status of a specific token ID.
*   **Optimized `bannedWalletAddresses`:**
* …
=> web3: Optimize Banned Wallet Checks with Caching and Multicall

core/node/events/stream.go, core/node/events/stream_cache.go
The stream node tracks the streams registry for emitted logs, parses these into events and processes them. Currently it also tries to process miniblock update for non-local streams causing log pollution; `onStreamLastMiniblockUpdated: failed to promote candidate`.
=> don't apply stream mb updates for non-local streams

core/node/events/stream_sync_task.go
For non-replicated streams nodes only register miniblocks periodically to save on transaction costs. That means that the stream update event as emitted during stream (re)placement contains a miniblock number that might not be the latest and the node managing the stream at the moment may have newer miniblocks.
In that case ask the existing quorum node for the latest block and reconcile to that block.
=> node: fetch latest miniblock during reconcile for to-repl-streams migration

packages/sdk/src/streamStateView.ts, packages/sdk/src/streamStateView_AbstractContent.ts, packages/sdk/src/streamStateView_GDMChannel.ts, packages/sdk/src/sync-agent/dms/models/dm.ts, packages/sdk/src/tests/multi/transactions_SpaceReview.test.ts, packages/sdk/src/tests/multi_ne/gdms.test.ts, packages/sdk/src/unauthenticatedClient.ts
Really it’s just GDM metadata.
=> Remove unused channel metadata abstraction

packages/sdk/src/streamStateView_Channel.ts, packages/sdk/src/streamStateView_Common_ChannelMessages.ts, packages/sdk/src/streamStateView_DMChannel.ts, packages/sdk/src/streamStateView_GDMChannel.ts
I want to kill the streamstateview timeline and i’m going to need some place to stash events while they are being decrypted. seems as good a place as any for now
=> Create abstraction for handling encrypted ChannelMessage payloads

packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts, packages/sdk/src/sync-agent/timeline/timeline.ts
I’m going to pull in the harmony one, don’t want any confusion.
=> Rename the “toEvents” function that the sync agent uses

core/node/events/miniblock_producer.go
We want to reduce conflict in the network between multiple nodes assuming they are the leader. The leader is elected based on the local node's perspective of the river chain head, so let's change leaders once every 10 blocks to reduce these conflicts.
=> Change interval size of leadership election

packages/sdk/src/tests/multi_ne/syncedStreams.test.ts
it was using user inbox stream acks to test subscriptions, i don’t want to save them in the timeline any more, just use the listener
=> simplify the syncstreams test

packages/sdk/src/streamStateView_Members.ts, packages/sdk/src/streamStateView_User.ts, packages/sdk/src/tests/multi_ne/trading.test.ts, packages/sdk/src/tests/testUtils.ts
use the view data instead of the raw events in the token tests
i want to stop retaining the raw events
=> simplify some token tests

packages/sdk/src/streamStateView_UserMetadata.ts, packages/sdk/src/tests/multi_ne/client.test.ts
reduce dependency on timeline events
=> Simplify client metadata tests

packages/sdk/src/tests/multi_ne/client.test.ts
check the actual solicitations instead of the raw events
=> simplify client solicitation test

.vscode/settings.json, packages/contracts/package.json, yarn.lock
Upgraded several package dependencies, including OpenZeppelin contracts (to 5.3.0), Towns Protocol Diamond (to 0.4.0), and Solady (to 0.1.14). Removed unused Solidity compiler remappings from `.vscode/settings.json` to simplify configuration.
=> chore(contract): update contract dependencies

core/cmd/registry_cmd.go, core/node/events/stream_cache.go, core/node/registries/river_registry_contract.go
Use `StreamRegistry::getPaginatedStreamsOnNode` instead of `StreamRegistry::getPaginatedStreams` where possible. This will only load streams from the current node instead of iterating over all streams and grab streams on the local node.
=> node: use ForAllStreamsOnNode instead of ForAllStreams

core/go.mod, core/tools/audit_db/README.md, core/tools/audit_db/inspect.go, core/tools/audit_db/river_audit_db.go, core/tools/audit_db/stream_disk_usage.go
Update the audit tool to print a detailed report of stream contents in the database so we can investigate why disk usage seems to be growing exponentially for some operators.
=> Update audit tool to examine stream disk usage

core/node/events/migrations/migrate_snapshot.go, core/node/events/migrations/snapshot_migration_0004.go, core/node/events/migrations/snapshot_migration_0004_test.go, packages/sdk/src/migrations/migrateSnapshot.ts, packages/sdk/src/migrations/snapshotMigration0004.ts, packages/sdk/src/tests/unit/snapshotMigration0004.test.ts
some usernames are just lost. users uploaded their username to the stream but didn’t share any keys.
then everyone requests the same session id to decrypt, but nobody has it, so we just save those requests forever.
this pr detects and flushes out lost username and displaynames.
We’re working on a real fix for this, but in the meantime this cuts the ax1 snapshot size in half.
Snapshot size reduced from 42133234 to 16167148, 24.76 MB saved 409854 sessionIds 85 usernames and 0 display names removed
=> Snapshot migration to flush lost session ids

.vscode/launch.json
We don't want to resume a debugger and get a timeout error. 
That's why this PR changes the tests timeout when debugging.
=> tests: remove timeout when debugging

core/node/events/miniblock_job.go, core/node/events/stream_view.go
This temporarily raises timeout on candidate save operation. From logs it can be seen that candidates timeout to apply.
=> Make write timeout configurable and remove unused snapshot index logic

core/xchain/entitlement/entitlement.go, core/xchain/entitlement/entitlement_test.go
If a nested entitlement contains two on-chain checks and chain unavailability causes rpc requests to lag until the context times out, these could have erroneously come back as a false entitlement result instead of an error result. I think it's very likely this would happen any time a chain or rpc provider is partially unavailable. This PR repairs the error for both AND and OR operators in entitlement trees.
=> Fix potential erroneous false entitlement check result

core/node/registries/river_registry_contract.go
Some of these parsing errors accidentally included objects that are unset. This PR trades the undefined object for the most specific object that was successfully parsed.
=> Fix river registry error tags to contain defined objects for better debugging on stream event parsing failures

packages/sdk/package.json, yarn.lock
SDK only require the types of `@connectrpc/connect-web`.
This should unblock stream-metadata docker image to build
=> fix: add `@connectrpc/connect-web` as dev dependency of sdk

scripts/run-local-ci.sh
- Create `run-local-ci.sh` to facilitate running GitHub Actions locally.
- Support specifying jobs, event types, and configuration options via CLI arguments.
- Automatically generates `event.json` based on event type.
- Provides error summaries for failed steps.
=> feat(scripts): add script to run GitHub CI locally using act

packages/encryption/src/decryptionExtensions.ts
Seems like we were just skipping them? Probably why snapshots got so huge.
=> Fix bug in processing of snapshotted key solicitations

packages/contracts/src/router/ISwapRouter.sol, packages/contracts/src/router/SwapRouter.sol, packages/contracts/test/router/SwapRouter.t.sol, packages/generated/dev/abis/ISwapFacet.abi.json, packages/generated/dev/abis/ISwapFacet.abi.ts, packages/generated/dev/abis/ISwapRouter.abi.json, packages/generated/dev/abis/ISwapRouter.abi.ts, packages/generated/dev/abis/ISwapRouterBase.abi.json, packages/generated/dev/abis/ISwapRouterBase.abi.ts, packages/generated/dev/typings/factories/ISwapFacet__factory.ts, packages/generated/dev/typings/factories/ISwapRouter__factory.ts
Introduce `SwapRouter__UnexpectedETH` error to enforce validation where unexpected ETH is sent with non-native token swaps. Includes updated typings, ABIs, and tests.
=> fix(contract): add `SwapRouter__UnexpectedETH` error handling

packages/contracts/scripts/deployments/diamonds/DeployAppRegistry.s.sol, packages/contracts/scripts/deployments/facets/DeployAttestationRegistry.s.sol, packages/contracts/scripts/deployments/facets/DeployModularAccount.s.sol, packages/contracts/scripts/deployments/facets/DeployModuleRegistry.s.sol, packages/contracts/scripts/deployments/facets/DeploySchemaRegistry.s.sol, packages/contracts/scripts/deployments/utils/DeployMockDiamond.s.sol
Updated import paths for diamond-related dependencies to match the new structure in the towns-protocol package.
- Updated import paths for diamond facet deployments by removing the `.s` extension from several files:
- `DeployDiamondCut.s.sol` → `DeployDiamondCut.sol`
- `DeployDiamondLoupe.s.sol` → `DeployDiamondLoupe.sol`
- `DeployIntrospection.s.sol` → `DeployIntrospection.sol`
- `DeployOwnable.s.sol` → `DeployOwnable.sol`
- `DeployOwnablePending.s.sol` → `DeployOwnablePending.sol`
- Changed the import for `DeployLib` to `LibDeploy` with an updated path:
- `@towns-protocol/diamond/scripts/common/DeployLib.sol` → `@towns-protocol/diamond/src/utils/LibDeploy.sol`
- Updated all references from `DeployLib.deployCode()` to `LibDeploy.deployCode()`
1. Ensure all imports resolve correctly by …
=> fix: update import paths for diamond scripts and LibDeploy

packages/sdk/src/rpcInterceptors.ts
ModifySync was timing out today at 30 seconds
=> Increase rpc timeout to 90 seconds

packages/contracts/src/apps/AppRegistryFacet.sol, packages/contracts/src/apps/IAppRegistry.sol, packages/contracts/src/apps/libraries/AttestationLib.sol, packages/contracts/src/apps/resolvers/SchemaResolver.sol, packages/contracts/src/spaces/facets/account/libraries/ExecutorLib.sol, packages/contracts/src/spaces/facets/account/reference/Executor.sol
- Added comprehensive documentation for all functions
- Refactored `_canCallExtended` into a more efficient `_canCall` function
- Simplified permission checking logic
- Improved naming conventions by renaming `checkSelector` to `_getSelector` and making it private
- Reorganized function order for better readability
- Simplified expiration checking logic
- Fixed a logic issue by moving value subtraction before resolver callbacks
- This ensures proper accounting even if the callback reverts
- Extracted revocation logic into a separate `_revokeAttestation` function
- Improved parameter naming by using `self` for the primary object being operated on
- Fixed parameter order in `_checkRefUID` for consistency
- Removed unused `isValidAttestation` function
- Replaced `ReentrancyGuardTransient` …
=> refactor: updates to executorlib, schemaresolver, and attestationlib

packages/contracts/package.json, yarn.lock
Upgrade the `@towns-protocol/diamond` dependency from version 0.5.1 to 0.5.4 to incorporate the latest improvements and bug fixes.
- Updated `@towns-protocol/diamond` from version 0.5.1 to 0.5.4 in package.json
- Updated corresponding yarn.lock entries to reflect the new version
=> chore: update @towns-protocol/diamond dependency to version 0.5.4 in package.json and yarn.lock

packages/dlog/src/dlog.ts
User report:
Hope you’re all doing great! I’m hitting a snag with the @towns-protocol/dlog package in a fresh Vite + React setup (both the official SDK boilerplate and a manual install). As soon as I import and call the hooks, I get this error in the console:
Uncaught (in promise) TypeError: s.test is not a function
This also breaks features like creating a new space—NFTs mint fine on-chain, but the space itself never loads.
Digging into dlog.js, I see:
for (const s of debug.names) {
if (s.test(ns)) {    // ← s.test is not a function
return true;
}
}
It looks like debug.skips or debug.names contains non-RegExp entries, so s.test doesn’t exist. Since the package only ships its dist folder, I can’t patch it locally.
=> Add instanceof check to prevent s.test is not a function issue

core/cmd/cmd_context.go, core/cmd/registry_cmd.go, core/cmd/stream_cmd.go, core/cmd/stream_util.go, core/node/events/dumpevents/dump_events.go, core/node/events/miniblock_job.go, core/node/events/stream.go, core/node/events/stream_view.go
Plus tooling to inspect streams for duplicate events.
Without this options in rare failure scenarios during node unavailability some events stay in minitpools forever since they are rejected by other nodes because they reference mb which is not in cache anymore and thus they can't complete duplicate check.
=> Allow skipping of duplicate check for addEvent on mb reconciliation

packages/sdk/src/tests/multi/channelScrubbing.test.ts
channelScrubbing.test wasn't testing loss entitlement anything because the final waitFor had no assertion
- added assertion
- changed the joiner to be a member that was not already joined to the space, which kicked off the scrubber
=> fix: channelScrubbing.test.ts

core/config/config.go
Currently the worker pool size for stream reconcile tasks is by default 32. With the number of nodes growing this can put a lot of stress on nodes that process these tasks. This change reduces the default count to 16.
Long term solution is to harden the receiving service and return an error that indicates to the caller to retry it later because the service is too busy to accept additional requests from the caller.
=> node: reduce default worker pool online stream reconcile task size

core/node/app_registry/service.go, core/node/app_registry/testutil.go, core/node/http_client/client.go, core/node/rpc/app_registry.go, core/node/testutils/testcert/testcert.go
Allow unencrypted http2 webhook calls for local testing to enable easier configuration of the bot framework tests.
=> App registry changes to support h2c for local testing

core/contracts/base/membership.go, core/node/auth/auth_impl.go, core/node/auth/auth_impl_cache.go, core/node/auth/space_contract.go, core/node/auth/space_contract_v3.go, packages/sdk/src/tests/multi/entitlements/membershipRenewals.test.ts, packages/sdk/src/tests/testUtils.ts, scripts/gen-river-node-bindings.sh
Entitlement checks determine whether the user's balance for a membership NFT is greater than 0. However, when a token is expired, they will still have a balance (see MembershipRenew.t.sol). Entitlement checks need to change to make sure a wallet contains an unexpired token.
- generates go bindings for MembershipFacet contract
- adds GetMembershipStatus to SpaceContractV3 which returns a MembershipStatus struct
- existing SpaceContract.IsMember updated to use GetMembershipStatus
- Updated checkEntitlement to use GetMembershipStatus. If a wallet has a membership nft that is not expired, or in the special case that they are joining a space (not a member yet), entitlement passes, otherwise it fails.
=> Check membership expiration during entitlement checks

core/node/registries/river_registry_contract.go
Handle `StreamLastMiniblockUpdateFailed` event in `RiverRegistryContract::OnStreamEvent`.
=> node: handle StreamLastMiniblockUpdateFailed event

.github/workflows/ci.yml
We are getting download failures for protoc due to github rate limits, but it may actually no longer be a build dependency for us. If CI passes, it's definitely not a dependency and we can go ahead and merge this removal.
=> Remove CI protoc dependency

core/cmd/cmd_context.go, core/cmd/registry_cmd.go, core/contracts/river/stream_registry_v1_ex.go, core/node/crypto/block_number.go, core/node/events/stream_cache.go, core/node/registries/river_registry_contract.go
`FilterStreamEvents` used to pick up `StreamLastMiniblockUpdateFailed` as well, which lead to parsing failure on a call site.
This PR limits `FilterStreamEvents` only to `StreamUpdated`
Also included: `registry events` command to dump stream events from txs.
=> Fix "Failed to parse stream event" "(13:INTERNAL) Stream event isn't update" error in logs

core/cmd/is_entitled_cmd.go, core/node/auth/auth_impl.go, core/node/auth/auth_impl_cache.go, core/node/auth/auth_impl_cache_test.go, core/node/auth/fake_auth.go, core/node/rpc/add_event.go, core/node/rpc/create_media_stream.go, core/node/rpc/create_stream.go, core/node/rpc/membership_scrub_test.go, core/node/scrub/stream_membership_scrub_task.go
Add stub for Evan to add reason into the result
Reasoning: We want to differentiate between leave membership events which were initiated by the user, by the scrubber when entitlements were lost, and by the scrubber when membership has expired.
=> Refactor isEntitled to return result instead of bool

core/cmd/registry_cmd.go, core/cmd/stream_cmd.go
Add a command line cmd to update stream registry records. The wallet needs to be given the configuration manager permissions.
Example:
```
./env/omega/run.sh registry update-stream <wallet-file> <stream-id> <replication-factor> \
<node-addr1> <node-addr2> <node-addr3>
```
=> node: add registry update-stream command line command

packages/contracts/scripts/deployments/diamonds/DeploySpace.s.sol
Included `AppAccount` in the deployment process by updating the facet helper to recognize it and correcting how its address is retrieved. This ensures proper integration for batch deployments.
=> build(contract): add `AppAccount` to the facet deployment batch

packages/contracts/scripts/deployments/diamonds/DeployAppRegistry.s.sol, packages/contracts/scripts/deployments/diamonds/DeployBaseRegistry.s.sol, packages/contracts/scripts/deployments/diamonds/DeployRiverAirdrop.s.sol, packages/contracts/scripts/deployments/diamonds/DeployRiverMigration.s.sol, packages/contracts/scripts/deployments/diamonds/DeployRiverRegistry.s.sol, packages/contracts/scripts/deployments/diamonds/DeploySpace.s.sol, packages/contracts/scripts/deployments/diamonds/DeploySpaceFactory.s.sol, packages/contracts/scripts/deployments/diamonds/DeploySpaceOwner.s.sol, packages/contracts/scripts/deployments/diamonds/DeploySwapRouter.s.sol, packages/contracts/scripts/deployments/utils/DeployMockNFT.s.sol, packages/contracts/test/factory/wallet-link/WalletLink.t.sol
This pull request includes a series of refactors aimed at simplifying and improving the maintainability of deployment scripts and tests. Redundant imports, dependencies, and logic have been removed or optimized to enhance clarity and efficiency across the codebase.
- Removed unnecessary `DeployBase` import and inheritance in `WalletLink` test suite.
- Simplified facet addition logic in deployment scripts by standardizing on the `makeCut` utility function.
- Refactored handling of `MultiInit` by centralizing its management into `diamondInitParams`.
- Optimized `DeployAppRegistry` contract to batch facet deployment operations and reduce redundancy.
- Eliminated unused `IDiamond` imports and redundant variables to clean up dependencies.
=> build(contract): refactor deployment scripts

packages/contracts/.gitignore, packages/contracts/makefile, packages/contracts/scripts/deployments/utils/DeploySpaceProxyInitializer.s.sol
Added support for additional environment files and enhanced deployment script capabilities with new parameters and a space proxy initializer.
- Added `.env.gamma` and `.env.omega` to `.gitignore`
- Enhanced the `deploy-any` make target with support for `password` and `sender` parameters
- Created a new deployment script `DeploySpaceProxyInitializer.s.sol` for initializing space proxies
=> feat: add SpaceProxyInitializer deployment script and update makefile options

packages/sdk/src/tests/multi/entitlements/membershipRenewals.test.ts, packages/stress/src/mode/chat/joinChat.ts, packages/stress/src/mode/chat/kickoffChat.ts, packages/stress/src/mode/slowchat/joinSlowChat.ts, packages/web3/src/BaseContractShim.ts, packages/web3/src/space-dapp/SpaceDapp.ts, packages/web3/src/space-owner/SpaceOwner.ts, packages/web3/src/space/IMembershipShim.ts, packages/web3/src/space/IMulticallShim.ts, packages/web3/src/space/Space.ts
This PR introduces handling expired memberships in SpaceDapp.
- Added membership renewal functionality via `renewMembership` method
- Replaced `hasSpaceMembership` with more detailed `getMembershipStatus` that includes expiration information
- Enhanced entitlement checks to properly handle expired memberships
- Optimized token ownership queries using multicall for better performance
- Fixed stress test code to use the new membership status API
- Added tests for membership renewal and expiration scenarios
=> Add membership renewal functionality and expiration checks

core/node/events/stream.go, core/node/events/stream_ephemeral.go, core/node/events/stream_sync_task.go, core/node/rpc/stream_replacement_test.go
If stream conciliation fails because non of the remotes could provide all requested miniblocks `err` is `nil` because remotes might be able to return a valid response, just not with all miniblocks.
This error was wrapped in a RiverError but being `nil` resulted in a river error with code unknown. The reconciliation task is rescheduled on particular error codes in which this unknown code is not one of. As a result the stream reconciliation task isn't rescheduled.
=> node: fix improper error handling in stream reconciliation

scripts/yarn-clean.sh
this was completely removing the usefulness of https://github.com/towns-protocol/towns/pull/2972
=> chore: dont clean yarn cache on `yarn clean`

.yarnrc.yml
We got a mismatch on `crypto-lib`, previously it wasn't throwing. 
https://github.com/HereNotThere/harmony/pull/9717
This PR reverts the behavior to the old one until we figure out the `crypto-lib` checksum mismatch
edit: actually, it was on harmony. But for the sake of having everything same, lets change here too.
=> dont throw on yarn checksumBehavior

packages/contracts/src/apps/BaseApp.sol, packages/contracts/src/apps/ITownsApp.sol, packages/contracts/src/apps/examples/SimpleApp.sol, packages/contracts/src/apps/facets/registry/AppRegistryBase.sol, packages/contracts/test/mocks/MockInvalidModule.sol, packages/contracts/test/mocks/MockModule.sol, packages/contracts/test/mocks/MockPlugin.sol, packages/contracts/test/mocks/MockSavingsModule.sol
This PR refactors the Towns app ownership model by replacing the direct IERC173 inheritance with a dedicated `moduleOwner()` function. This approach provides a cleaner separation between module ownership and the Ownable implementation details.
- Removed IERC173 inheritance from ITownsApp interface
- Added new `moduleOwner()` function to ITownsApp interface
- Implemented `moduleOwner()` and `_moduleOwner()` functions in BaseApp
- Created a new SimpleApp example that demonstrates the ownership pattern using Solady's Ownable
- Updated all mock implementations to support the new ownership interface
- Modified AppRegistryBase to use the new moduleOwner() function instead of owner()
=> refactor: replace IERC173 with moduleOwner() in ITownsApp interface

packages/contracts/scripts/interactions/InteractRegisterApp.s.sol, packages/contracts/scripts/interactions/helpers/SimpleApp.sol, scripts/deploy-base-contracts.sh
Added a new interaction script for registering apps with the AppRegistry, and moved the SimpleApp contract to a more appropriate location in the project structure.
- Created a new interaction script `InteractRegisterApp.s.sol` that allows registering apps with the AppRegistry
- Moved `SimpleApp.sol` from `src/apps/examples/` to `scripts/interactions/helpers/` to better reflect its usage
- Updated import paths in SimpleApp to maintain functionality
- Added the app registration step to the base contracts deployment script
=> feat: add InteractRegisterApp script and move SimpleApp to helpers

.coderabbit.yaml
Extend labels list in `.coderabbit.yaml` to include 'area/contracts'.
=> chore: add 'area/contracts' label to `.coderabbit.yaml`

core/node/track_streams/multi_sync_runner.go
This issue was caught by coderabbit in harmony when I merged upstream. I think it may actually be fine since the copy happens only once when the struct is first created, but at best it's still bad form.
=> [BUGFIX] - Fix mutex copy in multi sync runner.

packages/sdk/src/stream.ts, packages/sdk/src/streamUtils.ts, packages/sdk/src/syncedStream.ts, packages/sdk/src/syncedStreamsLoop.ts
Also doing this noticed that we're saving the miniblock header twice, once in the struct, once in the events list
Will try to fix that as well.
=> Save snapshots that come in via push subscription in new format

packages/sdk/src/client.ts
this could actually result in data loss if the keys aren’t processed and we try to load them again, because the events aren’t being persisted when we save a “backwards” block…
=> Miniblock tweak, don’t persist blocks when syncing back on the user inbox

packages/sdk/src/persistenceStore.ts, packages/sdk/src/streamUtils.ts
now that we have snapshots saved separately in the db, don't save these to disc
this includes a db wipe, and starts using the snapshot table in the persistence store.
=> Make sure we don’t save duplicate snapshots to the persistence store

packages/encryption/src/decryptionExtensions.ts, packages/sdk/src/clientDecryptionExtensions.ts
This should be able to go in without affecting needing iOS updates yet
I think it was a mistake to not pass session ids in the initial key solicitations, we end up in a situation where we can ping pong solicitations without actually satisfying the request. The contents of this change
- isNewDevice becomes a suggestion instead of a state
- all key requests now require session ids
- if isNewDevice is true, clients will still send all known sessions, but explicitly state in the fulfillment if they fulfilled any of the requested ids.
this should tighten the reqest loop and prevent at least one back and forth between clients in some cases.
update test
=> Modified handling of isNewDevice

packages/web3/src/space-dapp/SpaceDapp.ts
Upon investigation, I saw that the entitlement cache TTL on the node is actually shorter than other cache ttls, but this is not replicated in the client. This PR updates the client to share the same cache ttls as the node for caches that are common between them.
=> [BUGFIX] - Make TTLs in client cache match the node

packages/contracts/src/diamond/facets/token/ERC5643/ERC5643Base.sol, packages/contracts/test/spaces/membership/unit/MembershipDuration.t.sol, packages/contracts/test/spaces/membership/unit/MembershipRenew.t.sol
The time between an expiration and now could be greater than the membership duration, so if you renewed you'd still be expired.
This PR checks if the the membership has already expired, and sets the new duration from the current time, instead of the previous expiration time.
=> fix: _renewSubscription should handle expired memberships

core/node/app_registry/testutil.go
This should fix some flaky app registry tests I've been seeing. Here is an example: https://github.com/towns-protocol/towns/actions/runs/15200586362/job/42753869981?pr=3152
=> [BUGFIX] - add handling for channel inception events to the test bot server

packages/contracts/src/diamond/facets/token/ERC5643/ERC5643Base.sol, packages/contracts/test/spaces/membership/unit/MembershipDuration.t.sol
Refactored the ERC5643 subscription renewal logic to improve readability and reduce code duplication. 
The changes simplify the conditional flow while maintaining the same functionality.
- Restructured the renewal logic in `_renewSubscription()` to first check renewability for all existing subscriptions
- Simplified the expiration calculation into two clear cases: active subscriptions and new/expired subscriptions
- Removed unnecessary conditional checks and redundant code
- Removed unused console import from the membership duration test file
=> membership renewal cleanup code logic

packages/react-sdk/src/useReactions.ts, packages/sdk/src/sync-agent/timeline/models/reactions.ts, packages/sdk/src/sync-agent/timeline/models/threadStats.ts
to avoid conflicts when moving the timeline into river
=> Rename some sync agent models

packages/sdk/src/sync-agent/syncAgent.ts, packages/sdk/src/tests/multi_ne/space.test.ts, packages/sdk/src/tests/multi_ne/syncedStreams.test.ts
Fixed minor typos in comments and logs across multiple files:
- **syncAgent.ts**
- `thie` → `this`
- **multi_me/space.test.ts**
- `metatdata` → `metadata`
- `metadat` → `metadata`
- **multi_me/syncedStreams.test.ts**
- `othwerwise` → `otherwise`
-
=> fix typos and improve code comments

packages/contracts/src/airdrop/points/TownsPoints.sol, packages/contracts/test/airdrop/TownsPoints.t.sol, packages/contracts/test/spaces/swap/SwapFacet.t.sol
Fixes missing event emissions that are required by ERC20 standard for proper token tracking and integration with external tools.
- Add `Transfer` event emissions to `mint`, `transfer`, `transferFrom`, `batchMintPoints`, and `checkIn` functions
- Add `Approval` event emission to `approve` function
- Update existing tests with `vm.expectEmit` to verify proper event emissions
- Ensure ERC20 standard compliance for points token contract
=> fix(contract): emit missing ERC20 events in `TownsPoints`

packages/sdk/src/tests/multi_ne/streamRpcClientGetSince.test.ts
it assumed that a miniblock would get made faster than it actually was.
with replication this can get slow.
=> Harden the streamRpcClientGetSince test

packages/sdk/src/tests/testUtils.ts
this was asserting that an event ended up in the user stream, but this could be slow now because of replication
=> Harden joining a stream test code

packages/sdk/src/tests/multi/withEntitlements.test.ts, packages/sdk/src/tests/testUtils.ts
to help with flaky tests. kinda surprised this wasn't a problem before
=> Add waitFor around all expected user content membership checks in tests

packages/contracts/scripts/deployments/facets/DeployMainnetDelegation.s.sol, packages/contracts/src/base/registry/facets/mainnet/IMainnetDelegation.sol, packages/contracts/src/base/registry/facets/mainnet/MainnetDelegation.sol, packages/contracts/src/base/registry/facets/mainnet/MainnetDelegationBase.sol, packages/contracts/test/base/registry/MainnetDelegation.t.sol
This pull request introduces new functionality to manage and retrieve mainnet delegators and their associated data in the delegation contract. It also improves test coverage for existing and newly added features. The most important changes include adding a getter for mainnet delegators, updating the `selectors` function to include new methods, and implementing comprehensive tests for delegation-related functionality.
=> feat(contract): add `getMainnetDelegators` function and related tests

packages/sdk/src/tests/multi_ne/syncedStream.test.ts
this was just wrong, wait for was just returning after 10 seconds because these references are never equal
=> Fix equality test in syncedStream.test.ts

packages/stream-metadata/Dockerfile
So stream-metadata build failed to deploy because we're not pushing `node_modules` in the Dockerfile.
I copy pasted the same approach that we're using to `dd-trace`. Adding it into node_modules in the Dockerfile.
We need to mark `@towns-protocol/olm` as external since esbuild doesn't seem to respect the `"node"` export in `@towns-protocol/olm` package.json exports  
I'll try to think and investigate other possible solutions.. Maybe [rolldown](https://rolldown.rs/) respects the `"node"` export?
=> fix: stream metadata dockerbuild

packages/contracts/scripts/deployments/facets/DeployAppAccount.s.sol, packages/contracts/src/spaces/facets/account/AppAccount.sol, packages/contracts/src/spaces/facets/account/AppAccountBase.sol, packages/contracts/src/spaces/facets/account/IAppAccount.sol, packages/contracts/test/spaces/account/AppAccount.t.sol
Added a new `getClients` function to the AppAccount contract to retrieve the list of clients associated with a specific app.
- Added `getClients` function to the `AppAccount` contract that returns all clients for a given app
- Implemented the underlying `_getClients` helper function in `AppAccountBase`
- Added the function selector to the deployment script
- Updated the `IAppAccount` interface with the new function definition
- Added test coverage for the new functionality
=> feat: add getClients function to AppAccount

packages/sdk/src/stream.ts
not needed now that we don’t do weird interfaces
=> cleanup: Update streamId property in stream.ts

packages/subgraph/ponder.schema.ts, packages/subgraph/src/index.ts
This PR updates subgraph schema to avoid hitting PG Range Errors that block sync.
- converts timestamp column type to bigint to avoid PG Range Errors
- update handlers
- createdDate -> blockTimestamp column name for clarity
=> Subgraph: Convert timestamp to bigint, update schema, handlers

core/node/storage/pg_storage.go
Add the number of execution attempts as a tag to the returned error when a postgres transaction fails.
This would be useful for confirming if we're seeing some rare serialization failures in the app registry service because the small tables are causing pg to utilize table scans as an optimization over finding rows by index. If this were the case I would not have expected to see multiple attempts here.
=> Add number of retries to the returned error when a transaction fails.

core/node/events/stream_cache.go, core/node/events/stream_sync_task.go
Add the following prometheus metrics:
```
scheduledGetRecordTasksGauge: params.Metrics.NewGaugeEx(
"stream_cache_recon_scheduled_get_record_tasks",
"Number of recon tasks scheduled to get stream record",
),
scheduledReconciliationTasksGauge: params.Metrics.NewGaugeEx(
"stream_cache_recon_scheduled_recon_tasks",
"Number of recon tasks scheduled",
),
retryableReconcilationTasksGauge: params.Metrics.NewGaugeEx(
"stream_cache_recon_scheduled_recon_retryable_tasks",
"Number of recon tasks scheduled for retry",
),
```
=> node: add prom metrics for recon tasks

core/node/events/snapshot.go
was causing an error on the nodes.
=> Add missing case in snapshot.go

.github/workflows/ci.yml
arc-runner pods keep crashing in GKE with an upstream error fetching from GH backend. This is blocking CI progress. Let's use gh hosted vm's until this issue is fixed. It is likely an issue with GH backend or gh-runner image as nothing else has changed with our deployment which runs a Helm chart for the runner system in GKE.
=> fix ci while arc-runner bug is fixed upstream

core/cmd/is_entitled_cmd.go, core/node/auth/auth_impl.go, core/node/auth/auth_impl_cache_test.go, core/node/events/events.go, core/node/events/snapshot_test.go, core/node/events/stream_view_test.go, core/node/events/stream_viewstate_joinable.go, core/node/rpc/membership_scrub_test.go, core/node/rpc/service_norace_test.go, core/node/rpc/service_test.go, core/node/rpc/tester_test.go, core/node/rules/can_add_event.go, core/node/rules/can_create_stream.go, core/node/scrub/stream_membership_scrub_task.go
Cleanup: Use correct types instead of string or []byte in bunch of APIs
=> Refactor: Change userId to common.Address across codebase 

packages/sdk-crypto/.eslintrc.json, packages/sdk-crypto/README.md, packages/sdk-crypto/package.json, packages/sdk-crypto/src/node/crypto.test.ts, packages/sdk-crypto/src/node/index.ts, packages/sdk-crypto/src/web/crypto.test.ts, packages/sdk-crypto/src/web/index.ts, packages/sdk-crypto/tsconfig.json, packages/sdk-crypto/tsdown.config.ts, packages/sdk-crypto/vitest.config.ts, packages/sdk/package.json, packages/sdk/src/client.ts, packages/sdk/src/index.ts, packages/sdk/src/notificationService.ts, packages/sdk/src/sign.ts, packages/sdk/src/streamStateView_Space.ts, packages/sdk/src/streamStateView_UserMetadata.ts, packages/sdk/src/tests/multi_ne/client.test.ts, packages/sdk/src/tests/multi_ne/media.test.ts, packages/sdk/src/tests/multi_ne/space.test.ts, packages/sdk/src/tests/unit/crypto_utils.test.ts, packages/stream-metadata/package.json, packages/stream-metadata/src/riverStreamRpcClient.ts, packages/stream-metadata/tests/testUtils.ts, packages/stream-metadata/tsconfig.json, packages/tsconfig.base.json, yarn.lock
This allow us to bundle correctly sdk to both browser and web, since we we're using node-only APIs instead of solving if it was node / browser.
Also allow us to be a step closer to remove the `vite-plugin-node-polyfills` from clients. (https://github.com/towns-protocol/towns/pull/3265 is the missing piece)
✅ Requires vitest update to 3.2.1 https://github.com/towns-protocol/towns/pull/3237
=> move sdk crypto functions into a isolated package

packages/rpc-connector/tsdown.config.ts, packages/sdk-crypto/tsdown.config.ts, packages/stream-metadata/Dockerfile
I made the mistake of calling `tsdown` but imporing `tsup` in rpc-connector and sdk-crypto
It was working fine since we had tsup installed in other packages and tsdown is compatible, but on docker, tsup wasn't  installed (since the package that was tsup installed isnt copied in the dockerfile)
Also, I forgot to include the new packages dirs. This PR fixes it
=> fix stream-metadata dockerbuild

package.json, packages/dlog/package.json, packages/encryption/package.json, packages/proto/package.json, packages/rpc-connector/package.json, packages/sdk-crypto/package.json, packages/sdk/package.json, packages/stream-metadata/package.json, packages/stress/package.json, packages/web3/package.json, yarn.lock
So it matches on harmony syncpack check.
=> chore: use `^` in vitest dependency version

packages/contracts/scripts/interactions/InteractMembership.s.sol, packages/contracts/src/spaces/facets/membership/MembershipBase.sol
This PR  fixes a bug in the membership pricing logic to handle cases where the pricing module is not set and adds a new interaction script for the Membership contract
- Modified `MembershipBase.sol` to handle the case where pricing module is address(0)
- Improved the price calculation logic to return the minimum price when no pricing module is set
- Reorganized the code flow in the `_getMembershipPrice` function for better readability
- Removed unnecessary comment in `MembershipBase.sol`
- Added `InteractMembership.s.sol` script to interact with the Membership contract
=> feat: handle zero address pricing module in membership pricing

packages/contracts/deployments/alpha/base/addresses/appRegistry.json, packages/contracts/deployments/gamma/base/addresses/appRegistry.json
Added AppRegistry contract addresses for alpha and gamma environments on Base network.
- Added AppRegistry contract address for alpha environment on Base Sepolia: `0x23a9f5AbBcC82d1E2B5C0781b1F05B623E2c69`
- Added AppRegistry contract address for gamma environment on Base Sepolia: `0xec3081A4b07678C12Fc6B56f69F894EE9e732c42`
=> feat: add app registry addresses for alpha and gamma on base

core/node/auth/space_contract_v3.go
otherwise the scrubber will think you’re expired and kick you out!
=> Return error when failing to get membership expires at on node

core/README.md, core/justfile
When the go tests are run only failed is printed at the end if 1 or more tests fail. Its up to the developer to scroll back and find the failed tests in a big amount of output of all tests. The default go test command doesn't provide any kind of filtering.
This change adds the `test-all-report` just command that runs the go tests and prints a report at the end that contains the tests that fail.
Example output:
```
=== Failed
=== FAIL: node/rpc TestBotConversationNoRace/Large_bot_chat_test (16.23s)
tester_test.go:809:
Error Trace:	/Users/bas/dev/towns/towns/core/node/rpc/tester_test.go:809
/Users/bas/dev/towns/towns/core/node/rpc/tester_test.go:800
/Users/bas/dev/towns/towns/core/node/rpc/tester_test.go:1618
/opt/homebrew/Cellar/go/1.24.2/libexec/src/runtime/asm_arm64.s:1223
Error: …
```
=> go: add test-all-report to run go tests and print a report at the end

core/node/events/events.go, core/node/events/stream_viewstate_space_test.go, core/node/rpc/membership_scrub_test.go, core/node/rpc/service.go, core/node/rules/can_add_event.go, core/node/scrub/stream_membership_scrub_task.go, packages/sdk/src/sync-agent/timeline/models/timeline-types.ts, packages/sdk/src/views/streams/timelineEvents.ts
1. set the node address as the “inviter” which is the initiator in logs for leaves. this differentiates the request from one sent by the user
2. update logs on client to include reason
3. forward reason in to the membership payload to help with debugging
=> Scrubber updates to membership reason

core/node/base/backoff_tracker.go, core/node/base/backoff_tracker_test.go
Several operations need to be retried after it failed. `base#BackoffTracker` provides functionality to retry an operator N times or with a timer backoff that periodically retries the operation until a context expires/cancelled. When the context expires the returned error doesn't contain the given last error that gives context to the operation that must be tried. The result is that the caller can miss valuable error context.
Example:
```
Error leaving stream. AddEvent: (4:DEADLINE_EXCEEDED) 
<<base 0: deadline_exceeded: AddEvent: (4:DEADLINE_EXCEEDED) 
<<base 0: context deadline exceeded
>>base 0 end
nodeAddress = 0xB85dd7d21Bc093DAe6f1b56a20a45ec1770D11dD
nodeUrl = 
handler = AddEvent
elapsed = 5.000850173s
streamId = a8e4a1935907fe134e5cac6de5c877b464e0f1db870000000000000000000000
>>base …
```
=> node: include last error in returned error when context in backoff timer

packages/sdk/src/sync-agent/timeline/timeline.ts
in theory this shouldn’t be a problem, but nothing works like in theory. The compiler doesn’t care because in typescript “every possible string key maps to a Foo,” because we can’t have everything i guess.
=> Add proper defaults to sync agent timeline observables

packages/contracts/scripts/interactions/InteractMembership.s.sol, packages/contracts/src/spaces/facets/membership/MembershipBase.sol
Updated the membership renewal price logic to correctly handle platform fees and minimum prices. This change ensures that renewal prices are compared against the platform fee, while new membership prices are compared against the minimum price requirement.
- Modified `_getMembershipRenewalPrice` to use platform fee for renewal price validation
- Added platform requirements interface integration to properly fetch fee information
- Updated the interaction script to test and verify the new pricing logic
- Added console logging to display price and fee values for debugging
=> fix: update membership renewal price calculation logic

packages/sdk/src/streamStateView.ts
because this is a dictionary record lookup the value can be undefined, but the compiler doesn’t catch it. this could happen if timeline was accessed before initialize(…) is called.
=> Add empty timeline default to stream state view

packages/sdk/src/views/streams/unreadMarkersTransform.ts
I was seeing really odd behavior in my app with unread, it was not displaying unreads properly if decryption was behind.
We originally did it this way before we had the WithRef version of the encrypted channel message
Testing locally this seems much better.
=> Unread tweak - count encrypted non-ref messages as unread

core/node/rpc/add_media_event.go, core/node/rpc/create_media_stream.go, core/node/rpc/create_stream.go
This should help to ensure that more information is propogated back to the caller in the event of an error, so we can debug more effectively from web app error responses. 
- Replace RiverError calls with RiverErrorWithBase when original errors are available
- Fix cases where errors were passed as tags instead of base errors
- Ensure error chains are preserved for better debugging
- Add conditional error handling for cases where errors may or may not exist
Files changed:
- core/node/rpc/create_stream.go: Fix stream ID validation error handling
- core/node/rpc/create_media_stream.go: Fix multiple error handling patterns
- core/node/rpc/add_media_event.go: Fix proto.Unmarshal error handling
This ensures that original errors are not lost and debugging is easier.
=> (Claude) Improve RPC error handling by including base error and tag information

packages/encryption/package.json, packages/eslint-config/typescript.js, packages/sdk/package.json, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/rpcInterceptors.ts, packages/sdk/src/tests/multi/transactions.test.ts, packages/sdk/src/tests/multi/transactions_Tip.test.ts, packages/sdk/src/tests/multi_ne/sign.test.ts, packages/sdk/src/tests/testUtils.ts, packages/sdk/src/views/streams/spaceMentionsTransform.ts, packages/sdk/src/views/streams/timelines.ts, packages/sdk/src/views/streams/timelinesModel.ts, packages/sdk/src/views/transforms/blockedUserIdsTransform.ts, packages/sdk/src/views/transforms/dmsAndGdmsTransform.ts, packages/sdk/src/views/transforms/dmsAndGdmsUnreadIdsTransform.ts, packages/sdk/src/views/transforms/membershipsTransform.ts, packages/sdk/src/views/transforms/spaceIdsTransform.ts, packages/stress/package.json, packages/web3/package.json, yarn.lock
for better tree-shakability + keeping in sync with harmony.
also removed `lodash` dependencies from encryption, stress, and web3 package, which `lodash` was unused.
=> use `lodash-es`

packages/sdk/src/streamStateView.ts, packages/sdk/src/streamStateView_Members.ts, packages/stress/src/utils/stressClient.ts
I’ve seen cases where a user joins a stream and requests keys in the same block. In this case, the key request will be received and enqueued, and possibly processed before the membership is confirmed so the client will fail.
We want the client to continue, and it is safe to continue, because the client responding to key requests will check isEntitled on the blockchain before sending any sensitive key material.
=> Update for key exchange eligibility

packages/playground/package.json, packages/playground/src/components/copy-button.tsx, packages/playground/src/components/dialog/bot-install.tsx, packages/playground/src/components/dialog/bot-settings.tsx, packages/playground/src/components/dialog/create-bot/bot-credentials-dialog.tsx, packages/playground/src/components/dialog/create-bot/index.tsx, packages/playground/src/components/dialog/create-bot/steps/info.tsx, packages/playground/src/components/dialog/create-bot/steps/review.tsx, packages/playground/src/components/dialog/create-bot/steps/type.tsx, packages/playground/src/components/dialog/create-bot/types.ts, packages/playground/src/components/dialog/create-bot/wizard-footer.tsx, packages/playground/src/components/ui/checkbox.tsx, packages/playground/src/components/ui/secret-information-banner.tsx, packages/playground/src/hooks/useAllBots.ts, packages/playground/src/routes/t/dashboard.tsx, packages/playground/src/routes/t/space-channels.tsx, yarn.lock
This PR adds support for creating bots, updating settings and installing them into spaces.
This PR **doesnt** add a bot install page, you can only install bots that you created
- Let me know if its a blocker and I can iterate on this
Useful for testing bot creation on alpha
=> support for bots in playground

packages/sdk/src/persistenceStore.ts, packages/sdk/src/syncedStreamsExtension.ts
I hate this code…
If we don’t have persisted data we try to load it anyway and throw an error which we catch to increment a value which we decrement in a subsequent task that’s enqueued…
This change
1. shortcuts this to prevent the log
2. stops trying to re-look up the sycned stream object after batch looking up the sycned stream object in the persistence store
=> Fix for erroneous error “Unable to load from persistence”

packages/bot/src/bot.test.ts, packages/sdk/src/tests/multi/botEntitlements.test.ts
https://github.com/towns-protocol/towns/actions/runs/15892179484/job/44816609092?pr=3451
I saw it got flaky once. If it happens again we can merge this for now, so we don't block CI with WIP stuff
=> skip flaky bot entitlement test

packages/bot/package.json, packages/bot/src/bot.test.ts, packages/bot/src/bot.ts, packages/examples/bot-ask-poll/package.json, packages/examples/bot-ask-poll/src/index.ts, packages/examples/bot-quickstart/package.json, packages/examples/bot-quickstart/src/index.ts, packages/examples/bot-thread-ai/package.json, packages/examples/bot-thread-ai/src/index.ts, yarn.lock
This enable us to remove the dependency on Hono and move it to a peer dependency.
It also provides more developer freedom and better support for managing the Hono server, allowing to add more middlewares, getting access to Hono `env` (which its useful for deploying bots in cloudflare workers)
I wish I could use `hono/jwt` for the jwt middleware, ran into a few issues, will try again later.
=> bot-framework: don't create `Hono` internally

core/node/events/miniblock_job.go, core/node/events/miniblock_producer.go, core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_ephemeral.go, core/node/events/stream_reconcile_task.go, core/node/events/tracked_stream_view.go, core/node/nodes/stream_nodes.go, core/node/rpc/add_event.go, core/node/rpc/node2node.go, core/node/rpc/stream_replacement_test.go
Renamed all occurrences of "sync" to "reconcile/reconciliation" when referring to node-to-node stream replication to clearly distinguish it from client synchronization (SyncCookie).
Changes:
- Renamed stream_sync_task.go to stream_reconcile_task.go
- Updated method names: SubmitSyncStreamTask → SubmitReconcileStreamTask
- Updated method names: GetQuorumAndSyncNodesAndIsLocal → GetQuorumAndReconcileNodesAndIsLocal
- Updated method names: GetSyncNodes → GetReconcileNodes
- Fixed typo: retryableReconcilationTasks → retryableReconciliationTasks
- Updated field/variable names: syncNodes → reconcileNodes
- Updated comments to use "reconcile" terminology for node-to-node replication
Client synchronization functionality (SyncCookie, SyncResultReceiver, etc.) remains unchanged.
=> refactor: distinguish stream reconciliation from client sync

packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/decryptionExtensions.ts, packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts
instead of a “Stream” queue. This allows us to process them imediately since they are for people who are currently online and much more likely to be relevant.
=> Move the ephemeral events into a “main” queue

packages/docs/run/introduction.mdx
Description
Fixed an incorrect reference in the documentation where "River" was used instead of "Towns" in the introduction page.
=> docs: Fix reference from River to Towns in introduction.mdx

packages/contracts/src/spaces/facets/swap/SwapFacet.sol
Remove redundant refund logic in `SwapFacet.executeSwapWithPermit`.
- Removed balance snapshot and refund handling from `SwapFacet.executeSwapWithPermit`.
- Added clarification that `SwapRouter` already manages refunds for unconsumed input tokens.
=> refactor(contract): remove redundant refund logic in `SwapFacet`

packages/contracts/foundry.toml, packages/contracts/test/base/registry/RewardsVerifier.t.sol, packages/contracts/test/fork/ForkRewardsDistribution.t.sol, packages/contracts/test/fork/ForkStreamRegistry.t.sol
Implement snapshot-based state verification for `ForkRewardsDistribution` tests to handle existing Base mainnet state instead of assuming clean state.
- Added `StateSnapshot` struct to track operator votes, earning power, and staked amounts
- Added `takeSnapshot()` function to capture pre-action state
- Refactored `verifyStake` to use `verifyStakeWithSnapshot` with delta-based assertions
- Updated fork tests to use snapshot verification instead of absolute value checks
- Added snapshot storage mechanisms for test state management
- Fixed operator votes verification to handle existing Base mainnet votes
- Added `totalStaked` state tracking for accurate bounds checking
=> test(contract): implement snapshot-based verification for fork tests

packages/contracts/foundry.toml, packages/contracts/src/spaces/facets/executor/ExecutorBase.sol, packages/contracts/src/spaces/facets/executor/ExecutorStorage.sol
Refactored the executor's execution context tracking to use transient storage instead of persistent storage. This change improves gas efficiency and prevents potential composability issues by ensuring execution context data is properly cleared after each operation.
- Replaced persistent storage for execution IDs with transient storage using `tstore` and `tload` EVM opcodes
- Added new transient storage functions in `ExecutorStorage.sol` to manage execution context
- Updated `_executeOperation` to use transient storage for tracking execution context
- Simplified `_isTargetExecuting` and `_isExecuting` functions to use the new transient storage
- Added `ignored_error_codes = [2394]` to foundry.toml to suppress warnings related to transient storage usage
=> refactor: use transient storage for execution tracking

packages/bot/README.md, packages/examples/bot-quickstart/esbuild.config.mjs, packages/examples/bot-quickstart/package.json, packages/examples/bot-quickstart/src/index.ts, packages/examples/bot-quickstart/tsconfig.json, yarn.lock
This PR introduces an example esbuild configuration for running bots.
I tried running bots with `tsc + node`, but had the following issues:
1. our repo isn't using tsconfig `NodeNext`. 
This means that our import extensions aren't compatible with what Node ESM expects.
```diff
- import foo from './blah'
+ import foo from './blah.js' // even if blah is blah.ts
```
To solve this, we could either:
- add `.js` everywhere in our imports
- bundle packages
2. some of our deps aren't ESM compatible
We've been working on this. 
Below you can check the packages that aren't compatible with ESM.
https://pkg-size.dev/@towns-protocol%2Fsdk
`debug` package and `ethers@5` doesn't support ESM.
We need to move away from them if we want to support `tsc + node`
Moving away can be very time consuming. It's …
=> esbuild example for bots

packages/contracts/deployments/omega/base/addresses/appRegistry.json, packages/contracts/scripts/deployments/diamonds/DeployAppRegistry.s.sol, packages/contracts/test/attest/AppRegistry.t.sol
Simplified the AppRegistry schema by removing unnecessary fields, keeping only the essential app and client address fields. Also added the AppRegistry address for the Base network deployment.
- Simplified the `APP_REGISTRY_SCHEMA` constant in `DeployAppRegistry.s.sol` to only include "address app, address client"
- Updated the corresponding test in `AppRegistry.t.sol` to match the new schema
- Added AppRegistry contract address for Base network in a new JSON file
=> feat: simplify AppRegistry schema and add Base deployment address

packages/bot/src/bot.ts, packages/sdk/src/client-v2.ts
This PR adds support for unpack envelope options in the Bot client.
By default, the validation is turned off.
=> add unpack envelope options for bots

packages/contracts/src/spaces/facets/membership/join/MembershipJoin.sol, packages/contracts/test/spaces/membership/unit/MembershipRenew.t.sol
This PR adds point minting functionality for membership renewals and refactors the existing point minting logic into a reusable internal function to ensure consistent behavior across both new memberships and renewals.
- Extracted point minting logic into a new internal function `_mintMembershipPoints` to avoid code duplication
- Added point minting for membership renewals in the renewal flow
- Added tests to verify points are correctly minted during membership renewals
- Updated existing tests to check point balances after renewal operations
=> refactor: extract membership points minting to reusable function for  joins and renewals

core/node/storage/pg_stream_store.go, core/node/storage/pg_stream_store_preceding_test.go, core/node/storage/storage.go
- Add WritePrecedingMiniblocks interface method to StreamStorage
- Implement function to backfill miniblock gaps during reconciliation
- Validate miniblocks are continuous and precede existing blocks
- Skip overlapping miniblocks (preserve existing data)
- Use bulk insert with CopyFrom for performance
- Add comprehensive test suite with 10 test cases
- Does not update latest_snapshot_miniblock per storage invariants
=> feat: add WritePrecedingMiniblocks for backfilling gaps in storage

core/cmd/registry_cmd.go, core/cmd/stream_cmd.go, core/node/events/miniblock_info.go, core/node/events/snapshot.go, core/node/events/stream.go, core/node/events/stream_view.go, core/node/events/stream_view_test.go, core/node/events/stream_viewstate_space_test.go, core/node/events/tracked_stream_view.go, core/node/protocol/helpers.go, core/node/rpc/get_miniblocks.go, core/node/rpc/miniblocks.go, core/node/scrub/miniblock_scrub_task.go, core/node/track_streams/multi_sync_runner.go, core/tools/migrate_db/river_migrate_db.go
This change is related to #3571 - now GetStream can be used to get preceding miniblocks as well. 
Some refactoring: `snapshot` and `Snapshot` fields are removed/renamed in `MiniblockInfo` to avoid confusion, some checks hardened, `Snapshot` is always set even it's legacy snapshot from the header.
- Remove GetSnapshotByMiniblockIndex method and simplify snapshot retrieval
- Add ApplyOnlyMatchingSnapshot option to MiniblockInfo parsing
- Unify snapshot storage in MiniblockInfo with Snapshot and SnapshotEnvelope fields
- Update all callers to use the new simplified snapshot handling
- Remove IsSnapshot method from MiniblockHeader, use miniblock.Snapshot \!= nil instead
This refactor improves code clarity by consolidating snapshot handling logic and removing unnecessary indirection in …
=> refactor: simplify snapshot handling in miniblocks

packages/contracts/test/airdrop/DropFacet.t.sol, packages/contracts/test/airdrop/scripts/index.mjs
Added an end-to-end test for claiming tokens with a penalty, which verifies the correct token distribution and point deduction when a user claims with a penalty applied.
- Added a new test case `test_e2e_claimWithPenalty()` that validates the penalty-based claiming functionality
- Fixed the path to the airdrop scripts in `givenOffChainRoot()` function
- Added a comment clarifying that PENALTY_BPS represents 50%
- Removed commented-out test code that was no longer needed
- Added console import for debugging purposes
=> feat: add end-to-end test for claiming with penalty

packages/sdk/src/clientDecryptionExtensions.ts
It seems like under certain conditions it's possible for clients to over-solicit using ephemeral solicitations.
I believe adding a check like this in `getKeySolicitations` should fix it.
=> include ephemeral solicitations in getKeySolicitations

packages/contracts/scripts/interactions/InteractDropFacet.s.sol, packages/contracts/src/airdrop/drop/DropBase.sol, packages/contracts/test/airdrop/DropFacet.t.sol
Fixed a potential underflow vulnerability in the `DropBase` contract's loop and added a script to interact with the `DropFacet` contract.
- Fixed a potential underflow vulnerability in the `DropBase` contract by:
- Modifying the loop decrement pattern to use unchecked math
- Adding a break condition to safely exit the loop when reaching the start index
- Added a new interaction script `InteractDropFacet.s.sol` that:
- Creates a test environment for the `DropFacet` contract
- Includes a test case that verifies the proper reversion when no active claim condition exists
=> fix: prevent underflow in claim condition loop

packages/bot/src/bot.test.ts, packages/sdk/src/client-v2.ts, packages/sdk/src/client.ts, packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/decryptionExtensions.ts, packages/sdk/src/tests/multi/botEntitlements.test.ts, packages/sdk/src/tests/multi/channelSpaceSettings.test.ts, packages/sdk/src/tests/multi/sync-agent/syncAgents.test.ts, packages/sdk/src/tests/unit/decryptionExtensions.test.ts
I did this. It was dumb.
1. it hides real errors
2. it doesn’t retry retry-able errors
3. it was dumb, sorry, i will remove it from the node as well
=> Stop using optional in addEvent calls

packages/sdk/src/tests/testUtils.ts
seeing a lot of test failures here
increase timeout and add debugging info
=> Increase timeouts in the wait for memberships in testUtils

core/env/local/multi/on_chain.csv, core/env/local/multi_ne/on_chain.csv, core/node/crypto/config.go
Adds on-chain configuration setting `StreamBackwardsReconciliationThreshold` to control when backwards vs forward reconciliation is used for stream synchronization.
This implements the on-chain setting needed for the backwards reconciliation feature. The threshold determines the reconciliation strategy based on how far behind a stream is:
- If behind by more than the threshold → use backwards reconciliation
- If behind by less than or equal to the threshold → use forward reconciliation
- Added `StreamBackwardsReconciliationThresholdConfigKey` constant
- Added `StreamBackwardsReconciliationThreshold` field to `OnChainSettings` struct
- Set default value to 50 miniblocks
- Updated local environment CSV configuration files
This setting will be used by the stream reconciliation logic (to be …
=> feat: add StreamBackwardsReconciliationThreshold on-chain setting

packages/sdk/src/syncedStreamsLoop.ts
since the sync hasn’t failed, it will pick back up
=> Update “sync timed out” error to “sync stalled”

packages/sdk/src/streamStateView.ts
When decrypting also update the copy of the event in the local minipool
If an event gets decrypted before it is confirmed, confirming it could undo the decryption
This has been a bug since i simplified the timeline
=> Client - Re-Encryption bug: When decrypting also update the copy of the event in the local minipool

packages/sdk/src/persistenceStore.ts
this wasn’t a bug, just an edge case that wasn’t covered when I expected it to be.
=> Include minipool events when we prefetch cleartexts from the store

packages/sdk/src/clientDecryptionExtensions.ts, packages/sdk/src/decryptionExtensions.ts, packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts
1. don’t double enqueue the user inbox messages task
2. don’t wait for the user inbox stream to sync before decrypting
3. sort own and ephemeral solicitations and make sure that we only respond to solicitations if the stream is up to date
=> Update the decryption extensions queue again

core/node/rpc/stream_test.go
messages are only ordered once they make it into a miniblock. Before that they are added to the minipool and there is no guaranteed ordering there.
Fixing the tests so unordered messages are ok
=> Ephemeral messages: allow unordered messages in test

packages/sdk/src/client.ts, packages/sdk/src/streamStateView_AbstractContent.ts, packages/sdk/src/streamStateView_Channel.ts
in the spirit of only sync the channel you’re currently looking at, stop scrolling back on channels in the sdk
we have duplciate scrollback logic in the app
cursory testing doesn’t turn over any problems
=> Stop scrolling back on all channels by default

.gitignore, packages/stress-testing/run-docker-stress.sh, packages/stress/CLAUDE.md, packages/stress/src/mode/chat/joinChat.ts, packages/stress/src/mode/chat/kickoffChat.ts
Fixes race condition where follower clients tried to join spaces before root client finished minting memberships.
- Add synchronization signal after membership minting completes
- Remove unnecessary 1.1s delay between minting operations
- Add run-docker-stress.sh script for local stress test orchestration
- Document stress test architecture in CLAUDE.md
=> fix: resolve race condition in stress test membership minting

core/docs/features/backwards-reconciliation.md
- Updated backwards reconciliation documentation to reflect completed PR implementations
- Added references to merged PRs that implemented various steps of backwards reconciliation
- Updated step statuses from "Not implemented" to completed with PR references
- Added PR links for steps 1, 2, 3, and partial implementation of step 4
=> docs: update backwards reconciliation documentation with completed PRs

packages/contracts/src/spaces/facets/DependencyLib.sol, packages/contracts/src/spaces/facets/Entitled.sol, packages/contracts/src/spaces/facets/swap/SwapFacet.sol
- Reorganized import paths across files for consistency and readability.
- Added `SWAP_ROUTER` constant in `DependencyLib` and refactored `SwapFacet.getSwapRouter` to utilize it.
- Removed redundant constants like `SWAP_ROUTER_DIAMOND` and `_getSpaceFactory` from `SwapFacet`.
- Improved `getDependencies` logic by updating returned naming for clarity.
- General cleanup and formatting updates across files.
=> refactor(contract): tidy imports and enhance dependency handling

packages/sdk/src/tests/multi_ne/ephemeralEvents.test.ts
any online client can respond to a key solicitation request, and it's possible to get multiple fulfillments for a single key solicitation message.
Fix the test to allow more than a single fulfillment message
=> Flaky test: Allow more than one fulfillment message

packages/sdk/src/decryptionExtensions.ts
my comment was dumb, this can get called hunderds of times, tick sorts the stream ids, it’s expensive.
=> Fix the over-enqueueing of tick in decryption extensions

packages/web3/src/space-dapp/SpaceDapp.ts, packages/web3/src/space/IMembershipShim.ts
Our SpaceDapp sets the pollingInterval on the provider to 250ms - which is probably unnecessary, but we can change that in a different PR
```
if ('pollingInterval' in provider && typeof provider.pollingInterval === 'number') {
provider.pollingInterval = 250
}
```
The membership listener was using the ethers/typechain filter listener, which used this pollingInterval, which can result in extraneous rpc requests.
This PR changes that behavior such that:
- it uses getLogs w/ an interval of 1_000 ms to reduce rpc calls
- listenForMembershipToken returns a function. Call the returned function to start polling from the block number saved in the call to listenForMembershipToken (see example comment)
=> IMembershipShim: change listenForMembershipToken to use getLogs

packages/contracts/src/spaces/facets/dispatcher/DispatcherBase.sol, packages/contracts/src/spaces/facets/dispatcher/DispatcherStorage.sol, packages/contracts/src/spaces/facets/dispatcher/IDispatcher.sol, packages/contracts/src/spaces/facets/membership/join/MembershipJoin.sol, packages/contracts/src/spaces/facets/xchain/SpaceEntitlementGated.sol, packages/contracts/src/utils/libraries/StringSet.sol
Standardize storage manipulation across the codebase by introducing and utilizing the `StoragePointer` library for efficient direct storage access. This refactoring improves code clarity, reusability, and performance by eliminating custom wrapper types and redundant operations.
- Introduced `StoragePointer` library import from `@towns-protocol/diamond` package
- Replaced custom `BytesWrapper` struct with `StoragePointer.Bytes` for improved clarity and reusability  
- Refactored `StringSet.sol` to use `StoragePointer.String` and `StoragePointer.Uint256` instead of custom wrapper types
- Updated `DispatcherBase.sol` transaction data handling:
- Added `_deleteCapturedData()` method for efficient storage cleanup
- Changed `_getCapturedData()` to return `bytes storage` reference instead of …
=> refactor(contract): standardize storage handling with `StoragePointer`

packages/contracts/src/spaces/facets/swap/SwapFacet.sol, packages/contracts/test/spaces/swap/SwapFacet.t.sol
Fixes L-2 audit finding where poster fees were incorrectly refunded when `forwardPosterFee=true` but `poster=address(this)`. When a space acts as its own poster, fees should remain with the space regardless of the `forwardPosterFee` setting.
- Modified `_handleRefunds` function to accept `poster` parameter
- Simplified refund logic to check `poster == address(this)` instead of complex boolean condition
- Enhanced test coverage with `forwardPosterFee` fuzzing to cover both edge cases
- Optimized test assertions by removing redundant intermediate calculations
- Fixed edge case in fee manipulation attack test
=> fix(contract): resolve incorrect poster fee refund in `SwapFacet`

core/node/rules/can_add_event.go, packages/sdk/src/tests/multi_ne/client.test.ts
This needs to wait for iOS updates
I think it was a mistake to not pass session ids in the initial key solicitations, we end up in a situation where we can ping pong solicitations without actually satisfying the request. The contents of this change
- isNewDevice becomes a suggestion instead of a state
- all key requests now require session ids
- if isNewDevice is true, clients will still send all known sessions, but explicitly state in the fulfillment if they fulfilled any of the requested ids.
this should tighten the reqest loop and prevent at least one back and forth between clients in some cases.
=> Server rules for handling of isNewDevice

packages/sdk/src/client.ts, packages/sdk/src/persistenceStore.ts, packages/sdk/src/syncedStreams.ts, packages/sdk/src/syncedStreamsExtension.ts, packages/sdk/src/syncedStreamsLoop.ts, packages/sdk/src/tests/multi_ne/syncedStreams.test.ts
when we set high priority streams, save off the timestamps. sort by that timestamp.
tested in harmony, printed out loading and saving the lastAccessedAt property after clicking around a bit. DMs finally load in a normal way.
=> sort loading and syncing by last accessed at

core/node/events/miniblock_info.go, core/node/events/stream.go, core/node/events/stream_cache.go, core/node/events/stream_ephemeral_test.go, core/node/rpc/archiver.go, core/node/rpc/create_media_stream.go, core/node/rpc/miniblock_scrub_test.go, core/node/rpc/node2node_ephemeral.go, core/node/rpc/replicated_add.go, core/node/storage/pg_ephemeral_store.go, core/node/storage/pg_snapshot_trimmer_test.go, core/node/storage/pg_storage_archive_test.go, core/node/storage/pg_stream_store.go, core/node/storage/pg_stream_store_gaps_test.go, core/node/storage/pg_stream_store_preceding_test.go, core/node/storage/pg_stream_store_reinitialize_test.go, core/node/storage/pg_stream_store_test.go, core/node/storage/pg_stream_store_write_miniblocks_test.go, core/node/storage/pg_stream_trimmer_test.go, core/node/storage/storage.go
Remove WriteMiniblockData struct and use MiniblockDescriptor for all miniblock storage operations. This simplifies the storage interface by eliminating duplicate data structures.
=> refactor: consolidate miniblock data structures

core/node/rpc/forwarder.go, core/node/rpc/service_norace_test.go
Miniblock index can't be negative, and there should be at least one miniblock in the requested range
=> Add validation for miniblock index range in getMiniblocksImpl function.

packages/sdk/src/streamEvents.ts, packages/sdk/src/streamStateView.ts, packages/sdk/src/tests/multi_ne/ephemeralEvents.test.ts
This test is flaky. Maybe I'm missing something but:
- after random timeouts, clients are racing to fulfill a solicitation. in this case there are 3 clients (alice, bob, charlie) with keys syncing the same stream. chuck is soliciting keys.
- sometimes clients will not have had time to pick up that someone else fulfilled the solicitation at the same time, and will also send a fulfillment
- we were using `fulfillment.userId` for checking senders, but that id belongs to the key solicitor. we need to use the `senderUserId` for this approach to work
=> potentially fix flaky test

core/node/rules/can_add_event.go
this looks like copy pasta, no need to check one of if there’s only one, it’s just extra overhead.
=> Remove unnecessary checkOneOf, replace with check

packages/web3/src/BaseContractShim.ts, packages/web3/src/readContractRetryer.ts, packages/web3/tests/BaseContractShim.test.ts
The `BaseContractShim` provides a `read` contract which is used for reading data. This PR updates the read contract methods to bake in retries.
I only applied the retries to shims configured for Base networks - tests failed with shims configured on River - there were timeouts b/c getStreams retried instead of failing immediately, and I'm not sure if that would have real world consequence. So for now let's just retry Base reads, which is where we're getting failures in prod anyway.
This contract is not used for writes, as there is a separate `write` contract.
=> BaseContractShim: add retries to read contract

core/node/rpc/sync_runner_norace_test.go, core/node/track_streams/metrics.go, core/node/track_streams/multi_sync_runner.go, core/node/track_streams/streams_tracker.go
- Refactored metrics to be owned by MultiSyncRunner instead of StreamsTracker
- Added two new metrics for better observability:
- `OpenSyncSessions`: Tracks active sync sessions per target node
- `UnsyncedQueueLength`: Monitors the pending streams queue length
=> Move metrics ownership to MultiSyncRunner; add sync runner metrics

packages/sdk/src/sync-agent/syncAgent.ts, packages/stress/src/utils/stressClient.ts
=> Stop using shared syncer in the stress tests

packages/stream-metadata/src/routes/userSpaces.ts, packages/stream-metadata/tests/integration/userSpaces.test.ts
Issue: ppl join a new town and this endpoint gets outdated
Since we dont have a way to invalidate the cache, a easy solution is to just reduce the cache time
=> fix(stream-metadata): reduce cache time of `/user/userId/spaces`

core/node/track_streams/multi_sync_runner.go
Fix the queue length metric to refer to the size of the worker pool queue, instead of the size of a channel that's emptied by the worker pool, which will probably be close to zero even when many unsynced streams are waiting for sync session assignment.
=> Fix the unsynced queue length metric

packages/contracts/src/airdrop/drop/DropFacet.sol, packages/contracts/test/airdrop/DropFacet.t.sol
- Introduced a new address and key in the DropFacetTest contract.
- Added a test case for account claim with no points, verifying expected balance outcomes.
- Updated claim logic to remove unnecessary default values for claim points.
- Enhanced the Merkle tree construction to include new data for claims.
- Separate burn points logic to internal function
=> feat(contract): add no points check to drop facet

core/cmd/stream_cmd.go
Add the option to provide a node address to the stream dump subcommand to dump the stream from a particular node.
=> node: add ability to dump stream from a node

core/justfile
Anvil persists unlimited number of state files to disk, eventually using the entire free space.
Using `--max-persisted-states` to limit the number of tmp files.
=> Limit number of persisted states in Anvil to 50

.gitignore, packages/subgraph/.env.alpha, packages/subgraph/docker-compose-alpha.yml, packages/subgraph/ponder.config.alpha.ts
Setup an alpha environment for subgraph with capabilities to run alpha locally and in CI with docker-compose.
- config, env (with public rpc url) supporting alpha subgraph instance.
Tested with docker compose
```
➜  subgraph git:(jt/towns-30674-alpha-subgraph-on) ✗ docker compose -f docker-compose-alpha.yml up --build
➜  subgraph git:(jt/towns-30674-alpha-subgraph-on) ✗ curl http://localhost:42069/status                  
{"alpha":{"id":84532,"block":{"number":17814533,"timestamp":1731397354}}}%                                                                            
➜  subgraph git:(jt/towns-30674-alpha-subgraph-on) ✗ curl http://localhost:42069/ready 
Historical indexing is not complete.% 
```
=> Subgraph alpha configuration

core/node/rpc/service_norace_test.go, core/node/rpc/service_test.go, packages/sdk/src/tests/multi_ne/streamRpcClient.test.ts, packages/sdk/src/tests/multi_ne/streamRpcClientSync.test.ts
Start using ModifySync in tests instead of AddStreamToSync and RemoveStreamFromSync operations
=> Use ModifySync instead of AddStreamToSync and RemoveStreamFromSync

core/config/config.go, core/node/rpc/notifications.go
Since viper does not support arrays configurations via env var, Apps field cannot be initialized automatically.
As a workaround, we have added the TownsApp and SenditApp fields, and we copy their values to the Apps field, so the rest of the code can stay `apps` agnostic.
in the future, this configuration (both *App and Apps) will be moved to a database, to allow dynamic config without code changes
=> Fix notifications apps configuration

packages/contracts/foundry.toml, packages/contracts/scripts/deployments/utils/DeployTownsBase.s.sol, packages/contracts/scripts/interactions/InteractBaseAlpha.s.sol, packages/contracts/src/tokens/towns/base/TownsDeployer.sol, packages/contracts/test/base/registry/DelegationProxy.t.sol, packages/contracts/test/mocks/MockTownsDeployer.sol
- Utilize `abi.encodeCall` for cleaner initialization bytecode.
- Simplify `_deploy` logic for improved broadcast and test handling.
- Add lint severity configuration and exclusions in `foundry.toml`.
- Enhance tests by labeling deployments and introducing additional fuzz test parameters.
- Update `Towns` imports to relative paths and remove unused environment variable in `InteractBaseAlpha`.
=> refactor(contract): use `abi.encodeCall` and update deploy logic

core/config/config.go, core/config/config_test.go, core/node/notifications/push/push.go, core/node/notifications/push/push_test.go
Now that we fully support two apps, there is no need to be backward compatible, all the of the envs have the correct configuration
=> Removed handling of legacy notifications configuration

packages/subgraph/package.json, turbo.json
Build subgraph as part of CI though ponder runs on-the-fly compilation to javascript rendering the build artifacts unused, errors are picked up at build time such as when contract typings break the subgraph schema. This will help keep the subgraph up to date as contract dependencies change.
=> Build subgraph as part of CI

core/node/app_registry/types/app_metadata.go, core/node/rpc/app_registry_test.go, packages/bot/src/bot.test.ts, protocol/apps.proto
So we can use the stream metadata `/user/:appId/image` in the image / avatar field
Added a max len check, using [Amazon Cloudfront max url size](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html)
=> remove validation for image extension in `SetAppMetadata`

packages/subgraph/Dockerfile, packages/subgraph/docker-compose.yml, packages/subgraph/src/index.ts, packages/subgraph/src/utils.ts, turbo.json
- add web3 deps to dockerfile needed by https://github.com/towns-protocol/towns/pull/3901. Also removes platform specification which is not needed anymore as Dockerfile can be built in arm64/amd architectures now. 
- fixes turbo cache so ci passes
=> Add web3 deps subgraph dockerfile

.github/workflows/Publish_npm_packages.yml, packages/generated/scripts/prepare.js, scripts/publish-to-npm.sh
- Add timeout-minutes: 60 to GitHub Actions publish workflow
- Filter out CodeRabbit from required checks in publish-to-npm.sh to prevent infinite waiting
- Add contracts directory check in prepare.js before attempting local generation
This prevents publish workflows from hanging indefinitely when CodeRabbit stays in "pending" state, while maintaining all existing error handling logic.
=> fix(publish): prevent hangs from pending CodeRabbit reviews

packages/sdk/src/streamStateView.ts, packages/sdk/src/tests/multi_ne/client.test.ts, packages/sdk/src/types.ts, packages/sdk/src/views/models/timelineEvent.ts, packages/sdk/src/views/models/timelineTypes.ts, packages/sdk/src/views/streams/timelines.ts, packages/sdk/src/views/streams/timelinesModel.ts
this is a time that isn’t set by other clients that you can trust in the ui
=> Add confirmedAtEpochMs for timeline events

packages/examples/bot-ask-poll/src/index.ts, packages/examples/bot-quickstart/src/index.ts, packages/examples/bot-thread-ai/src/index.ts
The bot server itself isnt responsable of this. Lets leave it to render / vercel / fly.io. I always had this issue when deploying bots. We can come with a better way of testing bots local later
=> fix: remove `node:http2` from bot examples

core/node/protocol/apps.pb.go, protocol/apps.proto
The `username` field is unique in database, constrained by a column with `UNIQUE` index. `displayName` is stored with metadata in a `jsonb`
=> fix: misleading info about display name uniqueness in `apps.proto`

core/cmd/stream_cmd.go, core/node/shared/stream_id.go
Summary
Added a new subcommand to scan the Towns network and detect broken or inconsistent streams by comparing miniblock state across all nodes.
Changes
- Enhanced stream check-state command to scan all streams in the network in parallel
- Compares last miniblock hash/number between registry and all stream nodes
- Categorizes streams into OK, NOTICE, WARN, and ERROR states based on consistency
- Outputs results to separate JSONL files for easy analysis
- Added JSON marshaling support to StreamId type for proper serialization
=> node: add sub command to scan network and report broken streams

packages/contracts/package.json, packages/contracts/src/apps/BaseApp.sol, packages/contracts/src/apps/ITownsApp.sol, packages/contracts/src/apps/facets/registry/AppRegistryBase.sol, packages/contracts/src/apps/facets/registry/IAppRegistry.sol, packages/contracts/src/apps/helpers/SimpleApp.sol, packages/contracts/src/spaces/facets/account/AppAccountBase.sol, packages/contracts/src/spaces/facets/account/IAppAccount.sol, packages/contracts/test/attest/AppRegistry.t.sol, packages/contracts/test/attest/AttestationRegistry.t.sol, packages/contracts/test/mocks/MockInvalidModule.sol, packages/contracts/test/mocks/MockModule.sol, packages/contracts/test/mocks/MockPlugin.sol, packages/contracts/test/mocks/MockSavingsModule.sol, packages/contracts/test/spaces/account/AppAccount.t.sol, yarn.lock
Updated ERC6900 interface imports to match the reference implementation v0.8.0, replacing deprecated interface names with their current versions.
- Downgraded `@erc6900/reference-implementation` from v0.8.1 to v0.8.0
- Updated interface imports across the codebase:
- `IERC6900Module` → `IModule`
- `IERC6900ExecutionModule` → `IExecutionModule`
- `IERC6900Account` → `IModularAccount`
- Moved event definitions from the ERC6900 interfaces to our own interfaces
- Fixed import paths for `ExecutionManifest` and other types
- Updated interface checks in `supportsInterface` implementations
=> refactor: update ERC6900 imports to use v0.8.0 interface names

core/node/events/stream.go, core/node/events/stream_reconcile_task.go, core/node/rpc/repl_test.go
Fixed stream reconciliation for streams stuck at miniblock 0 by implementing fallback to genesis block recovery from the stream registry. It turns out that some streams are still assigned to a node dat left the network causing other nodes not able to reconcile the stream.  For streams that never moved beyond genesis it is possible to reconcile from the stream record in the steams registry.
Some of the following log entries are the result of this problem.
```
reconcileStreamFromPeers: Unable to reconcile stream from peers
```
An example stream `0xa5a087d6de203a8494d6b6e6bcb1e0ae2426c95b830000000000000000000000`
```
stream: 0xa5a087d6de203a8494d6b6e6bcb1e0ae2426c95b830000000000000000000000
miniblock: 0
hash: 0x88f3eb633f3475011a18cfe66ddf8ff1a4b524be6516dc320cbb9ff85e85cbc1
nodes: …
```
=> node: reconcile from stream registry record for streams at mb 0

packages/contracts/deployments/delta/base/addresses/appRegistry.json
Added the AppRegistry contract address for the Base network in the Delta deployment configuration.
- Added a new JSON file containing the AppRegistry contract address (`0x9fCd4F3F98b170C7A1AfB9d20E76C6f5ca9Cbe71`) for the Base Sepolia network in the Delta deployment
=> feat: add appRegistry address for Base delta deployment

core/contracts/src/README.md, core/contracts/src/river/registry, core/node/protocol/src/README.md, core/node/protocol/src/auth.proto, core/node/protocol/src/bots.proto, core/node/protocol/src/internode.proto, core/node/protocol/src/notifications.proto, core/node/protocol/src/protocol.proto
llm tools are smart enough to load correct files now. these hacks to reduce context are no longer required.
Remove symlinked files across repo.
=> Remove softlinks and associated README files from the project.

packages/bot/src/bot.test.ts, packages/bot/src/bot.ts, packages/examples/README.md, packages/examples/bot-ask-poll/.env.sample, packages/examples/bot-ask-poll/README.md, packages/examples/bot-ask-poll/src/index.ts, packages/examples/bot-quickstart/.env.sample, packages/examples/bot-quickstart/README.md, packages/examples/bot-quickstart/src/index.ts, packages/examples/bot-thread-ai/.env.sample, packages/examples/bot-thread-ai/README.md, packages/examples/bot-thread-ai/src/index.ts, packages/playground/src/components/dialog/create-bot/bot-credentials-dialog.tsx, packages/playground/src/components/dialog/create-bot/index.tsx, packages/sdk/src/id.ts
Backward compatible update. 
This PR creates a helper to build / parse private key data and adds a prefix to the key to make it findable.
Should close TOWNS-31001
=> add `towns-bot-` prefix to app private data key

.vscode/tasks.json, CLAUDE.md, CONTRIBUTING.md, scripts/run-local-ci.sh
Adds local CI testing capabilities to enable developers to validate GitHub Actions workflows locally before pushing changes. This improves the development workflow by catching CI issues early and reducing failed CI runs.
- Added `scripts/run-local-ci.sh` script to test GitHub Actions workflows locally using act
- Fixed event payload structure to include `repository.default_branch` for all event types (schedule, pull_request, workflow_dispatch)
- Updated platform mapping from `arc-runners` to `ubuntu-x64-16core` for proper runner compatibility
- Documented script usage in `CLAUDE.md` and `CONTRIBUTING.md` with examples and Docker requirement
- Added VSCode task "Test CI Locally" for easy access via Command Palette (`Cmd+P` → `task Test CI Locally`)
=> feat(ci): add local CI testing support with run-local-ci.sh script

scripts/deploy-contracts.sh
it’s fine to start anvil with a sub second block time, but you can’t cast setIntervalMining to less than one, you get a cryptic error
```
Error: server returned an error response: error code -32602: invalid number
```
Our user ops tests use 0.1 block times, and i’d like them to share this script
=> Deploy contract script update - protect against setting block time to less than 1

packages/examples/bot-quickstart/package.json, yarn.lock
we're using it to build slash commands.
wasn't caught in CI since yarn hoists it for us
=> add proto as dependency to quickstart example

packages/bot/README.md, packages/bot/src/bot.test.ts, packages/bot/src/bot.ts, packages/examples/bot-quickstart/src/index.ts, packages/examples/bot-thread-ai/src/index.ts
It all started in https://github.com/towns-protocol/towns/pull/4108#issuecomment-3283613915
Previous API was confusing. 
What happens if you have
```ts
onReply(client) => client.sendMessage('oh you replied me!')
onMessage(client) => client.sendMessage('new message!')
```
and you reply a message?
Will it trigger both? You send a reply, so it should trigger `onReply`. But the reply was also a message, so should it call `onMessage` too?
What if you sent a reply message in thread mentioning the bot? We had `onReply`, `onThreadMessage`, `onMentioned`, `onMentionedInThread`. Should it call all of three? 😵‍💫
This PR simplify handlers, removing `onReply`, `onMentioned`, `onThreadMessage`, `onMentionedInThread`. All of this data is now consolidated in `onMessage`.
You can get `threadId`, …
=> feat: simplify bot handlers, improve `onMessage`

packages/bot/src/bot.ts, packages/sdk/src/client-v2.ts
Use case: send a quick status response to user (no need to persist)
```
User: /ai solve the riemann hypothesis
Bot: I'll think. It may take a while (ephemeral message)
```
=> feat(bots): support for sending ephemeral messages

packages/examples/bot-quickstart/esbuild.config.mjs, packages/metrics-discovery/esbuild.config.mjs, packages/stream-metadata/esbuild.config.mjs, packages/stress/esbuild.config.mjs, packages/xchain-monitor/esbuild.config.mjs
Our code is compiled for multiple platforms. We don’t need to see this everywhere
Warning: G] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]
../dlog/dist/envUtils.js:10:19:
10 │         if (typeof import.meta === 'object' && 'env' in import.met...
╵                    ~~~~~~~~~~~
=> Silence import meta build warnings in esbuilds

core/node/crypto/chain_monitor.go
This PR fixes incorrect documentation comments in the NodeRegistryChainMonitor interface and
related type definitions.
Changes
- Fixed copy-paste errors in interface method documentation:
- OnNodeAdded: Corrected description (was incorrectly labeled as "OnNodeStatusUpdated")
- OnNodeUrlUpdated: Corrected description (was incorrectly labeled as "OnNodeStatusUpdated")
- OnNodeRemoved: Corrected description (was incorrectly labeled as "OnNodeStatusUpdated")
- Fixed type definition comment:
- OnNodeAddedCallback: Corrected comment that incorrectly stated "called each time a node url is
removed" to properly match the callback purpose
Impact
This is a documentation-only change with no functional impact. It improves code clarity and helps
developers understand the correct purpose of each …
=> node/core/crypto: fix minor documentation issues

core/node/crypto/chain_monitor.go, core/xchain/server/server.go
This PR refactors the entitlement check event handling by moving the event decoding logic from the
xchain server into a dedicated EntitlementCheckChainMonitor in the crypto package.
Changes
- Added EntitlementCheckChainMonitor interface and implementation in crypto/chain_monitor.go
- Provides specialized monitoring for entitlement check events on the base chain
- Handles unpacking of both V1 and V2 EntitlementCheckRequested events
- Encapsulates the ABI decoding logic and error handling
- Simplified xchain server event handling in xchain/server/server.go
- Removed direct ABI unpacking logic from event handlers
- Now receives pre-decoded event structs via callbacks
- Cleaner separation of concerns between event monitoring and business logic
Benefits
1. Better encapsulation: Event decoding …
=> node: move entitlement log to event decoding to crypto pkg

packages/bot/src/bot.ts
This PR introduces dlog for webhook requests in bot framework
If you have a bot, you can set those env:
```
DEBUG_DEPTH=100
DEBUG=csb:bot
```
and you should be able to inspect webhook events.
=> bot-framework: add webhook events debug log

.github/workflows/ci.yml
postgres:latest matched to pg 18 released yesterday, and it seems it needs additional config to work. Pin pg version to 17
=> Set PostgreSQL image version to 17 in GitHub Actions workflow.

.github/workflows/Metrics_discovery_docker.yml, .github/workflows/Stream_metadata_docker.yml, .github/workflows/Stress_test_node_docker.yml, .github/workflows/Subgraph_docker.yml, .github/workflows/Towns_anvil_docker.yml, .github/workflows/XChain_monitor_docker.yml, .github/workflows/_build-docker-arch.yml, .github/workflows/_create-docker-manifest.yml
Modularize Docker build workflows with centralized reusable logic and fix git operations for GitHub Actions compatibility.
- **Create reusable workflows:**
- `_build-docker-arch.yml` - Centralized single-arch Docker builds with ECR login and tag generation
- `_create-docker-manifest.yml` - Multi-arch manifest creation and validation
- **Fix git operations for GitHub Actions:**
- Replace `git describe` with `git rev-parse --short HEAD` for Docker-safe commit hashes
- Use `github.ref_name` instead of `git rev-parse --abbrev-ref HEAD` for branch detection (fixes detached HEAD issue)
- Add missing `id: login-ecr` to ECR login steps for output references
- **Standardize workflows:**
- Single-arch workflows (Metrics_discovery, Stream_metadata, Stress_test_node, XChain_monitor) simplified to ~50 …
=> refactor(docker): modularize Docker builds with reusable workflows

core/env/alpha/config.yaml, core/env/delta/config.yaml, core/env/gamma/config.yaml, core/env/omega/config.yaml
because we keep everything in N places
not sure how this is working on alpha though…
=> Add app registry address to the config.yaml’s for the different environments

packages/contracts/scripts/deployments/diamonds/DeploySubscriptionModule.s.sol, packages/contracts/scripts/interactions/InteractBaseAlpha.s.sol
Added support for the Subscription Module in the diamond initialization process and integrated it into the base alpha interaction script.
- Implemented `IDiamondInitHelper` interface in `DeploySubscriptionModule` to standardize diamond initialization
- Added `diamondInitHelper` method to handle facet deployment and cutting
- Updated `InteractBaseAlpha` to include the Subscription Module in the deployment process
- Added proper execution of diamond cuts for the Subscription Module
=> Implement Subscription Module deployment and interaction integration

core/node/app_registry/service.go
Previously, if webhook was unavaliable, it was throwing a error of `GetStatus` instead of returning 200 with the `validResponse` field set to false
This way, even if bot is unavaliable, we can know if its set as `active` and if its registered.
Should close TOWNS-31307.
=> app-registry: return valid response status in `GetStatus`

core/node/app_registry/app_client/app_client.go
We do not want to expose the webhook url of a bot in a public endpoint.
=> TOWNS-31203 Removed webhook url from errors returned in public endpoints

core/node/app_registry/service.go, core/node/app_registry/types/app_metadata.go, core/node/rpc/app_registry_test.go
Added a bunch of username validation for bots:
- Must start with a letter or number
- Can contain letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-)
- Must be between 1 and 255 characters
- No spaces allowed
=> TOWNS-31164 Bot username validation - do not allow space

packages/sdk/src/tests/multi/spaceWithVariousPriceConfigurations.test.ts, packages/web3/src/space-dapp/SpaceDapp.ts, packages/web3/tests/getJoinSpacePriceDetails.test.ts
Added protocol fee to the `getJoinSpacePriceDetails` method to properly account for the total cost when joining a space.
- Added `protocolFee` property to the return type of `getJoinSpacePriceDetails`
- Updated the method to fetch protocol fee data via multicall
- Modified the method to decode and return the protocol fee value
- Updated tests to verify that the price includes the protocol fee
=> feat: add protocolFee to getJoinSpacePriceDetails response
