core/node/events/stream_cache.go

Also refactor code a bit to make proposals in parallel.

Fix test flakiness due to simultaneous miniblock production

---

core/proto/scripts/watch_proto_files.cjs
core/proto/scripts/watch_proto_files_go.cjs

These have been off since we moved the proto files, causing issues if you switched between branches that had different protobuf definitions

Fix the protobuf watch scripts.

---

core/node/crypto/blockchain.go
core/node/crypto/chain_txpool.go
core/node/crypto/chain_txpool_test.go
core/node/crypto/testutil.go
core/node/events/minipool.go
core/node/events/snapshot.go
core/node/events/stream_view.go
core/node/infra/metrics.go
core/node/infra/metrics_factory.go
core/node/nodes/stream_nodes.go
core/node/registries/river_registry_contract.go
core/node/rpc/archiver.go
core/node/rpc/archiver_test.go
core/node/rpc/server.go
core/node/rpc/service_test.go
core/node/storage/pg_storage.go

Format with golines and gofumpt

---

core/node/events/migrations/migrate_snapshot.go

These files were recently moved

Fix bad file path in comment

---

packages/web3/src/TestGatingNFT.ts

Address gas estimate too low in tests when multiple test NFT are being minted in one block by incrementing the nonce properly

---

.github/CODEOWNERS

the latest line takes presidence

One more code owners fix

---

core/node/auth/auth_impl.go
core/node/auth/fake_auth.go
core/node/rpc/add_event.go
core/node/rpc/create_stream.go

Allow caller to distinguish between not entitled and evaluation errors.

Refactor IsEntitled to return bool, error pair

---

contracts/scripts/deployments/facets/DeployRewardsDistribution.s.sol
contracts/src/base/registry/facets/distribution/IRewardsDistribution.sol
contracts/src/base/registry/facets/distribution/RewardsDistribution.sol
contracts/test/base/registry/RewardsDistribution.t.sol

https://testnets.llama.xyz/orgs/river/base-sepolia/actions/112

Fix H1 H2 breakup claim function and fix bug when same address delegates on both chains

---

core/node/default_config.yaml

Add metrics intrface to default config so it can be set from env vars

---

contracts/src/factory/facets/prepay/PrepayFacet.sol

Testnet Proposal: https://testnets.llama.xyz/orgs/river/base-sepolia/actions/113

Update value check on prepay facet

---

contracts/scripts/deployments/facets/DeploySpaceDelegation.s.sol
contracts/src/base/registry/facets/delegation/ISpaceDelegation.sol
contracts/src/base/registry/facets/delegation/SpaceDelegationFacet.sol
contracts/test/base/registry/RewardsDistribution.t.sol
contracts/test/spaces/BaseSetup.sol

https://testnets.llama.xyz/orgs/river/base-sepolia/actions/115

Add function to calculate total operator delegation

---

contracts/scripts/deployments/facets/DeployEntitlementChecker.s.sol
contracts/src/base/registry/facets/checker/EntitlementChecker.sol
contracts/src/base/registry/facets/checker/IEntitlementChecker.sol
contracts/test/crosschain/EntitlementChecker.t.sol
contracts/test/spaces/BaseSetup.sol
core/xchain/create_multi.sh

https://testnets.llama.xyz/orgs/river/base-sepolia/actions/116

Only allow approved operators to register nodes, expose nodes by operator

---

core/node/auth/space_contract_v3.go
core/node/registries/river_registry_contract.go
core/node/rpc/forwarder.go

These are happening way to often to be useful, any objections?

Reduce noisy logs on node

---

packages/sdk/src/unauthenticatedClient.ts

i put this in really fast and this seems better

Small function rename in the unauthenticatedClient

---

packages/sdk/src/unauthenticatedClient.ts

I bungled this refactor https://github.com/river-build/river/commit/6829379f7810b715a8ac27dffa5f28349bc04454

Fix missing optional

---

contracts/src/spaces/entitlements/rule/RuleEntitlement.sol
contracts/test/crosschain/RuleEntitlement.t.sol

…
This reverts commit c46675d58aec9bab3970b794332eaa86edda7ffb.

Revert "If setEntitlement is called a second time, updating the ruleData, first clear the existing ruleData (#199)"

---

packages/sdk/src/signerContext.ts

Split out recover key code from check delegate sig code

---

packages/sdk/src/observable/decorators.test.ts
packages/sdk/src/observable/observable.ts
packages/sdk/src/observable/persistedObservable.ts
packages/sdk/src/store/store.test.ts
packages/sdk/src/store/store.ts
packages/sdk/src/sync-agent/README.md
packages/sdk/src/sync-agent/river-connection/models/riverNodeUrls.ts
packages/sdk/src/sync-agent/river-connection/riverConnection.test.ts
packages/sdk/src/sync-agent/river-connection/riverConnection.ts
packages/sdk/src/sync-agent/streams/streamsClient.ts
packages/sdk/src/sync-agent/syncAgent.test.ts
packages/sdk/src/sync-agent/syncAgent.ts
packages/sdk/src/sync-agent/user/models/userDeviceKeys.ts
packages/sdk/src/sync-agent/user/models/userInbox.ts
packages/sdk/src/sync-agent/user/models/userMemberships.ts
packages/sdk/src/sync-agent/user/models/userSettings.ts
packages/sdk/src/sync-agent/user/user.test.ts
packages/sdk/src/sync-agent/user/user.ts
packages/sdk/src/sync-agent/utils/providers.ts
packages/sdk/tsconfig.json

sync agent boots up
loads all state from idb in one transaction
runs initialization code which currently
loads the river urls
starts the user initialization
next
stream state
stream sync
spaces
channels

SyncAgent scaffolding

---

package.json

When I merge, I'll add to harmony too.

Make `yarn clean` a thing

---

core/node/storage/pg_storage.go

* The `sslmode` is hard-coded and if you attempt to use a non-`disable` value, the service will not start.
* If not specified, returns `disable` just as current functionality expects.

[db] parse sslmode

---

packages/sdk/src/client.ts
packages/sdk/src/makeStreamRpcClient.ts
packages/sdk/src/restart.test.ts
packages/sdk/src/syncedStreams.ts
packages/sdk/src/unauthenticatedClient.ts
packages/sdk/src/util.test.ts

I think maybe this wasn’t previously defined? Not sure how this got weird.

Remove duplicate type

---

packages/sdk/src/observable/persistedObservable.ts
packages/sdk/src/store/store.ts

It's really useful for everything to be set before we start doing side effect things

SyncAgent - Move the on loaded callbacks until after everything has been set

---

packages/sdk/src/observable/persistedObservable.ts
packages/sdk/src/sync-agent/river-connection/models/riverNodeUrls.ts
packages/sdk/src/sync-agent/user/models/userMemberships.ts
packages/sdk/src/sync-agent/user/user.ts

this needs to be per object, not per table

SyncAgent - move the load priority to the constructor

---

packages/sdk/src/streamEvents.ts
packages/sdk/src/syncedStreams.ts

I am investigating reusing this class in the sync agent, this makes it a little easier

Isolate the syncedStreamEvents

---

packages/sdk/src/riverConfig.ts

I finally got tripped up on it. Need more coffee and better error messages.

Update the BASE_CHAIN_ID error to be better

---

packages/web3/src/v3/RiverRegistry.ts

Sort node urls before returning in RiverRegistryDapp

---

contracts/scripts/deployments/facets/DeployRewardsDistribution.s.sol
contracts/src/base/registry/facets/distribution/IRewardsDistribution.sol
contracts/src/base/registry/facets/distribution/RewardsDistribution.sol
contracts/test/base/registry/RewardsDistribution.t.sol

https://testnets.llama.xyz/orgs/river/base-sepolia/actions/133
https://app.llama.xyz/orgs/river/base/actions/64

Allows mainnet delegators and operators to specify an address when claiming

---

packages/sdk/src/client.ts
packages/sdk/src/observable/observable.ts
packages/sdk/src/observable/persistedObservable.ts
packages/sdk/src/streamEvents.ts
packages/sdk/src/streamStateView_UserDeviceKey.ts
packages/sdk/src/streamStateView_UserInbox.ts
packages/sdk/src/sync-agent/river-connection/models/streamNodeUrls.ts
packages/sdk/src/sync-agent/river-connection/riverConnection.test.ts
packages/sdk/src/sync-agent/river-connection/riverConnection.ts
packages/sdk/src/sync-agent/syncAgent.test.ts
packages/sdk/src/sync-agent/syncAgent.ts
packages/sdk/src/sync-agent/syncAgentStore.ts
packages/sdk/src/sync-agent/user/models/userDeviceKeys.ts
packages/sdk/src/sync-agent/user/models/userInbox.ts
packages/sdk/src/sync-agent/user/models/userMemberships.ts
packages/sdk/src/sync-agent/user/models/userSettings.ts
packages/sdk/src/sync-agent/user/user.test.ts
packages/sdk/src/sync-agent/user/user.ts
packages/sdk/src/sync-agent/utils/spaceUtils.ts
packages/sdk/src/sync-agent/utils/syncAgentUtils.test.ts
packages/web3/src/LocalhostWeb3Provider.ts
packages/web3/src/v3/SpaceDapp.ts

slowly copying code over from the stress client, leaving places for the app view logic to go

SyncAgent - create space, user streams, observable dock

---

packages/sdk/src/sync-agent/db.ts
packages/sdk/src/sync-agent/river-connection/riverConnection.test.ts
packages/sdk/src/sync-agent/syncAgent.test.ts
packages/sdk/src/sync-agent/syncAgent.ts
packages/sdk/src/sync-agent/user/user.test.ts
packages/sdk/src/sync-agent/utils/testUser.test.ts

cleaning up the chaos before it spreads

SyncAgent - better tests, better db initialization

---

core/node/crypto/testutil.go

core: make auto commit transactions in go unit tests more reliable

---

packages/web3/src/v3/WalletLink.ts

missing fix in `linkCallerToRootKey`

fix wallet link for caller data

---

packages/web3/src/v3/Space.ts

Created a helper function to get all member addresess of a given space. See comments.

created a helper function to get all members of a space via ownerOf

---

contracts/src/spaces/facets/Permissions.sol
core/node/auth/permissions.go
packages/web3/src/ContractTypes.ts
packages/web3/src/v3/SpaceDapp.ts

Add REACT_REPLY and cause client to locally evaluate xchain entitlements for REACT_REPLY along with channel READ and WRITE.

Add REACT/REPLY permission

---

packages/sdk/src/sync-agent/river-connection/riverConnection.test.ts
packages/sdk/src/sync-agent/spaces/spaces.test.ts
packages/sdk/src/sync-agent/syncAgent.test.ts
packages/sdk/src/sync-agent/syncAgents.test.ts
packages/sdk/src/sync-agent/user/user.test.ts
packages/sdk/src/sync-agent/utils/bot.ts

make fundWallet a new bot function to run in tests

sdk: remove fundWallet from makeSyncAgent in Bot

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/metrics-discovery/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json
scripts/publish-to-npm.sh

commit 53c6dcc0985bd54ad5d5b24036fca7d37dac99de
Author: John Terzis <john@hntlabs.com>
Date:   Thu Jul 11 15:31:15 2024 -0700
b241aaf9-0.0.13

Release SDK b241aaf9

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/metrics-discovery/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 02b2c43b401f0ca84f972d26bb79d104cf7a9bd2
Author: John Terzis <john@hntlabs.com>
Date:   Thu Jul 11 20:27:17 2024 -0700
04cfc4a4-0.0.14

Release SDK 04cfc4a4

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/metrics-discovery/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2206b113c3e73bbba4b8fe257393c776954d7d03
Date:   Fri Jul 12 18:15:33 2024 +0000
740d828-0.0.15

Release SDK 740d828

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 645ab1f1e3b657cb72c1ad89506eb2c60404a40f
Date:   Sat Jul 13 00:19:03 2024 +0000
sdk-50fac98-0.0.16

Release SDK 50fac98

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 5ce3648690a93cb5a83e69353136970879970b85
Date:   Sun Jul 14 00:20:36 2024 +0000
sdk-0676df8-0.0.17

Release SDK 0676df8

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 04de68b34db6d88bbdee194d99d53e6a044310d6
Date:   Mon Jul 15 00:19:38 2024 +0000
sdk-ba97c03-0.0.18

Release SDK ba97c03

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 3c5d52a3ebf26ddb4a8c3dd236e1a20cee764004
Date:   Tue Jul 16 00:19:01 2024 +0000
sdk-6f5e4ff-0.0.19

Release SDK 6f5e4ff

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 80d05f5ba9b26684edbce8dc9e66e2a4a0ac12a1
Date:   Wed Jul 17 00:19:12 2024 +0000
sdk-e31601d-0.0.20

Release SDK e31601d

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 4be5223892c1dfaafae1fd3325d46989cf33ab61
Date:   Fri Jul 19 01:16:50 2024 +0000
sdk-263acc3-0.0.21

Release SDK 263acc3

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 510d4068a4ff63c0890ed4c905e1b90c0c602d11
Date:   Sat Jul 20 00:18:32 2024 +0000
sdk-e7752cb-0.0.22

Release SDK e7752cb

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 5d0bd9487dd2d8f51b962509841b255979d487f2
Date:   Sun Jul 21 00:20:25 2024 +0000
sdk-340476f-0.0.23

Release SDK 340476f

---

core/node/rules/can_add_event.go
packages/sdk/src/channelsWithEntitlements.test.ts
packages/sdk/src/client.ts

Update the react permission implementation to ensure that REACT users can redact their reactions.

Update client and stream server to allow redactions from REACT user.

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f81b87e42751d299799ca41625fddf8b13cdbabf
Date:   Thu Jul 25 00:18:52 2024 +0000
sdk-28b4c3a-0.0.24

Release SDK 28b4c3a

---

packages/react-sdk/src/useObservable.ts
packages/sdk/src/observable/observable.ts

and add a get value in case it’s usable
going to use usSyncExternalStore https://github.com/facebook/react/blob/f7ee804c2270b451087a697d181ef9f421e23f33/packages/use-sync-external-store/src/useSyncExternalStoreShimClient.js#L30
docs https://react.dev/reference/react/useSyncExternalStore

update use observable to return unsub function

---

packages/sdk/src/sync-agent/river-connection/riverConnection.ts

When implemented in the browser, if we wait to register views until after we’re connected we end up registering them twice.

SDK sync agent: Stop register view functions getting called twice

---

packages/sdk/src/sync-agent/spaces/models/space.ts

no concrete changes, just order things properly

SDK sync agent clean up the space observable listeners

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 09d3a756e9a03ec6b45d7def8801212920a46acf
Date:   Mon Jul 29 00:19:43 2024 +0000
sdk-f454024-0.0.25

Release SDK f454024

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 59e207ccc26a1ea9e21e391f23f7d8ca6a8b91b9
Date:   Tue Jul 30 00:19:19 2024 +0000
sdk-99fa07a-0.0.26

Release SDK 99fa07a

---

core/node/env/alpha/config.yaml
core/node/env/alpha/run.sh
core/node/env/gamma-arch/config.yaml
core/node/env/gamma/config.yaml

+add missing addrs for other envs.
For example
```
./core/node/env/alpha/run.sh registry streams --count
```
Prints stream count from alpha registry contract.

Add alpha config for cmd line river_node tool

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 5cab6beb61df2c6e0b1815cbb3b20844d5c0f6c8
Date:   Thu Aug 1 00:21:15 2024 +0000
sdk-58c551e-0.0.27

Release SDK 58c551e

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 152aed82930e94c66d1f670c7eb07482dff68859
Date:   Fri Aug 2 00:19:09 2024 +0000
sdk-094bc40-0.0.28

Release SDK 094bc40

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 03532250c69d8e54b781da00298c157a6bc8aab6
Date:   Sat Aug 3 00:18:46 2024 +0000
sdk-bbe091a-0.0.29

Release SDK bbe091a

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0e567ce6a0f37927e8404abd71ba1c2854115dd1
Date:   Sun Aug 4 00:20:26 2024 +0000
sdk-544c40a-0.0.30

Release SDK 544c40a

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 953aafe61c20d6d588716aa52e059e9fde3a0e81
Date:   Mon Aug 5 00:19:48 2024 +0000
sdk-a4151ad-0.0.31

Release SDK a4151ad

---

packages/dlog/src/dlog.ts
packages/encryption/src/encryptionDevice.ts
packages/encryption/src/tests/encryption-protocol.test.ts
packages/sdk/src/channelsWithEntitlements.test.ts
packages/sdk/src/client.test.ts
packages/sdk/src/mediaWithEntitlements.test.ts
packages/sdk/src/membershipManagement.test.ts
packages/sdk/src/persistenceStore.ts
packages/sdk/src/spaceWithEntitlements.test.ts
packages/sdk/src/sync-agent/user/user.test.ts
packages/sdk/src/withEntitilements.test.ts

chore: remove some usages of eslint disable

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 178f21e5a3f4850a95421b0bd11a4633b674e0a8
Date:   Tue Aug 6 00:19:07 2024 +0000
sdk-446a725-0.0.32

Release SDK 446a725

---

core/go.mod
go.work

Upgrading go/libs to see if it helps with #640

Upgrade go to 1.22.6

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit ce73978375fdf37379def587dd8b12138f18e2f2
Date:   Wed Aug 7 00:19:11 2024 +0000
sdk-162f0d6-0.0.33

Release SDK 162f0d6

---

core/node/rpc/sync/handler.go

Experiment: run Send from other thread

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9bb6ae15cbd7ecfca41b22c74475124c31f821d9
Date:   Thu Aug 8 00:19:03 2024 +0000
sdk-b1deec5-0.0.34

Release SDK b1deec5

---

core/Dockerfile
core/docker/full_node.supervisord.conf

Update docker to run river_node in combined mode

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 4b3c8b0c23ab9322b2fb0fdda33d30d836a688ca
Date:   Mon Aug 12 00:20:09 2024 +0000
sdk-b04638c-0.0.37

Release SDK b04638c

---

packages/web3/src/entitlement.ts

refactor(sdk): refactor entitlement data ABI encoding and decoding

---

scripts/start_dev.sh

Now that xchain is merges into the stream node no longer need to start it with dev scripts

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9a12e92ce83e2ec84ee97227b71d4c8b0b287b4e
Date:   Tue Aug 13 00:20:19 2024 +0000
sdk-de59a86-0.0.38

Release SDK de59a86

---

core/node/rpc/create_stream.go
core/node/rules/can_create_stream.go
core/node/rules/rule_builder_cs.go

Remove deprecated code from create_stream

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e6cb9aaa83ff58262a9ca4140be5566122926c6e
Date:   Wed Aug 14 00:19:52 2024 +0000
sdk-8ba36a6-0.0.39

Release SDK 8ba36a6

---

packages/playground/vite.config.ts

This is conflicting with other apps and I'd like to be able to run everything all at once. If you a suggestion for a better number I'm all ears.

Change playground development port

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9147333cb9f9cbd450bff7dd9a180c9b5e0a1d07
Date:   Thu Aug 15 00:20:34 2024 +0000
sdk-c46e439-0.0.40

Release SDK c46e439

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 54865f717529bbb5317f067c17dd776ad3c47386
Date:   Fri Aug 16 00:19:17 2024 +0000
sdk-14e678e-0.0.41

Release SDK 14e678e

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit d1f1402c6df44daf921a1494249fe4bd60b32495
Date:   Sat Aug 17 00:18:58 2024 +0000
sdk-231aa1c-0.0.42

Release SDK 231aa1c

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit d288a6c348f428c3678eebdc4f0f195e29268c53
Date:   Sun Aug 18 00:20:58 2024 +0000
sdk-91da48a-0.0.43

Release SDK 91da48a

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 678961f0d2155830da9897c39c983afe7b988d0c
Date:   Mon Aug 19 00:19:52 2024 +0000
sdk-8f5c8be-0.0.44

Release SDK 8f5c8be

---

.coderabbit.yaml

to stop code rabbit and dependabot from arguing with each other

update coderabbit to not run on the package.json file

---

packages/stream-metadata/src/node.ts
packages/stream-metadata/src/routes/spaceImage.ts

Wrote -ve tests and found that additional context in the logs will be useful for debugging. Added the log entries for error response. Tests will be in separate PR.

[stream-metadata] additional logging for invalid spaceAddress

---

packages/stream-metadata/src/node.ts

this change was removed in some PR. In my tests, I want to pass the test-configured server instance as an arg before the tests start. Putting the changes back.

[stream-metadata] pass server instance as an arg for testability

---

core/Dockerfile

Add curl to River Node docker container

---

contracts/deployments/alpha/base/addresses/entitlementDataQueryable.json
contracts/deployments/omega/base/addresses/entitlementDataQueryable.json
contracts/deployments/omega/base/addresses/entitlementDataQueryableFacet.json

https://app.llama.xyz/orgs/river/base/actions/93

add entitlement data queryable facet

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 4a1089301c8d6b59f65d42bbee2135af60c7c406
Date:   Thu Aug 22 00:19:36 2024 +0000
sdk-70065b2-0.0.46

Release SDK 70065b2

---

packages/sdk/src/sync-agent/spaces/models/channel.ts
packages/sdk/src/sync-agent/spaces/spaces.test.ts
packages/stream-metadata/src/environment.ts
packages/stream-metadata/src/logger.ts

pulling out minor code cleanups from my test pr.

minor code cleanups - pino types, env config, space image

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e6518a37ac51c6b0b0d933d60c68ece02e12c742
Date:   Fri Aug 23 00:19:22 2024 +0000
sdk-38424ca-0.0.47

Release SDK 38424ca

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e659c63fe44e937a7c0957a8a92b681c94797697
Date:   Sat Aug 24 00:19:06 2024 +0000
sdk-a9f2e75-0.0.48

Release SDK a9f2e75

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 1bb191959c92bea9433f667c481305c0b8bfe0a0
Date:   Sun Aug 25 00:21:23 2024 +0000
sdk-55eaa0e-0.0.49

Release SDK 55eaa0e

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 4a88491284768fb5e1bff45fe0909b0530cf0e3b
Date:   Tue Aug 27 00:20:12 2024 +0000
sdk-b195135-0.0.50

Release SDK b195135

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 11fd807d022b8c3831fed0f8289b7cab2fceabab
Date:   Wed Aug 28 00:20:14 2024 +0000
sdk-ebcdf9a-0.0.51

Release SDK ebcdf9a

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit c9a4e8e8fba53e2c5446cc9daaf0105c8f70cc07
Date:   Thu Aug 29 00:21:42 2024 +0000
sdk-b0fb141-0.0.52

Release SDK b0fb141

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8456566c1237e7a442b45fd6452f54962444df03
Date:   Sat Aug 31 00:20:21 2024 +0000
sdk-15574b3-0.0.53

Release SDK 15574b3

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 15a02dbf06bd3a391cc782b64de53bb42585ce59
Date:   Mon Sep 2 00:21:02 2024 +0000
sdk-adf1a07-0.0.54

Release SDK adf1a07

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2093aab890674fd65b97a0b5271c54fa0221fe7b
Date:   Tue Sep 3 00:20:04 2024 +0000
sdk-8fbc755-0.0.55

Release SDK 8fbc755

---

contracts/deployments/gamma/base/addresses/membershipFacet.json
contracts/deployments/omega/base/addresses/membershipFacet.json
contracts/makefile
contracts/src/spaces/facets/membership/MembershipBase.sol
contracts/src/spaces/facets/membership/MembershipFacet.sol
contracts/src/spaces/facets/membership/MembershipStorage.sol
contracts/test/spaces/membership/unit/MembershipJoinSpace.t.sol
contracts/test/spaces/prepay/PrepayFacet.t.sol

PROPOSAL ON TESTNET: https://testnets.llama.xyz/orgs/river/base-sepolia/actions/170
PROPOSAL ON MAINNET: https://app.llama.xyz/orgs/river/base/actions/101

fix(contracts): fixes price slippage

---

packages/playground/src/components/blocks/channels.tsx
packages/playground/src/components/dialog/env-switcher.tsx
packages/playground/src/routes/auth.tsx
packages/playground/src/routes/index.tsx
packages/playground/src/routes/layout.tsx
packages/playground/src/routes/root.tsx
packages/playground/src/routes/t/channel.tsx
packages/playground/src/routes/t/layout.tsx
packages/playground/src/routes/t/space.tsx
packages/react-sdk/src/useRiverConnection.ts

Playground now support `/t/:spaceId/:channelId` path
This PR also add support to login using bearer token only, without the need for metamask.

playground: move ids to url & allow login without metamask

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 69cb5ee92010153ec078a912fdd88f8ad9038fbd
Date:   Wed Sep 4 00:20:15 2024 +0000
sdk-d3ae9cf-0.0.56

Release SDK d3ae9cf

---

core/node/rules/can_add_event.go

To 100, want something large enough that we don’t have to worry about the limit for a while

Change max number of pins allowed per stream

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f371534f5d00e4040d31b93f9c13eb328a3fc3de
Date:   Thu Sep 5 00:20:02 2024 +0000
sdk-3df1ee7-0.0.57

Release SDK 3df1ee7

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit a42f1842301b14f20bf4efd0153a0fc4d344cb21
Date:   Fri Sep 6 00:20:44 2024 +0000
sdk-0d78f1d-0.0.58

Release SDK 0d78f1d

---

contracts/src/spaces/facets/Entitled.sol
contracts/src/spaces/facets/entitlements/EntitlementsManager.sol
contracts/src/spaces/facets/entitlements/EntitlementsManagerBase.sol
contracts/src/spaces/facets/entitlements/EntitlementsManagerStorage.sol
contracts/src/spaces/facets/entitlements/IEntitlementsManager.sol

Optimized function parameters by changing from `memory` to `calldata` for reduced gas usage. Improved loop initialization and increment operations for better performance and readability.

perf(contract): refactor `EntitlementsManager` and `Entitled`

---

packages/web3/src/entitlement.test.ts
packages/web3/src/entitlement.ts

Also, fix / build out error tests.

Fix bug in threshold validation for typescript entitlements check

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 598da0579888f4b3166d29205b77f488bc4968fa
Date:   Sat Sep 7 00:20:00 2024 +0000
sdk-78a8262-0.0.59

Release SDK 78a8262

---

packages/sdk/src/sync-agent/members/members.ts

Keep cache up to date, never flush it, and we weren’t always updating existing models

Fix bugs in sync agent members

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 7d57828f062a4a2e9d21aace08bab36a64403a70
Date:   Sun Sep 8 00:22:22 2024 +0000
sdk-cb9179e-0.0.60

Release SDK cb9179e

---

packages/sdk/src/sync-agent/spaces/models/channel.ts
packages/sdk/src/sync-agent/spaces/models/space.ts

SyncAgent: Update load priority of spaces and channels

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 548758bd89d534679fb9ec47ce5a9ebeea58c643
Date:   Mon Sep 9 00:21:32 2024 +0000
sdk-7f445a9-0.0.61

Release SDK 7f445a9

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 6f2892ba5bd1e992b95bbf821472113da594584a
Date:   Wed Sep 11 00:20:24 2024 +0000
sdk-72bd18c-0.0.62

Release SDK 72bd18c

---

core/node/crypto/chain_txpool.go

We are experiencing a nonce issues where the node is unable to submit a transaction because the nonce is too old. This can be caused by the river chain rpc node lagging behind when the nonce was fetched to assemble a previous transaction.
This PR contains 2 changes to address this issue:
- detect the outdated nonce and retry to submit the tx with the latest nonce. This will break the current loop that keeps on trying to submit the tx with an outdated nonce.
- the pending tx pool can now deal with a tx that was successfully submitted with an outdated nonce. This can happen when it was submitted at the time the chain rpc node was behind the canonical chain. These outdated tx are silently dropped but the pending tx pool kept on trying to retrieve the receipt for them. With this change if the …

core/node/crypto: refetch tx nonce in case chain rpc node reports nonce issues

---

packages/playground/src/components/dialog/env-switcher.tsx

Playground: dynamically generate environment switcher

---

contracts/deployments/omega/base/addresses/channels.json
contracts/deployments/omega/base/addresses/channelsFacet.json

PRODUCTION PROPOSALS: https://app.llama.xyz/orgs/river/base/actions/117

chore(contract) update channels facet addresses on omega

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit aeb76056197dddb673c6e7e1fb94e8978193bffe
Date:   Thu Sep 12 00:21:29 2024 +0000
sdk-5152d49-0.0.63

Release SDK 5152d49

---

.github/workflows/Bytecode_diff_report.yml
.github/workflows/Network_diff_upgrade.yml
scripts/bytecode-diff/scripts/upgrade-facets.sh

NET-85: update ci for omega bytecode diff report pipeline
- Puts gamma report on daily cron
- Omega report on once a week (Monday) cron prior to Omega release (Tuesday)
Requisite secrets have been added to github action repo.

NET-85 omega bytecode diff report pipeline 

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 5ec8b959fd59b1d4ffb0136bcdd2a8a580162b3e
Date:   Fri Sep 13 00:20:48 2024 +0000
sdk-12e2a2b-0.0.64

Release SDK 12e2a2b

---

contracts/deployments/alpha/base/addresses/channels.json
contracts/deployments/gamma/base/addresses/channelsFacet.json
contracts/deployments/gamma/base/addresses/referralsFacet.json
contracts/deployments/gamma/base/addresses/rolesFacet.json
contracts/src/spaces/facets/Permissions.sol
contracts/src/spaces/facets/channels/Channels.sol
contracts/src/spaces/facets/referrals/ReferralsFacet.sol
contracts/src/spaces/facets/roles/Roles.sol
contracts/test/spaces/architect/Architect.t.sol

TESTNET PROPOSAL: https://testnets.llama.xyz/orgs/river/base-sepolia/actions/197

fix(contract) permission names to match against actual keys

---

packages/stream-metadata/src/riverStreamRpcClient.ts

After a chat with Kerem I decided to look at the code, and sure enough, there is a "leak". The earlier caching code was only partially removed, and the decoded content was being kept in memory.
While at it I added code to remove the rpcClient from the mapping on error to avoid getting into a state where a bad client is a zombie and degrades the service.

Fix memory leak

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0092df8a9268cf9d6b28a43a077a44017b4321a3
Date:   Sat Sep 14 00:20:24 2024 +0000
sdk-6876b34-0.0.65

Release SDK 6876b34

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit ea7a2a7fa19ba7a77aa45400204072c55df8f03b
Date:   Mon Sep 16 00:22:01 2024 +0000
sdk-4024850-0.0.66

Release SDK 4024850

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 42bf7399750b63cfbc3e4fa1267a25afba4ac0bf
Date:   Tue Sep 17 00:18:43 2024 +0000
sdk-7b5d026-0.0.67

Release SDK 7b5d026

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e77bd0d8935897c6e6c67718d9a1a3b8e4abaca5
Date:   Wed Sep 18 00:21:08 2024 +0000
sdk-ffbc3c0-0.0.68

Release SDK ffbc3c0

---

core/docker/run.sh

fixes regression from: https://github.com/river-build/river/pull/1088

fixed dockerfile run.sh

---

packages/stream-metadata/src/routes/spaceMemberMetadata.ts
packages/stream-metadata/tests/integration/spaceMemberMetadata.test.ts

I couldnt run the test locally, so lets use the CI 😁

stream-metadata: add tests for space member metadata

---

packages/stream-metadata/src/environment.ts
packages/stream-metadata/src/logger.ts
packages/stream-metadata/src/node.ts
packages/stream-metadata/src/tracer.ts

for better logging and observability

all stream metadata service logs should emit the commit hash

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9a863b9838d06ea1a3d72bf862f381b94ea1710d
Date:   Thu Sep 19 00:21:07 2024 +0000
sdk-0dd540e-0.0.69

Release SDK 0dd540e

---

foundry.toml

Add lib back to foundry.toml

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 5596b6d5064706971716a1a3d166aac06478b4b3
Date:   Fri Sep 20 00:21:41 2024 +0000
sdk-4df389b-0.0.70

Release SDK 4df389b

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 45cf8b699d441d6dcc86cedde1dcad77daccd9ed
Date:   Sat Sep 21 00:20:50 2024 +0000
sdk-6c72071-0.0.71

Release SDK 6c72071

---

contracts/test/river/token/base/RiverBase.t.sol

Renamed test functions to indicate fuzz testing and replaced assume checks with bound constraints for parameter values. This ensures more robust and dynamic testing by covering a broader range of input scenarios. Removed unnecessary `console.log` statements to clean up test output.

test(contract): refactor token tests with better fuzzing and bounds

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 45ed4d88f931eae046d42bf7dc59252ba03a8018
Date:   Sun Sep 22 00:23:12 2024 +0000
sdk-06cdaf3-0.0.72

Release SDK 06cdaf3

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit a34bbe6406e367bcae983f17a2cad7ff3ae33536
Date:   Mon Sep 23 00:22:17 2024 +0000
sdk-7abf76f-0.0.73

Release SDK 7abf76f

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8d94196e2a082361fe35045d79aefa4c68099aa8
Date:   Tue Sep 24 00:21:54 2024 +0000
sdk-300e801-0.0.74

Release SDK 300e801

---

core/cmd/list_roles.go
core/contracts/base/i_roles.go
core/contracts/types/role_data.go
core/node/auth/space_contract.go
core/node/auth/space_contract_v3.go
scripts/gen-river-node-bindings.sh

Note: before running the below example you must update your `env/omega/config.yaml` to use a base chain id of 5432, it's currently incorrectly set to the testnet id.
This PR adds a utility to list roles for a space to the stream node binary, using the space's stream id/
Query against HNT Prod town stream id, which I grabbed from our URL:
```
./env/omega/run.sh list-roles 10c87bb04477151743070b45a3426938128896ac5d0000000000000000000000
Roles for space (10c87bb04477151743070b45a3426938128896ac5d0000000000000000000000):
- id: "1"
name: Minter
disabled: false
permissions:
- JoinSpace
entitlements:
- entitlementtype: RuleEntitlement
ruleentitlement:
operations:
- optype: 1
index: 0
checkoperations:
- optype: 3
chainid: "8453"
contractaddress: 0x5d358dd95040a2c2005af0e21e589c3ef0a2500a …
```

Build CLI utility into app to query roles on a space

---

contracts/scripts/interactions/InteractSetDefaultUriLocalhost.s.sol
packages/sdk/src/spaceDapp.test.ts
packages/web3/src/v3/Space.ts
packages/web3/src/v3/SpaceDapp.ts
protocol/protocol.proto
scripts/deploy-contracts.sh

Include getters in the spaceDapp and add a spaceDapp test

Add script to set space uri on localhost

---

packages/playground/src/routes/index.tsx
packages/playground/src/routes/inspect/root.tsx

`/inspect`
Useful to check/confirm things.
There are tons of possibilities and things to polish, but that's a start.

playground: inspect ids and stream view

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit c2d16beae5318c1d46871615ec495cca521c8d1c
Date:   Thu Sep 26 00:21:20 2024 +0000
sdk-c224df3-0.0.75

Release SDK c224df3

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f68415412a9cd82cfeca48c99b83f6de3dc37613
Date:   Fri Sep 27 00:21:54 2024 +0000
sdk-31f80c7-0.0.76

Release SDK 31f80c7

---

contracts/scripts/deployments/diamonds/DeploySpace.s.sol

Fix bug in alpha interaction script due to contract name change.

EntitlementGated is now SpaceEntitlementGated

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit ca5aa29807eb73e945c870dc4bc843dd7b0e9202
Date:   Sun Sep 29 00:23:58 2024 +0000
sdk-8727a4a-0.0.77

Release SDK 8727a4a

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8f7c546b0f5c80d81332e19e8f190e04bc6badc9
Date:   Mon Sep 30 00:22:34 2024 +0000
sdk-18da01e-0.0.78

Release SDK 18da01e

---

core/justfile
core/node/events/stream.go
core/node/events/stream_view.go
core/node/events/stream_view_test.go

Fix mb production for replicated scenarios; add notifications to ImportBlocks

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 712e59cb9014eb1a68512dd143a2dc3731b3feb5
Date:   Tue Oct 1 00:24:18 2024 +0000
sdk-4c21e73-0.0.79

Release SDK 4c21e73

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 362e4d55dfec8de29195c009d8e9806846abe1cd
Date:   Wed Oct 2 00:21:35 2024 +0000
sdk-b032fe3-0.0.80

Release SDK b032fe3

---

.github/workflows/ci.yml
packages/sdk/package.json

It's an experiment, too early to merge
Reverts river-build/river#1197

Revert "Increase runner configuration to ubuntu-x64-16core for all CI jobs"

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e8b245b8d46b9bea03417e045e2d313d1ed6a959
Date:   Thu Oct 3 00:21:40 2024 +0000
sdk-1ec463f-0.0.81

Release SDK 1ec463f

---

packages/stream-metadata/src/aws.ts
packages/stream-metadata/src/node.ts
packages/stream-metadata/src/routes/spaceRefresh.ts
packages/stream-metadata/src/routes/userBio.ts
packages/stream-metadata/src/routes/userRefresh.ts

stream-metadata: add cache for user bio

---

packages/stress/esbuild.config.mjs
packages/stress/package.json
packages/stress/src/demo.ts
packages/stress/src/mode/chat/chitChat.ts
packages/stress/src/mode/chat/joinChat.ts
packages/stress/src/mode/chat/kickoffChat.ts
packages/stress/src/mode/chat/root_chat.ts
packages/stress/src/mode/chat/statsReporter.ts
packages/stress/src/mode/chat/sumarizeChat.ts
packages/stress/src/mode/chat/updateProfile.ts
packages/stress/src/mode/slowchat/joinSlowChat.ts
packages/stress/src/mode/slowchat/root_slowchat.ts
packages/stress/src/mode/slowchat/slowChat.ts
packages/stress/src/mode/slowchat/waitForAllIn.ts
packages/stress/src/start.test.ts
packages/stress/src/start.ts
packages/stress/src/utils/logger.ts
packages/stress/src/utils/rpc-http2.ts
packages/stress/src/utils/storage.ts
packages/stress/src/utils/stressClient.ts
packages/stress/src/utils/systemInfo.ts
yarn.lock

Moving out from `dlog` since we need a better structured log solution.
Should close: TOWNS-12820

stress-tests: use pino for logs

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2d14598f4ad704b5202090a2f9c8ce98bcf4587b
Date:   Fri Oct 11 00:21:27 2024 +0000
sdk-9e569b4-0.0.82

Release SDK 9e569b4

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 39ce414b5854c3b411fe02ce78636ae4cd45f1af
Date:   Sat Oct 12 00:21:16 2024 +0000
sdk-1d842f4-0.0.83

Release SDK 1d842f4

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit abda095e74e6780d2380ae43efe340f828653a02
Date:   Mon Oct 14 00:22:54 2024 +0000
sdk-4e2c559-0.0.84

Release SDK 4e2c559

---

core/node/events/stream_view.go

Reverts river-build/river#1244
There is a similar check in ValidateNextEvent

Revert "Extend duplicate event check to include previous miniblocks"

---

packages/web3/src/entitlement.ts

Add the missing eth_balance checkOp and updating the default for eth_balance to be 0 instead

Add eth_balance checkOp

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 084110b40501921c16a828079ec40eb9df0c76dd
Date:   Tue Oct 15 00:22:02 2024 +0000
sdk-339c62a-0.0.85

Release SDK 339c62a

---

packages/stress/src/mode/chat/root_chat.ts
packages/stress/src/mode/chat/statsReporter.ts
packages/stress/src/mode/chat/summarizeChat.ts
packages/stress/src/utils/logger.ts

Closes: TOWNS-12692
I still need to play more with this to check if it's enough.
Usually, if something fails, it will be on the join chat step.

stress: logs to graph test results

---

packages/web3/src/Utils.ts
packages/web3/src/utils.test.ts

Add symetric spaceAddressFromSpaceId function in web3 utils

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0ff0e70700472435cb70cfdd6db7b1f30e375e22
Date:   Wed Oct 16 00:21:57 2024 +0000
sdk-d9ad9aa-0.0.86

Release SDK d9ad9aa

---

packages/stress/scripts/localhost_chat.sh
packages/stress/scripts/localhost_chat_setup.sh
packages/stress/scripts/localhost_demo.sh

stress-tests: use node env development in local scripts

---

.vscode/tasks.json
scripts/kill-all-local-dev.sh

start was leaving me in a state where i couldn’t ping any of the nodes.

Switch tasks.json to use just run instead of start

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 833c8f28793c2c5ba713fbd093343434087b0f75
Date:   Fri Oct 18 00:21:45 2024 +0000
sdk-02d6d00-0.0.87

Release SDK 02d6d00

---

packages/sdk/src/syncedStreamsExtension.ts
packages/sdk/src/types.ts

so that we can render data faster

Add ClientInitStatus flag for isHighPriorityDataLoaded

---

contracts/src/tokens/drop/DropFacet.sol
contracts/src/tokens/drop/DropFacetBase.sol
contracts/src/tokens/drop/IDropFacet.sol
contracts/test/airdrop/DropFacet.t.sol

Rearranged logic for claim condition checks and updates, improving gas efficiency and readability. Modified data types for timestamps and penalties, and used storage pointers to avoid unnecessary copies. Added unchecked blocks where safe to save on gas usage.

Refactor and optimize airdrop contracts

---

core/config/config.go
core/node/events/stream_cache.go
core/node/events/stream_sync_task.go
core/node/events/util_test.go
core/node/rpc/server.go

Configuration logic was tested locally.

Stream reconciliation to use workerpool with configurable size, defaulting to 8

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 10adac42298f24dcd8b4b1772124e107e86bccde
Date:   Wed Oct 23 00:21:55 2024 +0000
sdk-020ac1b-0.0.88

Release SDK 020ac1b

---

packages/stream-metadata/src/routes/userBio.ts
packages/stream-metadata/src/routes/userRefresh.ts

stream-metadata: tweak user bio cache

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f5e8111b020d35c32c18f80812b76dabf0e509ea
Date:   Sat Oct 26 00:21:27 2024 +0000
sdk-07a995c-0.0.89

Release SDK 07a995c

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2465e6efe1fa8c6f39acaed0bc35b98fbd5e0b81
Date:   Sun Oct 27 00:23:23 2024 +0000
sdk-7da9c96-0.0.90

Release SDK 7da9c96

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 14a83d39a3fef6022a434d2de3aaf7f67cc3861d
Date:   Mon Oct 28 00:23:09 2024 +0000
sdk-8f5c266-0.0.91

Release SDK 8f5c266

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit bbcd0bc6c8861822928823c64324269312822b12
Date:   Tue Oct 29 00:22:22 2024 +0000
sdk-3966e5f-0.0.92

Release SDK 3966e5f

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit a997518a93a561f8b1a77716e7bb0d3b752fdefa
Date:   Wed Oct 30 00:22:17 2024 +0000
sdk-b836b96-0.0.93

Release SDK b836b96

---

.github/workflows/ci.yml

dropped here: https://github.com/river-build/river/pull/706/files

Add stress test tests and demo back to ci

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 92c5d2eab153d5845b269be2e481424f4bbf02a9
Date:   Thu Oct 31 00:22:38 2024 +0000
sdk-b126347-0.0.94

Release SDK b126347

---

packages/sdk/src/sync-agent/gdms/models/gdm.ts

Stress test clients have lots of gdms

Remove verobse log

---

packages/stress/src/mode/chat/root_chat.ts
packages/stress/src/mode/common/common.ts

We have way too many streams, tests are failing to start.

Comment out the stress gdm generation

---

packages/sdk/src/rpcInterceptors.ts

I’m seeing BAD_STREAM_ID logs in the nodes after retrying, seems like the subsequent requests are empty?

Update the retry interceptor to clone the request before retrying

---

core/tools/migrate_db/river_migrate_db.go

Alternative partition creation method that might be faster.

Add --fast flag to `partition` command of db migrate tool

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit c2bd31a09d14bd6a71947d3d844d9dd6c396e42d
Date:   Fri Nov 1 00:23:56 2024 +0000
sdk-f30d036-0.0.95

Release SDK f30d036

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit b6e7e85d09ed339b764790263c883943c06fa2d2
Date:   Sat Nov 2 00:21:38 2024 +0000
sdk-69f756a-0.0.96

Release SDK 69f756a

---

core/node/registries/river_registry_contract.go

This is causing GetAllStreams to timeout.

Remove ctx timeout

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit c3985e331ea3ab9d45e95c0485b84c576d42024e
Date:   Sun Nov 3 00:23:44 2024 +0000
sdk-50ba734-0.0.97

Release SDK 50ba734

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 94e6592eb1bed9521e7339302160aea0b62430fa
Date:   Mon Nov 4 00:23:02 2024 +0000
sdk-827ff51-0.0.98

Release SDK 827ff51

---

core/node/scrub/stream_scrub_task.go

Fix scrub metrics collection to correctly calculate user boots, add membership check metric

---

.vscode/tasks.json

Otherwise you just relaunch the same thing again. (since we switched to just, re-running does not include a build with the new code)

Add build step to the node restart command in tasks.json

---

core/node/events/miniblock.go
core/node/events/minipool.go
core/node/events/stream.go
core/node/storage/pg_stream_store.go
core/node/storage/pg_stream_store_test.go
core/node/storage/storage.go

(also used in upcoming replication pr)

Unify miniblock writing into single functions with consistency checks

---

packages/sdk/src/spaceDapp.test.ts
packages/sdk/src/util.test.ts
packages/web3/src/v3/WalletLink.ts

Add new contract call to space dapp

SpaceDapp: WalletLink.unlinkCaller

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f56a8b3e1e15e9420a64c898b5b3b901a9f36454
Date:   Thu Nov 7 00:22:05 2024 +0000
sdk-4a5d2e7-0.0.99

Release SDK 4a5d2e7

---

packages/workers/merkle-worker/package.json
packages/workers/merkle-worker/src/createResponse.ts
packages/workers/merkle-worker/src/index.ts
packages/workers/merkle-worker/src/router.ts
packages/workers/merkle-worker/src/types.ts
packages/workers/merkle-worker/test/index.test.ts
packages/workers/merkle-worker/wrangler.toml

- add /api/merkle-proof route to generate a merkle proof from conditionId, merkleRoot, claim leaf data.
- update types for enhanced type coverage
- update wrangler.toml for deployment to gamma, omega
- update tests

Add proof generation route, tests

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f5f61b5585fb5a1a5eb4328cba7ce1ec58f1bfb2
Date:   Fri Nov 8 00:21:44 2024 +0000
sdk-100775f-0.0.100

Release SDK 100775f

---

contracts/scripts/deployments/facets/DeployDropFacet.s.sol
contracts/src/tokens/drop/DropFacet.sol
contracts/src/tokens/drop/DropFacetBase.sol
contracts/src/tokens/drop/DropStorage.sol
contracts/src/tokens/drop/IDropFacet.sol
contracts/test/airdrop/DropFacet.t.sol

* [Q-1] Lack of public view function to retrieve all claimable conditions
* [M-1] Incomplete eligibility reset for conditions (removed functionality to reset)

DropFacet Audit Fixes

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 25b1235c10784915f47596bcd464a9e5fcdd6987
Date:   Sat Nov 9 00:22:15 2024 +0000
sdk-e33861b-0.0.101

Release SDK e33861b

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit ffe39271743b2237303bfc1cb768a7eafbfbf752
Date:   Mon Nov 11 00:22:33 2024 +0000
sdk-11a3e03-0.0.102

Release SDK 11a3e03

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit fe885416d4c3b6217e495c2336fc726ec5cf7991
Date:   Tue Nov 12 00:21:52 2024 +0000
sdk-291d204-0.0.103

Release SDK 291d204

---

packages/sdk/src/mls/epochKeyStore.ts
packages/sdk/src/mls/groupStore.ts
packages/sdk/src/mls/index.ts
packages/sdk/src/mls/mlsStore.ts

- it doesn't yet cover all mls entities, @jakzale please adjust it as you see fit
- for simplicity, i created a new database for now, we could later discuss in which db this should go
- i have a few unrelated compilation errors
- there are quite a few call sites where we'll need to convert the code from sync to async, didn't want to make that change now

add very simple mls persistence layer

---

packages/react-sdk/.eslintrc.cjs
packages/react-sdk/package.json
packages/sdk/.eslintrc.json
packages/sdk/package.json
packages/sdk/src/check.ts
packages/sdk/src/sync-agent/river-connection/models/authStatus.ts
packages/sdk/src/syncedStreamsLoop.ts
yarn.lock

should close TOWNS-14591
I wish I could add this to `packages/eslint-config`, but we're not using it in the sdk package, doing this change results in a tons of file changed and I dont want to do this right now.

add eslint-tsdoc-plugin in sdk and react-sdk

---

core/config/config.go
core/node/crypto/blockchain.go
core/node/crypto/chain_txpool.go
core/node/crypto/chain_txpool_test.go
core/node/crypto/testutil.go

node/crypto: replace stuck transactions on node boot

---

contracts/test/base/registry/BaseRegistry.t.sol
contracts/test/base/registry/MainnetDelegation.t.sol
contracts/test/base/registry/RewardsDistribution.t.sol
contracts/test/base/registry/RewardsDistributionV2.t.sol

- refactor test contracts
- add redelegate and claim reward tests
- add `MainnetDelegation` unit tests.

test(contract): add `MainnetDelegation` unit tests

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0fb86eb79230ce639165d7ea704bca417921b9dd
Date:   Thu Nov 14 00:22:26 2024 +0000
sdk-9565e59-0.0.104

Release SDK 9565e59

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0aac9bc56d8ac3e706f055cf6524328e679074bb
Date:   Fri Nov 15 00:23:40 2024 +0000
sdk-cd96da4-0.0.105

Release SDK cd96da4

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 60d3481500cc40c65dccc393d94f62042767f69e
Date:   Sat Nov 16 00:23:11 2024 +0000
sdk-fc3a135-0.0.106

Release SDK fc3a135

---

lerna.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit df452686722e0e57990294b8c8d75d66808fed45
Date:   Sun Nov 17 00:24:39 2024 +0000
sdk-5dc72d6-0.0.107

Release SDK 5dc72d6

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0602ba4bd36b426f8630c4f14de72287bc0b9c19
Date:   Mon Nov 18 21:46:49 2024 +0000
sdk-14056e4-0.0.109

Release SDK 14056e4

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/mint.json
packages/docs/sdk/react-sdk/api/useChannel.mdx
packages/docs/sdk/react-sdk/api/useCreateDm.mdx
packages/docs/sdk/react-sdk/api/useCreateGdm.mdx
packages/docs/sdk/react-sdk/api/useDm.mdx
packages/docs/sdk/react-sdk/api/useGdm.mdx
packages/docs/sdk/react-sdk/api/useMember.mdx
packages/docs/sdk/react-sdk/api/useMemberList.mdx
packages/docs/sdk/react-sdk/api/useRiver.mdx
packages/docs/sdk/react-sdk/api/useSpace.mdx
packages/docs/sdk/react-sdk/api/useUserDms.mdx
packages/docs/sdk/react-sdk/api/useUserGdms.mdx
packages/docs/sdk/react-sdk/api/useUserSpaces.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit a9e2f1f67ad3af27b697f17773abf67814164277
Date:   Tue Nov 19 00:24:01 2024 +0000
sdk-1a6eea7-0.0.110
commit d8a0cc17af6df690e2d587135ec101b0dccdb83a
Date:   Tue Nov 19 00:23:51 2024 +0000
docs for version sdk-1a6eea7-

Release SDK 1a6eea7

---

contracts/src/spaces/facets/membership/join/MembershipJoin.sol

Renamed variables for clarity, refactored payment logic, and extracted common operations into a new helper function `_afterChargeForJoinSpace`. This improves code readability and maintainability.

refactor(contract): payment processing in `MembershipJoin`

---

packages/playground/package.json
packages/playground/vite.config.ts
yarn.lock

yarn dev was working fine, but yarn build had some issues with crypto polyfill
https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/92#issuecomment-2228168969

playground: fix build

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit d3e1c1315919d10b9095a4ab0d3eef18f272ec2c
Date:   Wed Nov 20 00:23:47 2024 +0000
sdk-a49e744-0.0.111

Release SDK a49e744

---

packages/react-sdk/scripts/docgen/generate.ts

Doc gen is now syncing the entry points modules <> docs api folder.
If a function doesn't exist anymore, the doc api page should not exist as well.

docgen: prune mdx that arent used anymore

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 1a867d172491ce64886f666356444f3e5d9dc8cc
Date:   Sat Nov 23 00:23:32 2024 +0000
sdk-2324e9a-0.0.114

Release SDK 2324e9a

---

core/node/auth/auth_impl.go

We're seeing high base rpc calls in mainnet after adding channel scrubbing and expect that caching space memberships could reduce average expected rpc count per channel member by up to 1/3. This PR introduces that cache.

Add a cache for space memberships for auth checks

---

packages/playground/src/components/form/dm/create.tsx
packages/playground/src/routes/t/dashboard.tsx
packages/playground/src/routes/t/space-channels.tsx

Now if you login with a signer (ie metamask), you can create a dm in the playground

playground: create dm feature

---

packages/react-sdk/src/RiverSyncProvider.tsx
packages/react-sdk/src/useAgentConnection.ts
packages/react-sdk/src/useCreateChannel.ts
packages/react-sdk/src/useReactions.ts
packages/react-sdk/src/useRedact.ts
packages/react-sdk/src/useRiver.ts
packages/react-sdk/src/useScrollback.ts
packages/react-sdk/src/useSendReaction.ts
packages/react-sdk/src/useSpace.ts
packages/react-sdk/src/useSyncAgent.tsx
packages/react-sdk/src/useThreads.ts
packages/react-sdk/src/useTimeline.ts
packages/react-sdk/src/useUserDms.ts
packages/react-sdk/src/useUserGdms.ts
packages/react-sdk/src/useUserSpaces.ts

This PR adds a few examples and adds docs for timeline related hooks.

react-sdk(docs): add missing docs

---

packages/playground/src/routes/auth.tsx
packages/playground/src/routes/index.tsx
packages/playground/src/routes/layout.tsx
packages/playground/src/routes/root.tsx

playground: splash screen

---

packages/create-river-build-app/src/modules/clone-playground.ts

Clone from main can lead into a broken playground state
Npm publishes our packages once a day, but we can change the package and playground N times a day.
If someone gets playground from main but with outdated npm packages, playground will fail to build/be in a broken state.
In order to fix this, we need to get the playground from the latest sdk published tag.

create-river-build-app(playground): get latest sdk tag to clone

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/RiverSyncProvider.mdx
packages/docs/sdk/react-sdk/api/useAgentConnection.mdx
packages/docs/sdk/react-sdk/api/useCreateChannel.mdx
packages/docs/sdk/react-sdk/api/useReactions.mdx
packages/docs/sdk/react-sdk/api/useRedact.mdx
packages/docs/sdk/react-sdk/api/useRiver.mdx
packages/docs/sdk/react-sdk/api/useScrollback.mdx
packages/docs/sdk/react-sdk/api/useSendReaction.mdx
packages/docs/sdk/react-sdk/api/useSpace.mdx
packages/docs/sdk/react-sdk/api/useSyncAgent.mdx
packages/docs/sdk/react-sdk/api/useThreads.mdx
packages/docs/sdk/react-sdk/api/useTimeline.mdx
packages/docs/sdk/react-sdk/api/useUserDms.mdx
packages/docs/sdk/react-sdk/api/useUserGdms.mdx
packages/docs/sdk/react-sdk/api/useUserSpaces.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 752476a0e03a05f4fe8425fa881f8762298754f5
Date:   Wed Nov 27 00:24:35 2024 +0000
sdk-8cf549e-0.0.115
commit 0c54d56cba9cbf1cb001cec1cfd8e9ceeaa7d9af
Date:   Wed Nov 27 00:24:24 2024 +0000
docs for version sdk-8cf549e-

Release SDK 8cf549e

---

packages/jest.env.ts
packages/playground/package.json
packages/web3/package.json
yarn.lock

chore: update viem

---

core/config/config.go
core/env/local/common/common.yaml

Make using the migrated stream schema the default behavior

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useAgentConnection.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 65badd63c5867acf4283f2bf6cf77208844951dd
Date:   Thu Nov 28 00:24:36 2024 +0000
sdk-b22df64-0.0.116
commit b7d44e43985f011604ce503d4d2ed1218d937b04
Date:   Thu Nov 28 00:24:26 2024 +0000
docs for version sdk-b22df64-

Release SDK b22df64

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 665e15cd82e47a4932b8ca5146325654ab2a7bbb
Date:   Fri Nov 29 00:24:32 2024 +0000
sdk-3b52407-0.0.117

Release SDK 3b52407

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit f68c72d1aef01aee431c6e83e9150be5ae400693
Date:   Sat Nov 30 00:23:59 2024 +0000
sdk-82e13a6-0.0.118

Release SDK 82e13a6

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 0e2f43c2848a7814ae79f79f924891b5b4bf203e
Date:   Sun Dec 1 00:28:33 2024 +0000
sdk-42c0159-0.0.119

Release SDK 42c0159

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useAgentConnection.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 329c4ec14407840e18cc09f9407ca1e2439f6642
Date:   Mon Dec 2 00:26:01 2024 +0000
sdk-c7b309f-0.0.120
commit 25841f63e7eec8c0eff03fe06b4c67a3ba86f451
Date:   Mon Dec 2 00:25:50 2024 +0000
docs for version sdk-c7b309f-

Release SDK c7b309f

---

packages/sdk/src/client.ts

This is something I found a few weeks ago when I was looking at test instability  and didn't prioritize because it wasn't a root cause of the issue as far as I could tell, but seems like it could definitely cause errors.

ClientSDK Deduplicate init stream requests

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 961ee65cfa3f67e30bef6f51e4e83462b33696ed
Date:   Tue Dec 3 00:25:53 2024 +0000
sdk-0506656-0.0.121

Release SDK 0506656

---

contracts/deployments/omega/base/addresses/channelsFacet.json

This new facet has the changes from #1593

new updated channels facet on omega

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/mint.json
packages/docs/sdk/react-sdk/api/useRedact.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit bfc2d736dac78db016d0aef25e9ade8d8f26fb95
Date:   Thu Dec 5 00:25:04 2024 +0000
sdk-b5b2cb4-0.0.123
commit bf65db7b6d8f7f0f6497112d71be2ba39ac2d48a
Date:   Thu Dec 5 00:24:53 2024 +0000
docs for version sdk-b5b2cb4-

Release SDK b5b2cb4

---

core/node/crypto/chain_txpool.go

#1700 
Use the newly added getMethodName, used by client metrics, which populates the method name of the selector for all registered contracts, instead of the raw selector hex-encoded bytes.

[RIVER-1700] Update transaction pool metrics to use method_name

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useAdminRedact.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 7f0ca1f37e66ad5faf0ae8f3b13c7e3eff339c7c
Date:   Fri Dec 6 00:24:27 2024 +0000
sdk-5eacd90-0.0.124
commit b130f9381122c709d015241bfeb2d371741bc260
Date:   Fri Dec 6 00:24:17 2024 +0000
docs for version sdk-5eacd90-

Release SDK 5eacd90

---

packages/dlog/src/utils.ts
packages/stream-metadata/tests/testUtils.ts

add ts_jest env check to isTestEnv

---

packages/playground/src/routes/t/dashboard.tsx

tired of making mistakes in the scrollarea
skill issue hits hard 😔

playground: render all spaces/gdm/dm - remove scrollable area

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit fa64801283ca6bca7c7b13299627c1486cb4e459
Date:   Sun Dec 8 00:26:16 2024 +0000
sdk-d876d2f-0.0.125

Release SDK d876d2f

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 927ff99f4542113d5e12361b1a42313539880dc3
Date:   Mon Dec 9 00:25:18 2024 +0000
sdk-7558e76-0.0.126

Release SDK 7558e76

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e8d81e4762a525d1e7c22d85ed966b1f08d986b0
Date:   Tue Dec 10 14:20:55 2024 +0000
sdk-3bce347-0.0.127

Release SDK 3bce347

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2e6214c3847bfff11c99ec1f3a297891a669f1ad
Date:   Thu Dec 12 00:24:41 2024 +0000
sdk-ecefe23-0.0.129

Release SDK ecefe23

---

packages/sdk/src/tests/multi/riverAirdropDapp.test.ts
packages/sdk/src/tests/multi/spaceDapp.test.ts
packages/web3/src/v3/RiverAirdropDapp.ts

instead of https://github.com/river-build/river/pull/1805

Add the river points facet to the RiverAirdropDapp

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 142016d977285c0e272954f9a77b267c71bcea4b
Date:   Fri Dec 13 00:25:12 2024 +0000
sdk-78269d0-0.0.130

Release SDK 78269d0

---

contracts/test/airdrop/DropFacet.t.sol

It's failing on pull river: https://github.com/HereNotThere/harmony/actions/runs/12306977160/job/34358245738?pr=8596
not sure why, i commented it out in harmony, @john can you figure out why?

Comment out test_endToEnd_differentialTestingRoot

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 2b5c65bc5bd5a202908c567baaafa1d1ff82b2de
Date:   Sat Dec 14 00:24:15 2024 +0000
sdk-73aa5a4-0.0.131

Release SDK 73aa5a4

---

core/cmd/registry_cmd.go
core/env/local/common/common.yaml
core/node/registries/river_registry_contract.go

Due to the race between reading from channel and remaining task counter few last pages sometimes got ignored.

Fix GetPaginatedStreams not to potentially ignore last pages

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit eec4e364dad803028813069eee13d8ba439f33c0
Date:   Tue Dec 17 00:24:34 2024 +0000
sdk-55c2668-0.0.134

Release SDK 55c2668

---

contracts/scripts/interactions/InteractAlphaSparse.s.sol

until diff is updated to add new diamond and deployer contract impl IDiamondInitHelper interface.

Remove riverAirdrop in interactAlpha script 

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 7128434a77bfc79935a0ddf3419d6e2d2d469e93
Date:   Wed Dec 18 00:23:59 2024 +0000
sdk-6f57bad-0.0.135

Release SDK 6f57bad

---

contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol

Refactor staking and redelegation logic to use `call` for error handling. This ensures the contract can handle failures without reverting, improving system robustness. Changes include decoding responses and conditionally updating state based on success.

fix(contract): handle staking and redelegation failures gracefully

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 81bea4a613a802083074473e2d2b8206cc127603
Date:   Fri Dec 20 00:23:21 2024 +0000
sdk-96e7cb5-0.0.137

Release SDK 96e7cb5

---

packages/sdk/src/tests/multi/transactions_Tip.test.ts

These passed (thank god), just making sure the events show up in the right places for everyone.

Add tests for tipping derived events

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 6780bc932e0a64d6724ce2969e3a1f6de11ba2bd
Date:   Sat Dec 21 00:22:57 2024 +0000
sdk-fea5246-0.0.138

Release SDK fea5246

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8bb280683b23a03a37406e0b5ca53cf0480adc9f
Date:   Sun Dec 22 00:24:57 2024 +0000
sdk-6bd922b-0.0.139

Release SDK 6bd922b

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit da5657add4113e396da77a046a82e55af15b14da
Date:   Mon Dec 23 00:24:11 2024 +0000
sdk-487af77-0.0.140

Release SDK 487af77

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9113019fb4033155e955c86088c7bf1740b70650
Date:   Tue Dec 24 00:23:13 2024 +0000
sdk-0237264-0.0.141

Release SDK 0237264

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8dd98e480db56da7454df04e143bab393ba0a426
Date:   Sun Dec 29 00:25:17 2024 +0000
sdk-407a47b-0.0.142

Release SDK 407a47b

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8e0d062f02cb0f78585dbecc697d6a1957077aa6
Date:   Mon Dec 30 00:23:56 2024 +0000
sdk-d90d168-0.0.143

Release SDK d90d168

---

packages/sdk/src/streamStateView_Members.ts

There is a real bug here, but I don't know what it is. This is too noisy though, sorry for not killing it sooner.:wq

Remove noisy exception when parsing stream joins

---

packages/docs/sdk/react-sdk/api/useTimeline.mdx
packages/docs/sdk/react-sdk/getting-started.mdx
packages/playground/src/components/blocks/timeline.tsx
packages/react-sdk/src/useTimeline.ts
packages/sdk/src/sync-agent/timeline/models/threadStats.ts
packages/sdk/src/sync-agent/timeline/models/timeline-types.ts
packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts
packages/sdk/src/tests/multi/sync-agent/timeline.test.ts
packages/sdk/src/tests/testUtils.ts
packages/stress/src/mode/slowchat/slowChat.ts

Rename the timeline events to match data structures (river)

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit ecfd499c0f137c2388cfd9bc1cd02a69048f1209
Date:   Tue Dec 31 00:23:14 2024 +0000
sdk-8b9541f-0.0.144

Release SDK 8b9541f

---

packages/sdk/src/sync-agent/timeline/models/timeline-types.ts
packages/sdk/src/sync-agent/timeline/models/timelineEvent.ts

Tweaks to bring timeine code in line with harmony

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 1152bd9d2bb2d327d2bafd61cc2f03b0a13d9b0c
Date:   Wed Jan 1 00:25:13 2025 +0000
sdk-6517f0e-0.0.145

Release SDK 6517f0e

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 13c75cf4b56a8bcdca1f64f6172413bb1baff5c7
Date:   Thu Jan 2 00:22:56 2025 +0000
sdk-01e660c-0.0.146

Release SDK 01e660c

---

contracts/scripts/deployments/diamonds/DeployRiverRegistry.s.sol
contracts/scripts/interactions/InteractRiverAlphaSparse.s.sol

Fixes `InteractRiverAlphaSparse.s.sol` script for correctly cased facet names.

fix facet deployment script

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 26c2371838cff1c89ae3130520c168ca3b4b31ad
Date:   Fri Jan 3 00:23:10 2025 +0000
sdk-d150ea9-0.0.147

Release SDK d150ea9

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit e75612e48c1cfbc7fcb4522829201e8de5b80771
Date:   Sat Jan 4 00:22:50 2025 +0000
sdk-f0e1449-0.0.148

Release SDK f0e1449

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json
yarn.lock

commit 3bf8e7aa564b29f6a06e2bf9d670749ebe1fb1a7
Date:   Wed Jan 8 00:23:10 2025 +0000
sdk-a1fe18b-0.0.149

Release SDK a1fe18b

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit d29323a7e10737822bcd72203185dca76fd34e24
Date:   Thu Jan 9 00:23:19 2025 +0000
sdk-3a7d74d-0.0.150

Release SDK 3a7d74d

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 1f5fc620cdd2829fcf7df54e6772785df8864a5f
Date:   Fri Jan 10 00:23:50 2025 +0000
sdk-2fb1c02-0.0.151

Release SDK 2fb1c02

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json
yarn.lock

commit ee577caed1bcd85081a507fedbd0df2a811488b3
Date:   Sun Jan 12 00:25:11 2025 +0000
sdk-8918082-0.0.152

Release SDK 8918082

---

packages/sdk/src/tests/multi_ne/streamRpcClient.test.ts

it fails locally on my machine

Is this test even run?

---

packages/dlog/src/binary.ts
packages/sdk/src/sign.ts

I need to use it in the crypto package

Move bigIntToBytes to the utils (dlog) package

---

contracts/makefile
contracts/test/base/registry/NodeOperator.t.sol
contracts/test/base/registry/RewardsDistribution.t.sol
contracts/test/factory/partner/PartnerRegistrySetup.sol
contracts/test/factory/partner/registerPartner.t.sol
contracts/test/factory/partner/updatePartner.t.sol
contracts/test/river/registry/RiverRegistryBaseSetup.t.sol
contracts/test/river/registry/stream/StreamRegistry.t.sol
contracts/test/river/token/mainnet/AuthorizedClaimers.t.sol
contracts/test/spaces/membership/unit/MembershipJoinSpaceWithReferral.t.sol
contracts/test/spaces/referrals/Referrals.t.sol
contracts/test/spaces/referrals/registerReferral.t.sol
contracts/test/spaces/referrals/removeReferral.t.sol
contracts/test/spaces/referrals/updateReferral.t.sol
contracts/test/spaces/roles/Roles.t.sol
contracts/test/spaces/tipping/Tipping.t.sol

test(contract): enforce stricter assumptions in test cases

---

core/cmd/archive_cmd.go
core/cmd/dd_profiler.go
core/cmd/notification_service_cmd.go
core/cmd/run_cmd.go
core/node/events/stream.go
core/node/events/stream_view.go
core/node/events/stream_view_test.go
core/node/rpc/forwarder.go
core/node/rpc/get_last_miniblock_hash.go
core/node/rpc/get_stream.go
core/node/rpc/miniblock_scrub_test.go
core/node/storage/pg_stream_store_test.go

My local gopls service complains when parameters are unused. Here is a PR that fixes all oustanding issues for go code!

[CLEANUP] Fix all unused params in go code

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 8fff94d0a355a10a83faa380756b564061a9fbf9
Date:   Wed Jan 15 00:23:17 2025 +0000
sdk-25668d3-0.0.154

Release SDK 25668d3

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit cde076b7df4e77a5fd37cfee1f5206f28bb8cf8a
Date:   Thu Jan 16 00:23:06 2025 +0000
sdk-9799d5f-0.0.155

Release SDK 9799d5f

---

packages/encryption/src/base.ts
packages/encryption/src/decryptionExtensions.ts
packages/encryption/src/encryptionDevice.ts
packages/encryption/src/groupDecryption.ts
packages/encryption/src/groupEncryptionCrypto.ts
packages/encryption/src/tests/decryptionExtensions.test.ts
packages/sdk/src/client.ts
packages/sdk/src/tests/multi_ne/client.test.ts
packages/sdk/src/tests/multi_ne/clientCrypto.test.ts
packages/sdk/src/tests/multi_ne/deviceKeyMessage.test.ts
packages/sdk/src/tests/multi_ne/outboundGroupSession.test.ts
packages/stress/src/mode/chat/joinChat.ts
packages/stress/src/mode/chat/kickoffChat.ts
packages/stress/src/utils/stressClient.ts

make the device private, force everything through the same api

Group Encryption Refactor 1: Patch up crypto backend abstraction

---

packages/encryption/src/base.ts
packages/encryption/src/decryptionExtensions.ts
packages/encryption/src/groupDecryption.ts
packages/encryption/src/groupEncryption.ts
packages/encryption/src/groupEncryptionCrypto.ts
packages/encryption/src/olmLib.ts
packages/encryption/src/tests/decryptionExtensions.test.ts
packages/sdk/src/client.ts
packages/sdk/src/clientDecryptionExtensions.ts
packages/sdk/src/tests/multi_ne/client.test.ts
packages/sdk/src/tests/multi_ne/outboundGroupSession.test.ts
packages/sdk/src/tests/multi_ne/userInboxMessage.test.ts
protocol/protocol.proto

say the value was set to something
includes future proof logic to properly display "not supported"

Group Encryption Refactor 3: w/ Proto modifications: add option to pass different encryption algorithm

---

core/node/rpc/metrics_interceptor.go

Currently almost immediately after the timer is created its duration is observed without measuring the time it takes before the request is made. This change includes the request between the metrics are initialised and finalised giving actual data.

node: bugfix in grpc request metrics

---

scripts/kill-watches.sh

Update kill watches script

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit c18ac5f9f5d58cd721f371cfe6e46537cac7eb6c
Date:   Tue Jan 21 00:22:40 2025 +0000
sdk-58af724-0.0.157

Release SDK 58af724

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit 9737f61020df7dff87eecdc557854e3b220956a4
Date:   Wed Jan 22 00:23:04 2025 +0000
sdk-a40bdae-0.0.158

Release SDK a40bdae

---

packages/encryption/src/decryptionExtensions.ts
packages/encryption/src/groupEncryptionCrypto.ts
packages/encryption/src/olmLib.ts

Lost this logic when we transitioned from datatype to data version

Clean up the parsing algorithm for group encryption

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/RiverSyncProvider.mdx
packages/docs/sdk/react-sdk/api/connectRiver.mdx
packages/docs/sdk/react-sdk/api/connectRiverWithBearerToken.mdx
packages/docs/sdk/react-sdk/api/signAndConnect.mdx
packages/docs/sdk/react-sdk/api/useAgentConnection.mdx
packages/docs/sdk/react-sdk/api/useRiverAuthStatus.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
protocol/package.json

commit b2c16ff42fd3bfd49fe0c800fbbb92db0660757b
Date:   Sat Jan 25 00:22:10 2025 +0000
sdk-11441f0-0.0.159
commit 7e4b4dd6a2e5136dbaeeee2ae9513e3be3a9861f
Date:   Sat Jan 25 00:21:58 2025 +0000
docs for version sdk-11441f0-

Release SDK 11441f0

---

packages/encryption/README.md
packages/playground/src/routes/auth.tsx
packages/sdk/README.md

docs.river.build -> docs.towns.com
Fixes #2171

chore: update docs mention

---

packages/xchain-monitor/.env.example
packages/xchain-monitor/Dockerfile
packages/xchain-monitor/docker-compose.yml
packages/xchain-monitor/esbuild.config.mjs
packages/xchain-monitor/package.json
packages/xchain-monitor/src/environment.ts
packages/xchain-monitor/src/index.ts
yarn.lock

Copy deployment infra over from stream-metadata service:
- Dockerfile, docker-compose
- fix build dependencies
- Switch to esbuild for easier building

[RIVER-2187] Dockerize xchain-monitor service for deployment

---

packages/workers/merkle-worker/src/conditions/gamma_condition_id_1.json

Merkle root added for following claim values. From governance action: https://llama-testnet.river.build/orgs/river/base-sepolia/actions/297

Add new gamma condition id

---

packages/encryption/src/decryptionExtensions.ts

stop doing the expensive findIndex, just put them in their own queue and process them before doing the priority streams.
figured out we were adding thousands of empty solicitations then ticking through them, stopped doing that

Update handling of own key solicitations in the web

---

core/node/crypto/chain_txpool.go

For each transaction that is assembled through the generated abi bindings the node performs 2 rpc calls to determine the miner tip. At the moment there is no gas market on River chain and no need to ask the a suggested miner tip fee.
This PR sets a hard coded miner tip on River chain transactions. We can also make it an on-chain config setting but I don't think that is needed at the moment.

node: set a fixed miner tip for river chain transactions

---

packages/encryption/src/decryptionExtensions.ts
packages/encryption/src/tests/decryptionExtensions.test.ts
packages/sdk/src/client.ts
packages/sdk/src/clientDecryptionExtensions.ts
packages/sdk/src/tests/multi_ne/client.test.ts

group by stream id, sort stream ids by priority, do everything for the stream

Better priorities for decryption

---

packages/sdk/src/tests/multi_ne/client.test.ts

not sure how this every worked...

Fix wait for issues in client.test.ts

---

packages/stress/src/utils/stressClient.ts

the json wasn’t jsoning, shit was undefined and breaking

Fix stress tests

---

packages/sdk/src/syncedStreamsLoop.ts

I forgot to reset the inflight cookies, eventually things stop syncing

Fix bad state in sync streams loop

---

packages/encryption/src/decryptionExtensions.ts
packages/encryption/src/tests/decryptionExtensions.test.ts
packages/sdk/src/clientDecryptionExtensions.ts

make sure they never override the current high priority channel

Tweak the priority for recent encrypted messages

---

packages/sdk/src/client.ts
packages/sdk/src/syncedStreams.ts
packages/sdk/src/syncedStreamsLoop.ts
packages/sdk/src/tests/multi_ne/syncedStreams.test.ts

was 10ish millis on every stream load on my machine

small perf win, reduce number of times we convert bytes stream id to string

---

packages/encryption/src/decryptionExtensions.ts
packages/sdk/src/client.ts
packages/sdk/src/sign.ts
packages/sdk/src/streamStateView.ts
packages/sdk/src/syncedStreamsLoop.ts
packages/sdk/src/types.ts

key solicitations were failing unnecessairily

fix for verifying signatures on key solicitations that were in miniblocks

---

packages/encryption/src/encryptionDevice.ts
packages/encryption/src/groupEncryptionCrypto.ts
packages/stress/src/utils/stressClient.ts
protocol/payloads.proto

the json parsing was breaking because we use bigints and json sucks like that

Udpate export encryption device to use protobuf

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/mint.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 5b90eab427530ed9ae4f6b9a4604652611e7c209
Date:   Tue Feb 11 00:23:08 2025 +0000
sdk-74d48fc-0.0.161
commit 4642461c4715844f37a2ea686397e091a1142d4b
Date:   Tue Feb 11 00:22:55 2025 +0000
docs for version sdk-74d48fc-

Release SDK 74d48fc

---

packages/sdk/src/syncedStreamsLoop.ts

this 100% causes the Buffer Full exception, and it slows down the initial load a ton, but it seems to work better than modify sync
NOTE: we're still using modify sync to add streams that users join after sync starts, but i updated the queueing logic so that we never have more than 
one modify sync request in flight at any time.

SyncStreamsLoop - go back to subscribing to everything at once

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit fbd34ab1a46bb28f0afbfd6d96ff4a48aae2a1de
Date:   Wed Feb 12 00:23:13 2025 +0000
sdk-16c7c5b-0.0.163

Release SDK 16c7c5b

---

packages/sdk/src/sync-agent/river-connection/riverConnection.ts
packages/stress/src/start.ts
packages/stress/src/utils/stressClient.ts

For some reason the 4th process is just stalling out and not starting up any clients. Logs are not helpful, hopefully this gives us some insight.

Update logs to debug broken stress tests

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit fadeea988521f396070f4d41fbb436dcc983624d
Date:   Thu Feb 13 00:23:15 2025 +0000
sdk-899371f-0.0.164

Release SDK 899371f

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit c566710e2ba5a576a14f0e74f230f7ac7fc1bb03
Date:   Fri Feb 14 00:23:22 2025 +0000
sdk-88bf183-0.0.165

Release SDK 88bf183

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/deployments/gamma/base/addresses/multiInit.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 2faf0272159abe1bf37b563a99bbd648a2a865cc
Date:   Sat Feb 15 00:23:04 2025 +0000
sdk-4b28072-0.0.166
commit 93c2109c3010cafd8dbff15ee3f32d314a2e324c
Date:   Sat Feb 15 00:22:52 2025 +0000
deployments for version sdk-4b28072-

Release SDK 4b28072

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 7ba1fa55ab7ba2950bbef5543281812063623b14
Date:   Thu Feb 20 00:23:25 2025 +0000
sdk-da827cc-0.0.169

Release SDK da827cc

---

packages/sdk/src/tests/testUtils.ts
packages/sdk/src/tests/unit/testUtils.test.ts

we had some tests where people expect wait for to wait for a condition, make that work

Update waitfor to be more intuitive

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit bc31a7f85b6756ceaabe1529ca63f1f882eda1a1
Date:   Sat Feb 22 00:22:50 2025 +0000
sdk-346feb3-0.0.171

Release SDK 346feb3

---

README.md
core/xchain/README.md
scripts/install-protobuf-deps.sh

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit f426060b3972888ec9845f4303bf2c16d1451325
Date:   Sun Feb 23 00:24:50 2025 +0000
sdk-f681ce3-0.0.172

Release SDK f681ce3

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit d118d9cbab7a1ba6e5ade916817a6f902af933b7
Date:   Mon Feb 24 00:24:36 2025 +0000
sdk-fab52ad-0.0.173

Release SDK fab52ad

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 190a9f3ebde2fe1b293fdfd121a2cf5add691168
Date:   Tue Feb 25 00:23:47 2025 +0000
sdk-4f8fe1d-0.0.174

Release SDK 4f8fe1d

---

packages/sdk/src/sync-agent/river-connection/riverConnection.ts

seems like init user is throwing an error but it’s not getting caught… idk weird

Better logs for stress tests

---

package.json
packages/dlog/package.json
packages/encryption/package.json
packages/proto/package.json
packages/sdk/package.json
packages/stream-metadata/package.json
packages/stress/package.json
packages/web3/package.json
yarn.lock

https://vitest.dev/blog/vitest-3.html
No breaking changes for us

 chore: upgrade to vitest 3

---

core/node/authentication/testutil.go
core/node/crypto/sign.go
core/node/crypto/sign_test.go
core/node/crypto/utils.go
core/node/events/events.go
core/node/events/parsed_event.go
core/node/notifications/event_processor.go
core/node/rpc/service_test.go
core/node/rules/can_add_event.go

RiverHash => TownsHashForEvents.Hash

Refactor hash function to allow different prefixes for wrapped hash

---

contracts/src/river/registry/facets/stream/StreamRegistry.sol
contracts/src/river/registry/libraries/RegistryStorage.sol
contracts/test/river/registry/stream/StreamRegistry.t.sol

- Add tests for stream-node mapping and validate edge cases
- Refactor stream validation with reusable internal functions

perf(contract): optimize `StreamRegistry` again

---

scripts/bytecode-diff/utils/utils.go

Use time.Time types for accurate date comparison.

Update date comparison for s3 files

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit f312c999b26a834972b605fef9c14e245a54eaad
Date:   Wed Feb 26 00:23:29 2025 +0000
sdk-808871e-0.0.175

Release SDK 808871e

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/deployments/alpha/base/addresses/spaceFactoryInit.json
packages/generated/deployments/alpha/base/addresses/spaceProxyInitializer.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 3fe01b37793ae7dae904a5a23a3d5f742559ee0e
Date:   Thu Feb 27 00:23:48 2025 +0000
sdk-bab372a-0.0.176
commit 6a573eb8508f4b4259aa9ac2b8f98c225560ddd8
Date:   Thu Feb 27 00:23:35 2025 +0000
deployments for version sdk-bab372a-

Release SDK bab372a

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit f4d85383e3d8d57c629a3d9f9613d91a7293bbdd
Date:   Fri Feb 28 00:23:45 2025 +0000
sdk-77313f4-0.0.177

Release SDK 77313f4

---

packages/docs/mint.json
packages/docs/towns-token/claiming.mdx
packages/docs/towns-token/staking.mdx

staking docs, update claim docs

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 00a8b1708a6dec5b643b4287d47aaf754fa27a99
Date:   Sat Mar 1 00:25:45 2025 +0000
sdk-43d6db3-0.0.178

Release SDK 43d6db3

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit ad2a5fe44e14d49439ec7e9fe27054c498b379ba
Date:   Sun Mar 2 00:25:10 2025 +0000
sdk-7ec3857-0.0.179

Release SDK 7ec3857

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit cd90faa0a8b4c18bc6e5511045d6a24b0c618ec9
Date:   Mon Mar 3 00:24:49 2025 +0000
sdk-24feada-0.0.180

Release SDK 24feada

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit dac98c78f545c84f84c48fcdbfd55c5db50c66cf
Date:   Tue Mar 4 00:24:01 2025 +0000
sdk-b0c1be0-0.0.181

Release SDK b0c1be0

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 72db3cc85025f1fcc7a894205f60a96759343d4d
Date:   Tue Mar 4 21:41:57 2025 +0000
sdk-9ab7cc3-0.0.182

Release SDK 9ab7cc3

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 39dbe857c0143f23f472bc94ad8cb18f04546371
Date:   Tue Mar 4 22:58:56 2025 +0000
sdk-8f726ea-0.0.183

Release SDK 8f726ea

---

core/node/events/miniblock_job.go

introduced in the previous refactoring

Fix minor data race in mb production

---

.github/workflows/Bytecode_diff_report.yml
.github/workflows/Publish_npm_packages.yml

this got reverted when we reverted the artifacts pr

Change FOUNDRY_VERSION on bytecode differe and npm publish scripts to stable

---

contracts/package.json

make all deletes the forge build and we don't need to do that every time

Update the yarn build command for contracts to make install && make build

---

core/node/rpc/repl_mc_norace_test.go

Reverts towns-protocol/towns#2517

Revert "Remove flaky test skip condition from 100x100 test in repl_mc_norace_test.go"

---

.gitattributes

this should clean up the diffs when we check in all this generated code

Add .gitattributes with linguist-generated=true for packages/generated/dev

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit f8736a3d54b85488bd0391733a791ce1db77c710
Date:   Thu Mar 6 00:24:07 2025 +0000
sdk-352bfb7-0.0.185

Release SDK 352bfb7

---

packages/docs/run/contracts.mdx
packages/docs/run/node-operator/system-requirements-installation.mdx

updates for clarity and accuracy

update rpc docs

---

packages/sdk/src/streamStateView_MemberMetadata.ts

will be used in the user lookup later

Make an NFT type

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useCreateDm.mdx
packages/docs/sdk/react-sdk/api/useCreateGdm.mdx
packages/docs/sdk/react-sdk/api/useSendMessage.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 57e039484f3eb1f2d8fd6cd03eb6f1b4f30fc6ce
Date:   Fri Mar 7 00:23:46 2025 +0000
sdk-c2c9e66-0.0.186
commit 203ee4ab573c3a4518cbf60a30caeb61af760883
Date:   Fri Mar 7 00:23:33 2025 +0000
docs for version sdk-c2c9e66-

Release SDK c2c9e66

---

contracts/src/factory/facets/wallet-link/libraries/SolanaUtils.sol
contracts/test/utils/SolanaUtils.t.sol
remappings.txt

Reorganized and optimized Base58 encoding logic using assembly for better performance. Introduced separate constants for Base58 alphabet lookup and simplified validation logic. Added a fuzz test to ensure Base58 validation accuracy.

perf(contract): refactor `SolanaUtils` for optimized Base58 encoding

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 449daf4784fa7f4a1f1e4e1928d182dd3aee93f8
Date:   Sun Mar 9 00:22:06 2025 +0000
sdk-40eefec-0.0.187

Release SDK 40eefec

---

packages/stream-metadata/src/riverStreamRpcClient.ts
packages/stream-metadata/src/routes/media.ts
packages/stream-metadata/src/routes/profileImage.ts
packages/stream-metadata/src/routes/spaceImage.ts
packages/stream-metadata/src/routes/spaceMemberMetadata.ts
packages/stream-metadata/src/routes/spaceMetadata.ts
packages/stream-metadata/src/routes/userBio.ts

we don't want to log these as errors since these are expected.

treating stream_not_found errors as expected errors

---

lerna.json
packages/create-river-build-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 8c4a8e30ab96fbc00daee5a072a7312b0a63aff0
Date:   Thu Mar 13 00:24:27 2025 +0000
sdk-cf54563-0.0.189

Release SDK cf54563

---

core/node/rpc/archive.go
core/node/rpc/otel.go
core/node/rpc/server.go

We weren't running s.initTracing() on archive nodes. This PR will help us run tracing

add tracing to archive nodes

---

core/node/auth/auth_impl.go

Reverts towns-protocol/towns#2589

Revert "Add logs to alpha in order to debug the entitlement failures for delegated wallets"

---

core/node/rpc/archiver.go
core/node/shared/stream_id.go

...for the purpose of easier analysis of large numbers of corrupt streams.

Add stream type label for archiver

---

packages/dlog/src/dlog.ts
packages/sdk/src/rpcInterceptors.ts
packages/sdk/src/tests/testDriver_testUtils.ts
packages/sdk/src/tests/testUtils.ts

**Description:**
This pull request addresses several minor issues in the codebase:
1. **Typographical Corrections:**
- Corrected the spelling of `retrieve` in `dlog.ts`.
- Fixed the spelling of `receive` in `testDriver_testUtils.ts`.
2. **Comment Improvements:**
- Enhanced clarity of comments in `rpcInterceptors.ts` and `testUtils.ts` for better understanding of the code functionality.
These changes aim to improve code readability and maintainability without affecting functionality.

fix typos and improve code comments

---

core/cmd/on_chain_config_cmd.go
core/node/crypto/config.go
core/node/crypto/config_test.go
core/node/nodes/stream_registry.go

Prevents allocation of new streams on blocked nodes.

Add node.blocklist on-chain setting

---

lerna.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
protocol/package.json

commit 804395ab43504052f65277d121a5f9a60dd76221
Date:   Fri Apr 4 15:39:07 2025 +0000
sdk-d556fece-0.0.190

Release SDK d556fece

---

lerna.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 9f3dd988be0524c4403fd45525b33123bcdf1bd2
Date:   Sat Apr 5 04:19:19 2025 +0000
sdk-5539bf32-0.0.192

Release SDK 5539bf32

---

lerna.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit f0b82ff473b24714b62fa4ae5461388d644d5d5f
Date:   Sun Apr 6 00:25:32 2025 +0000
sdk-89dbe36f-0.0.193

Release SDK 89dbe36f

---

lerna.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
yarn.lock

commit 466bbe35cd3a9e055c2d83667f414c46cc366fca
Date:   Mon Apr 7 00:24:44 2025 +0000
sdk-d5119980-0.0.194

Release SDK d5119980

---

lerna.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit ff546d307125e72e6ace668b9223b4f3cf4784b8
Date:   Tue Apr 8 00:23:58 2025 +0000
sdk-763fb5fc-0.0.195

Release SDK 763fb5fc

---

packages/metrics-discovery/Dockerfile
packages/stream-metadata/Dockerfile
packages/xchain-monitor/Dockerfile

I built locally and things are working properly by removing the copy of remappings.txt

remove copy of remappings on Dockerfiles

---

packages/sdk/src/client.ts

if we scrollback and we don't return anything (likely in the new setup) we get stuck on the same block in the useScrollbackToFocusItem

Add miniblock num to scrollback return value

---

scripts/deploy-base-contracts.sh
scripts/deploy-contracts.sh

some ci scenarios only need these contracts

chore: put base deployments into a separate script

---

packages/sdk/src/memberMetadata_DisplayNames.ts
packages/sdk/src/memberMetadata_Usernames.ts

stop hanging onto data structures that we don’t need

Simplify the member metadata

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit a5fddc624fe652fde74cd8dc96caacbfe84f30e9
Date:   Sun Apr 20 00:25:31 2025 +0000
sdk-5f90d3d2-0.0.197

Release SDK 5f90d3d2

---

packages/sdk/src/observable/observable.ts

send the prevValue along with the updates

Update observable api to mirror zustand

---

packages/react-sdk/src/useObservable.ts

otherwise it recreates it every frame and loops 🤦

Update useObservable to memo the callback function

---

packages/sdk/src/syncedStreamsExtension.ts
packages/sdk/src/syncedStreamsLoop.ts

relax the streaming logging, add loading logging

Update sync logging

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 2b420579c6e8172a4bdfc89c68e5eef296ba7c22
Date:   Mon Apr 21 00:25:03 2025 +0000
sdk-f2b9ba41-0.0.198

Release SDK f2b9ba41

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
yarn.lock

commit 4a48eae63886fe8bd3d144455c408e025e2510dd
Date:   Tue Apr 22 00:23:54 2025 +0000
sdk-992ca41f-0.0.199

Release SDK 992ca41f

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 79ed20230e8aa22a82b29824fae2fd1af8eb29c5
Date:   Wed Apr 23 00:23:55 2025 +0000
sdk-6a25c080-0.0.200

Release SDK 6a25c080

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 8a0f80fa66c8b89979a00bcb5c2a2e40e076f484
Date:   Thu Apr 24 00:23:56 2025 +0000
sdk-1e910a1b-0.0.201

Release SDK 1e910a1b

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1865df6f7d5fdc45bac14d0a15ae997d307b1af6
Date:   Fri Apr 25 00:24:05 2025 +0000
sdk-8ddeba0d-0.0.202

Release SDK 8ddeba0d

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit ab4aaa0f9005ae26b52a2d532eabf2e179dbbd5e
Date:   Sat Apr 26 00:23:36 2025 +0000
sdk-19e58d2a-0.0.203

Release SDK 19e58d2a

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3df4181acc9e3c42c43338e1bbc12ef9d5daa0ff
Date:   Sun Apr 27 00:25:48 2025 +0000
sdk-bccb45e1-0.0.204

Release SDK bccb45e1

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 7668a9e62cbd418410404ac72611eb9d7015dfd0
Date:   Mon Apr 28 00:25:12 2025 +0000
sdk-c49f5b86-0.0.205

Release SDK c49f5b86

---

packages/web3/src/v3/SpaceDapp.ts
packages/web3/tests/getJoinSpacePriceDetails.test.ts
packages/web3/tests/utils.ts

reduced call time on my machine (dev build) from about 1200ms -> 300ms

SpaceDapp: use multicall in getJoinSpacePriceDetails

---

scripts/deploy-base-contracts.sh
scripts/deploy-contracts.sh
scripts/start-local-basechain.sh
scripts/start-local-riverchain.sh

Simplified logic for setting block time and mining modes in local scripts. Made `BASE_EXECUTION_CLIENT` explicit for conditional automine and interval mining adjustments, improving clarity and maintainability.

refactor(script): simplify logic for block time and mining settings

---

packages/contracts/wagmi.config.ts
packages/subgraph/ponder.config.gamma.ts
packages/subgraph/ponder.config.ts
packages/subgraph/ponder.schema.ts
packages/subgraph/src/index.ts

On SpaceCreated, SpaceUpdated fetch all data from event args and on-chain data needed to populate SpaceInfo for a space.

NET-230 : Update subgraph schema, api to support SpaceInfo queries

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1fbd3b7a9c7b51255fec9ecfda7643e7c11f8d27
Date:   Wed Apr 30 00:24:08 2025 +0000
sdk-8eb0ee65-0.0.206

Release SDK 8eb0ee65

---

core/node/rpc/app_registry_test.go

I will circle back to fix this later.

Skip flaky app registry test

---

packages/stream-metadata/package.json
packages/stream-metadata/src/node.ts
packages/stream-metadata/src/routes/userTips.ts
packages/stream-metadata/tests/integration/spaceImage.test.ts
packages/stream-metadata/tests/integration/spaceMemberMetadata.test.ts
packages/stream-metadata/tests/integration/spaceMetadata.test.ts
packages/stream-metadata/tests/integration/userTips.test.ts

returns tips for any user, cached every 30 minutes
add test

Add user/{userid}/tips route to user metadata service

---

core/node/rpc/sync/client/local.go
core/node/rpc/sync/client/remote.go
core/node/rpc/sync/client/syncer_set.go

Reverts towns-protocol/towns#2929

Revert "Ping remote syncer before considering as an available fallback node"

---

packages/dlog/package.json
packages/dlog/src/utils.ts
packages/encryption/src/encryptionDelegate.ts
packages/sdk/src/rpcCommon.ts
packages/sdk/src/utils.ts
yarn.lock

chore: remove browser-or-node dependency

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 4c17eb8b0e21981befe5caf5e5c6f1e79ce23eb3
Date:   Fri May 2 00:24:14 2025 +0000
sdk-ed541f1d-0.0.208

Release SDK ed541f1d

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 8aa8a629ece460a2bb51f430da46db19e8861761
Date:   Sun May 4 00:26:54 2025 +0000
sdk-bd5a5079-0.0.210

Release SDK bd5a5079

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 9e08186c659ab48f2b790580eae3b4ea11799e75
Date:   Mon May 5 00:25:42 2025 +0000
sdk-606d833f-0.0.211

Release SDK 606d833f

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useScrollback.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 49f868c70499d44312bd62f12ccd4ade8a998e6f
Date:   Tue May 6 00:24:30 2025 +0000
sdk-041518ea-0.0.212
commit 713e3421a1c40df689f63b93ed619e022ee9b52a
Date:   Tue May 6 00:24:15 2025 +0000
docs for version sdk-041518ea-

Release SDK 041518ea

---

packages/web3/src/BaseContractShim.ts

lost when i refactored in https://github.com/towns-protocol/towns/pull/2969

web3: restore typed interface to BaseContractShim

---

packages/contracts/.cursor/rules/contracts.mdc
packages/contracts/README.md

Enhanced README and contracts docs to include staking, cross-chain delegation, and governance mechanisms. Updated deployment instructions and added clarity on Diamond Pattern implementation and storage guidelines.

docs(contract): update contracts documentation

---

.gitignore
packages/subgraph/README.md
packages/subgraph/generated/schema.graphql
packages/subgraph/package.json

Checkin schema.graphql file for subgraphs. In the future, this will be generated at build time in CI.

Checkin gql schema file for subgraph

---

packages/sdk/src/streamStateView_User.ts
packages/sdk/src/tests/multi/transactions_Tip.test.ts

?? wasn't ??ing, adds were taking presidence

Fix order of operations issue in sdk when adding tips

---

core/cmd/node_cmd.go

The specific metadata can be changed, anyone is welcome to modify this according to their needs.

Add cli 'node' command to dump a subset of streams assigned to a particular node

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1a73861cb6e9b4a55bbe563cf969ebf9084cd323
Date:   Fri May 9 00:25:03 2025 +0000
sdk-c6ecc64e-0.0.215

Release SDK c6ecc64e

---

README.md

docs: add deepwiki badge

---

.github/PULL_REQUEST_TEMPLATE.md
packages/contracts/.cursor/rules/contracts.mdc
packages/contracts/CONTRIBUTING.md
packages/contracts/README.md

Added a pull request template and detailed contribution guidelines, including coding standards, diamond pattern implementation, and facet development instructions.
Added PR template and contribution guidelines.

docs: add PR template and contribution guidelines

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit e127a3b5dd6a458de77453d2d7ca1127ae05f1e5
Date:   Sat May 10 00:23:32 2025 +0000
sdk-b2a4f706-0.0.216

Release SDK b2a4f706

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 6fc52470b1122676728c5087cbc3acde92caf84a
Date:   Sun May 11 00:26:26 2025 +0000
sdk-481a5f39-0.0.217

Release SDK 481a5f39

---

core/node/events/miniblock_job.go

Fix division by zero in mb candidate production slowdown check

---

packages/contracts/src/spaces/facets/executor/ExecutorFacet.sol
packages/contracts/src/spaces/facets/executor/IExecutor.sol

Reorganized the ExecutorFacet contract and IExecutor interface to improve code readability and maintainability. The changes include reordering methods to group them by functionality (write operations first, followed by read operations) and adding missing documentation.
- Reordered methods in ExecutorFacet to group write operations before read operations
- Moved the constructor after the modifier in ExecutorFacet for better code organization
- Added missing NatSpec documentation for internal methods in ExecutorFacet
- Improved documentation in IExecutor interface, particularly for the `hasAccess` method
- Added missing `setAllowance` method documentation in IExecutor
- Reordered method declarations in IExecutor to match the implementation order

refactor: reorganize ExecutorFacet methods and improve documentation

---

packages/contracts/.cursor/rules/contracts.mdc
packages/contracts/.cursor/rules/solidity-style-guide.mdc

Updated the glob pattern for Solidity rules and added a comprehensive Solidity style guide to standardize code formatting and structure across the project.
- Modified the glob pattern in contracts.mdc from `**/*.sol` to `*.sol` to adjust file matching scope
- Added a new solidity-style-guide.mdc file with detailed conventions for:
- Code layout (indentation, blank lines, line length)
- File structure and organization
- Import handling
- Function ordering by visibility
- Whitespace usage
- Control structure formatting
- Naming conventions for different Solidity elements

fix: update glob pattern of contracts cursor rules and add Solidity style guide rules

---

packages/contracts/.cursor/rules/contracts.mdc
packages/contracts/.cursor/rules/solidity-style-guide.mdc

Enhanced Solidity style guide with detailed naming conventions, NatSpec requirements, and new rule for pure library functions to improve consistency and readability.
- Updates to Solidity Style Guide:
- Expanded naming conventions:
- Added rules for matching contract/library names with filenames and avoiding unrelated contracts in a single file.
- Clarified naming conventions for private/internal functions and variables, as well as handling reserved word collisions.
- Added guidelines for NatSpec documentation:
- Public interfaces must include NatSpec comments, with examples provided for clarity.
- Updates to Contract Rules:
- Added a rule requiring library functions to be pure, ensuring no side effects in functional programming terms.
- Other Changes:
- Updated the description of the …

chore(contract): update Solidity style guide and coding rules

---

core/node/registries/river_registry_contract.go
core/node/shared/stream_id.go

Add context and fix incorrect error description.

improve several error messages

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
yarn.lock

commit 4cd82f22fada4b85f53fc67e08fae7f1b2e6ee69
Date:   Tue May 13 00:25:05 2025 +0000
sdk-b6c24fd2-0.0.219

Release SDK b6c24fd2

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit b821a1085b1c7ec45cf6012ebfdd96e16605ac39
Date:   Wed May 14 00:24:55 2025 +0000
sdk-4fffec5e-0.0.220

Release SDK 4fffec5e

---

.github/workflows/ci.yml
core/justfile

Stand up app registry in CI for e2e tests. This PR was validated against Miguel's WIP here: https://github.com/towns-protocol/towns/actions/runs/15028843995/job/42236228048?pr=3067

Add app registry service to CI for multinode e2e tests

---

core/tools/audit_db/stream_disk_usage.go

Provide a "histogram" command on the audit tool to fulfill @bas-vk 's request of generating a histogram by stream type. This cli command only considers miniblocks since we would not want to migrate candidates anyway, and ideally the minipools should be small.

"histogram" audit command

---

core/node/auth/auth_impl.go
core/node/rpc/add_event.go
core/node/rpc/create_stream.go

no code changes, just formatting

Save go files to fix formatting

---

core/node/auth/auth_impl.go
core/node/rpc/archiver_norace_test.go
core/node/rpc/archiver_test.go
core/node/rpc/create_media_stream.go
core/node/rpc/create_stream.go
core/node/rpc/notification_test.go
core/node/rpc/replicated_add.go
core/node/rpc/tester_test.go

Fix all lint issues identified in the 'Problems' tab of VS Code / Cursor

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 434064d9d81b57d63b362fbbd95f351b0c768f85
Date:   Fri May 16 00:25:07 2025 +0000
sdk-b7788fa9-0.0.222

Release SDK b7788fa9

---

packages/contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol
packages/contracts/src/base/registry/facets/distribution/v2/StakingRewards.sol

Refined inline comment formatting for better readability. Enhanced parameter descriptions in events and functions for improved clarity and precision.
- NatSpec in `RewardsDistribution`

docs(contract): improve formatting and param descriptions

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 4a8a09d4a7f1558978aa3923f2d2e20cc436ed17
Date:   Sat May 17 00:24:35 2025 +0000
sdk-1228a8c9-0.0.223

Release SDK 1228a8c9

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit a924e86a395f510c10b9abc80813d70202aaa1d4
Date:   Sun May 18 00:26:52 2025 +0000
sdk-4292c110-0.0.224

Release SDK 4292c110

---

packages/contracts/scripts/interactions/InteractAlphaSparse.s.sol
packages/contracts/scripts/interactions/InteractRiverAlphaSparse.s.sol

Pass relative dir which is whitelisted for r/w in foundry.toml

Fix interaction script

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 564d94bc6a22f3c5f7631442cddd734e7514a395
Date:   Tue May 20 00:25:55 2025 +0000
sdk-027d47cc-0.0.226

Release SDK 027d47cc

---

packages/contracts/package.json
yarn.lock

https://app.towns.com/messages/8843de0513cf436e2b9afc754e71f51dc80a35f141764d12d9535a77d9d62060#5b8fe75afd684abae3688acf53b3ef62b7bba901783a7988a2c92f13cf43b25e

chore: pin `account-abstraction` dev dependency

---

.github/workflows/ci.yml

lets see if it passes :)
my guess: leftover from mls-rs encryption

chore: remove rust toolchain from ci

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 6aece8b3fcbc2bc02068b298251e4a1656926d58
Date:   Wed May 21 00:25:44 2025 +0000
sdk-67496c79-0.0.227

Release SDK 67496c79

---

packages/subgraph/generated/schema.graphql
packages/subgraph/ponder.schema.ts
packages/subgraph/src/index.ts

add date timestamp off block timestamp to swap and swapRouterswap table

add createdAt timestamp off block timestamp

---

packages/web3/src/space-dapp/SpaceDapp.ts

Enables space delegation and provides access to node operator getters, both required for delegating staking
- Expose BaseRegistry
- Add space delegation helper

feat(dApp) add space delegation

---

packages/subgraph/generated/schema.graphql
packages/subgraph/ponder.schema.ts
packages/subgraph/src/index.ts

Fixes primary key violation error

Make subgraph pkey inserts idempotent

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 120cddb17c9c0f2c0fd2034d6b68aeab243c0c4e
Date:   Thu May 22 00:24:56 2025 +0000
sdk-b4553ed6-0.0.228

Release SDK b4553ed6

---

core/justfile
packages/contracts/scripts/interactions/InteractPostDeploy.s.sol
packages/contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol

The updates remove the on-chain operator registration from the base chain configuration process, shifting this logic into the post-deployment script. The post-deployment script now handles operator registration and approval. In the rewards distribution contract, operator validation is broadened to include both "Approved" and "Active" statuses.

refactor(contract): update operator status checks and rename related functions

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 217c4dfaa9d4697dab77ca0f299ba661e7a29952
Date:   Fri May 23 00:24:58 2025 +0000
sdk-acc404d1-0.0.229

Release SDK acc404d1

---

core/node/track_streams/metrics.go
core/node/track_streams/multi_sync_runner.go

Wire up metrics for the multi-syncer, and update them to track more relevant statistics

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit c2ebabef4e05320b7b466d0719646ebe2ef63016
Date:   Sat May 24 00:24:30 2025 +0000
sdk-54497ee3-0.0.230

Release SDK 54497ee3

---

packages/web3/src/BaseContractShim.ts
packages/web3/src/space/IMembershipShim.ts

so overriding function can access it

BaseContractShim: add address to executeCall override and fix passing value

---

core/cmd/stream_cmd.go
core/node/events/parsed_event.go

Update stream dump cli command to print parsed event info

---

core/node/rules/can_add_event.go

either the receipt or the solana receipt is valid, don’t try to log the receipt hash without checking first (ehem go… not like other languages haven’t solved this with the compiler).

Fix for panic in can_add_event

---

packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts

packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts
`memebers` - `members`
`messsage` - `message` x2

minor docstring fixups

---

core/env/local/multi/on_chain.csv
core/env/local/multi_ne/on_chain.csv

Long overdue change to run CI and local test in replicated configuration with factor 3

Increase stream replication factor from 1 to 3 in on_chain.csv files.

---

packages/sdk/src/client.ts
packages/sdk/src/stream.ts
packages/sdk/src/streamStateView.ts
packages/sdk/src/sync-agent/user/models/userInbox.ts
packages/sdk/src/sync-agent/user/models/userMemberships.ts
packages/sdk/src/sync-agent/user/models/userMetadata.ts
packages/sdk/src/sync-agent/user/models/userSettings.ts
packages/sdk/src/tags.ts
packages/sdk/src/tests/multi_ne/tags.test.ts
packages/sdk/src/tests/testUtils.ts

i ended up going a different way with this and no longer need the abstraction.

Remove the extra IStreamStateView interface

---

packages/contracts/src/spaces/facets/swap/SwapFacet.sol
packages/contracts/test/spaces/swap/SwapFacet.t.sol

- fix `_resolveSwapPoster` to correctly handle zero address poster when `collectPosterFeeToSpace` is false
- enhance test coverage for poster fee distribution scenarios

fix(contract): improve `SwapFacet` poster fee logic

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/docs/sdk/react-sdk/api/useReactions.mdx
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 2a36bd5cc1a95852b772a3aa6cb0aa1d6a3f0fa6
Date:   Sat May 31 00:24:54 2025 +0000
sdk-5ae061d9-0.0.233
commit d7287c189ea9ff243d71ecb4f87c1a3371351c38
Date:   Sat May 31 00:24:29 2025 +0000
docs for version sdk-5ae061d9-

Release SDK 5ae061d9

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit e9a17c45dd217b64ede2e0ab3b62c25ca1ebe5a4
Date:   Sun Jun 1 00:30:28 2025 +0000
sdk-f01053a4-0.0.234

Release SDK f01053a4

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 422f007efb8ebe509ffe585cc08d7f9c87d747b3
Date:   Mon Jun 2 00:27:00 2025 +0000
sdk-48ac3f1c-0.0.235

Release SDK 48ac3f1c

---

packages/sdk/src/tests/multi_ne/space.test.ts

lots of tests were grouped together
one test had a try catch around the whole thing which was eating the tests exceptions and messing up the error report

Improve the space.test.ts

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/deployments/omega/mainnet/addresses/utils/proxyBatchDelegation.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 58f22b3e4cf43d2d957529e48220b8998ff4afd5
Date:   Tue Jun 3 00:26:09 2025 +0000
sdk-596afe77-0.0.236
commit 2d75d2764caac772e63eaf37116f015106f7c46a
Date:   Tue Jun 3 00:25:41 2025 +0000
deployments for version sdk-596afe77-

Release SDK 596afe77

---

packages/docs/run/node-operator/system-requirements-installation.mdx

Update eth requirements for node operators.
- add min node requirements
- add alerting requirements

Update node operator docs for Eth requirements

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit bded33abf485748fc7a24b65a336fccbb99d929a
Date:   Wed Jun 4 00:25:44 2025 +0000
sdk-988d6372-0.0.237

Release SDK 988d6372

---

packages/sdk/src/syncedStream.ts
packages/sdk/src/tests/multi/sync-agent/syncAgent.test.ts

=== will just compare references

Fix snapshot hash equality check

---

package.json
packages/contracts/package.json
yarn.lock

update turbo to 2.5.4

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit af397fcae5a467f0814ac6397858aa85adfb0b60
Date:   Fri Jun 6 00:25:15 2025 +0000
sdk-a589c3b9-0.0.239

Release SDK a589c3b9

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 10716c7a93182aa60d42ae59265c45fa16660cf6
Date:   Sun Jun 8 00:27:59 2025 +0000
sdk-b01b7cba-0.0.240

Release SDK b01b7cba

---

packages/sdk/src/tests/multi_ne/gdms.test.ts

I updated the other one, missed this one. Need to wait for memberships to be confirmed in blocks

Update flaky test in gdms.test.ts

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 0da2aeb0eeeb344c6ac5ef5c4d137f68936d1c78
Date:   Tue Jun 10 00:25:43 2025 +0000
sdk-47383089-0.0.242

Release SDK 47383089

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 8f17f6f7a619532ed6e0e50687b9073d49cc8eb5
Date:   Thu Jun 12 00:25:23 2025 +0000
sdk-b889eace-0.0.244

Release SDK b889eace

---

packages/sdk/src/tests/multi_ne/space.test.ts

for flaky tests https://github.com/towns-protocol/towns/actions/runs/15616707715/job/43991261663
```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯
FAIL   multi_ne  src/tests/multi_ne/space.test.ts > spaceTests > spaceImage
AssertionError: expected undefined to be defined
❯ src/tests/multi_ne/space.test.ts:234:55
232|                 throw new Error('snapshot is not a space content')
233|             }
234|             expect(snapshot.content.value.spaceImage).toBeDefined()
|                                                       ^
235|             expect(snapshot.content.value.spaceImage?.data).toBeDefine…
236|         })
```

Update the space tests to wait for miniblocks before making snapshots

---

packages/stream-metadata/package.json
yarn.lock

Update axios here to unblock harmony syncpack PR that updates axios in there

chore: update axios

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 682c0c94458caec886bb045b06c6af9151b486fe
Date:   Sat Jun 14 00:24:51 2025 +0000
sdk-8b1dad3e-0.0.246

Release SDK 8b1dad3e

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit b27760ba539a2052d1893a5e45b84071acc9c9f6
Date:   Sun Jun 15 00:28:14 2025 +0000
sdk-bd5348b7-0.0.247

Release SDK bd5348b7

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 56fd2c8514a16c93c3eb4b96a28a33ab8e840715
Date:   Mon Jun 16 00:26:54 2025 +0000
sdk-727c8404-0.0.248

Release SDK 727c8404

---

packages/subgraph/package.json
yarn.lock

upgrade ponder v to 11.17 which features some indexing fixes. https://github.com/ponder-sh/ponder/releases

update ponder version to latest

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit ceb2522df32e93d5d95ea9f6d9f7792d50fa04cb
Date:   Tue Jun 17 00:25:43 2025 +0000
sdk-77a12969-0.0.249

Release SDK 77a12969

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/deployments/alpha/base/addresses/appRegistry.json
packages/generated/deployments/gamma/base/addresses/appRegistry.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 9466c44497800942f7a423e0c0272a2caa6ef01d
Date:   Wed Jun 18 00:25:42 2025 +0000
sdk-f8cb4ba4-0.0.250
commit 0c6ae9b041848fa321746eddebbeab81054d7a7d
Date:   Wed Jun 18 00:25:16 2025 +0000
deployments for version sdk-f8cb4ba4-

Release SDK f8cb4ba4

---

packages/sdk/src/observable/observable.ts
packages/sdk/src/observable/persistedObservable.ts

Add return value to setValue in observable

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 7f4c80a751d8e7d8c043ebfe36d3e018e1b67189
Date:   Thu Jun 19 00:25:54 2025 +0000
sdk-73fea33b-0.0.251

Release SDK 73fea33b

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 5964df7345c00dfa0c2681b4cd04140777e96dcb
Date:   Fri Jun 20 00:25:33 2025 +0000
sdk-fc3663ea-0.0.252

Release SDK fc3663ea

---

packages/sdk/src/observable/observableRecord.ts

Updates to observable record

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 5b687cbd26af3cdf380c3e909c49b0fb4352cd7c
Date:   Sat Jun 21 00:25:27 2025 +0000
sdk-83969731-0.0.253

Release SDK 83969731

---

packages/sdk/src/decryptionExtensions.ts
packages/sdk/src/observable/observable.ts
packages/sdk/src/observable/utils.ts
packages/sdk/src/streamStateView.ts
packages/sdk/src/streamStateView_ChannelMetadata.ts
packages/sdk/src/streamStateView_GDMChannel.ts
packages/sdk/src/streamStateView_Members.ts
packages/sdk/src/sync-agent/timeline/models/timeline-types.ts
packages/sdk/src/views/streams/gdmStreams.ts
packages/sdk/src/views/streams/streamMemberIds.ts
packages/sdk/src/views/streamsView.ts
packages/sdk/src/views/transforms/dmsAndGdmsTransform.ts
packages/sdk/src/views/transforms/membershipsTransform.ts
packages/sdk/src/views/transforms/spaceIdsTransform.ts

migrating the maze of react hooks in our towns client to the sdk

Observable work, spaceids, membership ids, dms and gdms

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 7c7eedeb938c78663bc892df4f505b909361517f
Date:   Mon Jun 23 00:27:19 2025 +0000
sdk-bbf2e949-0.0.255

Release SDK bbf2e949

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3bbbc9aa2748e77c7a1f3c9872111018951e7119
Date:   Tue Jun 24 00:26:55 2025 +0000
sdk-ca5a0130-0.0.256

Release SDK ca5a0130

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 2826690d274fb2b6468825799001f5d0caba54d4
Date:   Wed Jun 25 00:26:18 2025 +0000
sdk-a2ac93a3-0.0.257

Release SDK a2ac93a3

---

lerna.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit b4223ae20cca890f174f87df3a04bfe3f42e91cb
Date:   Thu Jun 26 00:26:06 2025 +0000
sdk-b37a4045-0.0.258

Release SDK b37a4045

---

packages/bot/src/bot.test.ts

Somehow its failing w/ timeout on CI. Since I dont want to block ppl on this, I'll skip it for now.
https://github.com/towns-protocol/towns/actions/runs/15891203689/job/44814591467?pr=3427

skip bot.onReply test

---

core/node/rules/can_create_stream.go
packages/bot/src/bot.test.ts
packages/sdk/src/tests/multi/botStreamCreation.test.ts

We would like to delay deploying the app registry contract to all production environments until we confirm that the contract operates as expected. Thus, we will disable the App Registry check on GDM and DM creation in order to not require the contract in all environments. 
This change should fix the nodes on alpha.

Remove app registry check on DM/GDM creation.

---

core/cmd/app_registry_cli_cmd.go

This file is mostly AI-generated, and is here in part as a stub that we can use to extend as necessary.

add a cli utility to interact with the app registry contract

---

.github/workflows/XChain_monitor_docker.yml

Build xchain monitor with shorter commit tag that corresponding with what is deployed from CI/CD.

build xchain-monitor with short commit sha tag

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit e8e169483da3f214a14c7defa192e79978a2a0dd
Date:   Fri Jun 27 00:26:35 2025 +0000
sdk-f499699b-0.0.259

Release SDK f499699b

---

packages/contracts/src/base/registry/facets/delegation/SpaceDelegationFacet.sol
packages/contracts/src/base/registry/facets/distribution/v2/IRewardsDistribution.sol
packages/contracts/src/base/registry/facets/distribution/v2/RewardsDistributionBase.sol
packages/contracts/src/base/registry/facets/distribution/v2/RewardsDistributionV2.sol
packages/contracts/src/base/registry/facets/distribution/v2/StakingRewards.sol
packages/contracts/test/base/registry/RewardsDistributionV2.t.sol
packages/contracts/test/base/registry/SpaceDelegation.t.sol

Refactors the staking rewards system to improve code organization, function naming clarity, and add defensive programming practices. Consolidates reward sweep logic into the `StakingRewards` library and enhances documentation for better maintainability.
- Moved reward accounting logic into `StakingRewards` library and updated import paths
- Renamed `sweepUnclaimedReward` to `transferReward` for clarity
- Added defensive checks for stake and commission consistency to prevent underflow
- Enhanced `claimReward` documentation with detailed usage scenarios
- Simplified revert logic using direct `.revertWith()` syntax
- Added helper functions for better reward management

refactor(contract): improve staking rewards with encapsulation and defensive checks

---

core/node/app_registry/service.go

I previously mis-ordered checking user stream app contract addresses and storing info in the db; we should store registration info as the last step of this rpc call.

Do not store app data in pg until the registration info is fully verified.

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 5b02375fcf6cd424b38133209a723cbe3f0f36cc
Date:   Sun Jun 29 00:29:12 2025 +0000
sdk-0d72faa8-0.0.261

Release SDK 0d72faa8

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 78d0b47dac3d777829f374f57546e6c4001919f6
Date:   Mon Jun 30 00:27:58 2025 +0000
sdk-6740b660-0.0.262

Release SDK 6740b660

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3eadd216e79fcb4f68079c7b3961ae160e332616
Date:   Tue Jul 1 00:29:10 2025 +0000
sdk-3bbd8bce-0.0.263

Release SDK 3bbd8bce

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 0ff21c0d1f9ee034fed75d9bcf5dccae7fe9817a
Date:   Wed Jul 2 00:26:03 2025 +0000
sdk-a27e7709-0.0.264

Release SDK a27e7709

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 59465c85618253d7912024faa00399e26d9c0ef6
Date:   Thu Jul 3 00:26:30 2025 +0000
sdk-86e0536b-0.0.265

Release SDK 86e0536b

---

packages/examples/bot-ask-poll/package.json
packages/examples/bot-quickstart/package.json
packages/examples/bot-thread-ai/package.json

[bot-examples] add `--watch` to tsx

---

packages/sdk/src/syncedStreamsLoop.ts

I believe I'm seeing these errors show up in datadog with error messages that are pretty obtuse. I'm trying to add a little more extra context to see if we can spot any particular trends around why this is happening.

Add some extra details to syncLoop errors to help us debug production issues

---

core/node/storage/CLAUDE.md

Add comprehensive documentation for the storage layer including:
- Core storage abstractions and PostgreSQL implementation patterns
- Transaction handling with retry logic and consistency guarantees
- Testing strategies and utilities
- Performance optimizations and query patterns
- Enforced stream constraints including miniblock sequencing rules

docs: Add CLAUDE.md for Towns storage layer

---

packages/sdk/src/decryptionExtensions.ts
packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts
packages/sdk/src/views/streams/unreadMarkersTransform.ts

keep priority of the priority queue and processing new sessions
run own key solicitations and 3 streams in parallel

Parallelize the decryption queue in decryptionExtensions

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit d1e457ee54550979ce569e34e9313c1a61e5e9d1
Date:   Sat Jul 5 00:25:04 2025 +0000
sdk-6b17d78e-0.0.267

Release SDK 6b17d78e

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit d12c8e4e93c7cbfffa729e0a71a296e5528df977
Date:   Sun Jul 6 00:28:47 2025 +0000
sdk-c0d8d785-0.0.268

Release SDK c0d8d785

---

packages/contracts/scripts/deployments/facets/DeployExecutorFacet.s.sol
packages/contracts/src/spaces/facets/account/AppAccountBase.sol
packages/contracts/src/spaces/facets/executor/ExecutorBase.sol
packages/contracts/src/spaces/facets/executor/ExecutorFacet.sol
packages/contracts/src/spaces/facets/executor/IExecutor.sol
packages/contracts/test/spaces/account/Executor.t.sol

Added `executionId` field to the Target struct to track execution context
- Implemented `_isTargetExecuting` helper function to check execution context
- Added `onExecution` external view function to the IExecutor interface for testing new system
- Removed unnecessary hook implementations from AppAccountBase
- Added comprehensive tests for the new execution context verification

feat: add tracking of execution id on target for proper nested executions

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 5c799cf50798d3638029a3d7c7584ba9eb9b893b
Date:   Tue Jul 8 00:26:50 2025 +0000
sdk-3ed7a266-0.0.270

Release SDK 3ed7a266

---

packages/bot/package.json
packages/bot/src/bot.ts
yarn.lock

So we can improve our compatibility with Cloudflare Workers, without the `nodejs-compat`. This will get us one step closer
Should close TOWNS-28937

[bot framework] using nanoevents instead of `node:events`

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/deployments/omega/base/addresses/appRegistry.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 5a7b17b3a818fec21578108a86882bb259bb1528
Date:   Wed Jul 9 00:26:56 2025 +0000
sdk-698f69c1-0.0.271
commit 6a9e1463ae069e714cd5b8350d45bec13279006f
Date:   Wed Jul 9 00:26:30 2025 +0000
deployments for version sdk-698f69c1-

Release SDK 698f69c1

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit edea1200e7d81bcf3a51e5d53b12b1e457d7b2ed
Date:   Thu Jul 10 00:26:58 2025 +0000
sdk-a2d43eb9-0.0.272

Release SDK a2d43eb9

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 55ff7fcca9faafd389a0ef28700c71d71a012f15
Date:   Fri Jul 11 00:26:51 2025 +0000
sdk-7e40793d-0.0.273

Release SDK 7e40793d

---

packages/docs/introduction/technical-whitepaper.mdx
packages/docs/mint.json

- Add technical-whitepaper.mdx to mint.json navigation under Learn section
- Ensures whitepaper is visible in documentation site
- Clean up Benefits section

docs: add technical whitepaper to navigation

---

CLAUDE.md

Add section outlining commit message best practices and explicitly stating that AI assistance should not be mentioned in commits.

docs: add git commit guidelines to CLAUDE.md

---

core/node/rpc/app_registry_norace_test.go

Skip TestBotConversationNoRace

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 111c7ae118489e7c4eaf9f24a21fb12746176079
Date:   Wed Jul 16 00:27:12 2025 +0000
sdk-1171c984-0.0.277

Release SDK 1171c984

---

packages/sdk/src/tests/multi/sync-agent/member-queue.test.ts
packages/sdk/src/tests/multi/sync-agent/syncAgents.test.ts
packages/sdk/src/tests/multi_ne/clientDecryptionExtensions.test.ts
packages/sdk/src/tests/testUtils.ts

i was hitting these up in lots of places, just make it 10 everywhere.

Increase default timeout of all waitFors to be 10 seconds

---

core/justfile

Currently all nodes on local environments are registered by the same operator. This isn't representative for live environments and causes log pollution with warnings. This change gives each River node instance its own unique operator when configuring an environment.
Before:
```
#streams  node                                         operator                                     status    url
0         0x9c6eDc5B6CEF353c2714F1108FC1FbCcFb5DA21a   0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266   2         https://localhost:5170
0         0xF306dd883fab1D6c7E47f1A2E827228e8755f31F   0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266   2         https://localhost:5171
0         0x1FD218cF6aebfac88939d3b80d9B297f47Aa79d0   0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266   2         https://localhost:5172
0 …
```

just: every node instance has its own unique operator

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit f464bb976dea63cfdba3b9a2fc5e689881bb7153
Date:   Thu Jul 17 00:27:29 2025 +0000
sdk-45fd2321-0.0.278

Release SDK 45fd2321

---

packages/sdk/src/views/models/timelineEvent.ts

this broke when i did the timeline move into the sdk

Fix fallback content after decryption

---

.github/workflows/ci.yml

Scale up ci runner vm to improve stability

Scale up ci vms

---

core/node/rpc/app_registry_test.go

These can be re-enabled when the deadlocking sql is fixed.

Disable all app registry service tests

---

CLAUDE.md
packages/stress/esbuild.config.mjs
packages/stress/package.json
packages/stress/src/generateWallets.ts

This tool exposes the ability to generate a set of wallets from a seed phrase. The algorithm here is the same one we use for generating wallets in the stress test itself, and this utility is useful for grabbing those wallets.

Add a utility for generating wallets from a mnemonic seed phrase.

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit d83f7bbfca6463784872fbd5f2841f15b5425d9f
Date:   Fri Jul 18 00:26:50 2025 +0000
sdk-e95b4efe-0.0.279

Release SDK e95b4efe

---

packages/sdk/src/views/models/timelineTypes.ts
packages/sdk/src/views/streamsView.ts

remove unnecessary throttle
restructure funny function

Sdk tiny cleanup

---

packages/sdk/src/views/streams/unreadMarkersTransform.ts

we have tests for this in the harmony repo that weren't running, so this got missed for a while. 
todo: migrate tests to sdk

Fix mentions bug (bad order of operations)

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit ec3e754f191b26d8a7352876f410c55ba17bcca5
Date:   Mon Jul 21 00:28:58 2025 +0000
sdk-43325168-0.0.282

Release SDK 43325168

---

packages/sdk/src/clientDecryptionExtensions.ts
packages/sdk/src/decryptionExtensions.ts
packages/sdk/src/id.ts
packages/sdk/src/streamEvents.ts
packages/sdk/src/streamStateView.ts
packages/sdk/src/streamStateView_Members.ts
packages/sdk/src/streamStateView_Members_Solicitations.ts
packages/sdk/src/tests/multi_ne/ephemeralEvents.test.ts
packages/sdk/src/tests/unit/decryptionExtensions.test.ts

i see a 30% improvement on my build (i’m in a lot of spaces)

Memory Optimization - don’t keep userAddress in memory

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit f69d38eaeca9a87265746214d7d4da66e005358a
Date:   Wed Jul 23 00:27:39 2025 +0000
sdk-491c80d8-0.0.283

Release SDK 491c80d8

---

packages/contracts/package.json
yarn.lock

Updated dependencies to their latest versions to ensure compatibility and stability:
- @openzeppelin/contracts
- @towns-protocol/diamond
- solady
- Updated dependency versions in the contract package.

chore(contract): update dependencies (@openzeppelin/contracts, @towns-protocol/diamond, solady)

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit e4fcab359af75e247c98af963c39391f54515101
Date:   Thu Jul 24 00:27:36 2025 +0000
sdk-21ea3c14-0.0.284

Release SDK 21ea3c14

---

packages/stream-metadata/package.json

for funzies and to make testing easier

stream-metadata service add dev commands to run against alpha and omega

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1dd5a69c1ecf4601f0bd13fb788a305fb4fb36fa
Date:   Sun Jul 27 00:29:48 2025 +0000
sdk-c048e18a-0.0.286

Release SDK c048e18a

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit db5a8dc0cee97b3d01eaf59880431fb6f5d6cef5
Date:   Mon Jul 28 00:29:10 2025 +0000
sdk-766fdc44-0.0.287

Release SDK 766fdc44

---

core/node/events/miniblock_info.go
core/node/storage/pg_stream_store.go

It appears that nil snapshots in some case could have been saved as zero-length arrays, which in turn can be confusing on read. This PR standardizes the meaning of fields.

Clean up snapshot roundtripping to storage

---

packages/sdk/src/client.ts

like most of the way the sync code is, idk why this is the way it is

make syncStreamsExtensions not optinal

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 9f555480626b06ebce630b3c45f7b08f7bd85820
Date:   Wed Jul 30 00:28:01 2025 +0000
sdk-888a9cab-0.0.289

Release SDK 888a9cab

---

packages/dlog/src/dlog.ts

And add it to the buffered logger and finally have errors in bug reports (how did we make it this long without it?)

Wrap the error log in dlog so that we can capture it in the app

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 7003aaf14e5b0ec341c3b890664396b6665cf53c
Date:   Fri Aug 1 00:30:30 2025 +0000
sdk-258d4050-0.0.291

Release SDK 258d4050

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit be2ff09e852dfea7956e2846f35bee67451db8d1
Date:   Mon Aug 4 00:30:01 2025 +0000
sdk-ccc1321a-0.0.294

Release SDK ccc1321a

---

packages/docs/mint.json

Move MiCA Whitepaper to first position in White Paper group

 MiCA Whitepaper navigation display 

---

packages/docs/white-paper/towns-technical-overview.mdx

Update the Allocation values and Supply schedule

Update the Allocation values and Supply schedule

---

core/node/track_streams/multi_sync_runner.go

This should prevent nodes from being spammed over lost sync ids.

Cancel sync runners for not-found syncs in the notification service

---

core/fmt.sh

Pin the formatter tool versions, just as we pin the versions of tools we use for linting.

Pin format versions for go code

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 545ad30623e22211ee101ed68dcb291bfa2d6573
Date:   Wed Aug 6 00:27:51 2025 +0000
sdk-c9048ef5-0.0.296

Release SDK c9048ef5

---

packages/docs/token-governance/towns-token.mdx

Fix contract addresses formatting and add hyperlink to Towns Lodge

Fix contract addresses formatting 

---

packages/contracts/src/spaces/facets/membership/IMembership.sol
packages/contracts/src/spaces/facets/membership/join/MembershipJoin.sol
packages/contracts/src/spaces/facets/xchain/SpaceEntitlementGated.sol

This PR refactors the membership join process by introducing a new `JoinDetails` struct to centralize and standardize pricing logic. The implementation consolidates previously scattered payment validation and charging logic into a single source of truth.
- Added a new `PricingDetails` struct to `IMembershipBase` to encapsulate all pricing information
- Implemented `_getPricingDetails()` method to calculate pricing details in one place
- Refactored payment validation logic to use the new struct
- Updated charging methods to accept the `PricingDetails` struct as a parameter
- Removed redundant methods like `_shouldChargeForJoinSpace()`, `_getRequiredAmount()`, and `_validatePayment()`
- Updated cross-chain entitlement handling to use the new pricing structure

refactor: add JoinDetails struct and improve membership payment logic

---

packages/sdk/src/syncedStreamsLoop.ts

I think Erik was right - we only need one abort controller
Add it everywhere including pings
Re-create it when we start syncing

Better abort controller

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 2a6603809d5b42ed045982f00810356392274eaa
Date:   Fri Aug 8 00:27:53 2025 +0000
sdk-4e10740e-0.0.298

Release SDK 4e10740e

---

packages/react-sdk/.eslintrc.cjs
packages/react-sdk/src/useUserGdms.ts
packages/sdk/src/syncedStreamsLoop.ts

I added this this week, shouldn’t write code when adrenaline is high.
Also need better tests

Fix bug in syncStreamsLoop cleanup

---

packages/sdk/src/syncedStreamsLoop.ts

the harmony tests became unstable with these changes and seems like this fixes it.

Update abort controller again with better stop mechanics

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3bfdf9b16343873cac6aa93a483372ea5ae76d7d
Date:   Mon Aug 11 00:29:09 2025 +0000
sdk-bbf82414-0.0.301

Release SDK bbf82414

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 7f32a2006a2a525aaecb52f5c0726404cd1f8687
Date:   Wed Aug 13 00:24:57 2025 +0000
sdk-8fd21784-0.0.303

Release SDK 8fd21784

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 632f316c1e03eb742f2298d70945d269150b7bcd
Date:   Thu Aug 14 00:24:47 2025 +0000
sdk-60570c12-0.0.305

Release SDK 60570c12

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3a5e788632eccf5972b0da970b55eb9f392752c5
Date:   Sun Aug 17 00:26:37 2025 +0000
sdk-144920fe-0.0.308

Release SDK 144920fe

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1105ed20cf59bb547b86dcba692b3ea07d407fe4
Date:   Tue Aug 19 00:24:17 2025 +0000
sdk-6f83b6e7-0.0.310

Release SDK 6f83b6e7

---

core/node/notifications/push/push.go

As per the Apple APNs Provider API, we should keep a handle to the apns client, so that it keeps the connections with APNs open across multiple notifications; APNs treats rapid connection and disconnection as a denial-of-service attack.
Create the client on load, and keep using it for the duration of the run

Do not create apns client for every notification

---

.github/workflows/ci.yml

Fix spelling mistake in github job

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit bad11d2643b61c514d017ca6fe66d3bda35bd95c
Date:   Wed Aug 20 00:23:19 2025 +0000
sdk-2201a475-0.0.311

Release SDK 2201a475

---

packages/subgraph/src/index.ts

Update arg names to match contracts for recent changes. Followup PR will add `yarn build` step to CI so we can catch these errors during CI.
```
yarn typecheck
➜  subgraph git:(main) ✗ yarn typecheck
src/index.ts:153:53 - error TS2339: Property 'collectPosterFeeToSpace' does not exist on type '{ posterFeeBps: number; forwardPosterFee: boolean; }'.
153                 collectPosterFeeToSpace: event.args.collectPosterFeeToSpace,
~~~~~~~~~~~~~~~~~~~~~~~
src/index.ts:163:53 - error TS2339: Property 'collectPosterFeeToSpace' does not exist on type '{ posterFeeBps: number; forwardPosterFee: boolean; }'.
163                 collectPosterFeeToSpace: event.args.collectPosterFeeToSpace,
~~~~~~~~~~~~~~~~~~~~~~~
src/index.ts:256:38 - error TS2339: Property 'treasury' does not exist on type '{ token: …
```

fix: update arg names to match contracts

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 03377a89341c12e9ef422eee189a7350a0423225
Date:   Thu Aug 21 00:23:00 2025 +0000
sdk-324f3a7d-0.0.312

Release SDK 324f3a7d

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 2e23a557dc442c2da05460f0b967879fdcea3614
Date:   Fri Aug 22 07:17:44 2025 +0000
sdk-bea730ca-0.0.314

Release SDK bea730ca

---

packages/generated/scripts/prepare.js

- Fix `tar` command working directory issue in `downloadArtifactsFromNpm()`
- Add error logging to diagnose download failures
- Move contracts directory check before Foundry installation to fail fast
The tar command was failing in Docker because it ran from wrong directory. npm pack creates .tgz in tempDir but tar was running from package root. Now both commands use `cwd: tempDir` for consistency.
This resolves Docker build failures for services that don't include contracts package.

fix(generated): fix npm artifact download in Docker builds

---

packages/bot/src/bot.test.ts
packages/bot/src/bot.ts

feat: `bot.onMentionedInThread`

---

.github/workflows/Subgraph_service_continuous_deployment.yml
packages/subgraph/docker-entrypoint.sh

Adds a flag to ponder to set the logging format, only if `PONDER_LOG_FORMAT` environment variable is defined

Add log format to subgraph & include alpha env

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit ff940def9ff56d5c4f66c304fa8c2355a4176464
Date:   Mon Aug 25 00:24:55 2025 +0000
sdk-4cac4894-0.0.319

Release SDK 4cac4894

---

packages/bot/src/bot.test.ts
packages/sdk/src/streamStateView_Members.ts
packages/sdk/src/streamStateView_User.ts
packages/sdk/src/streamStateView_UserInbox.ts
packages/sdk/src/streamStateView_UserMetadata.ts
packages/sdk/src/streamStateView_UserSettings.ts
packages/sdk/src/views/models/timelineEvent.ts
packages/sdk/src/views/models/timelineTypes.ts
packages/sdk/src/views/streams/userInboxStreams.ts
packages/sdk/src/views/streams/userMetadataStreams.ts
packages/sdk/src/views/streams/userSettingsStreams.ts
packages/sdk/src/views/streams/userStreamsView.ts

So we can add support to check if a user is a not in the SDK-level

feat(sdk): add `app_address` in stream view

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 3851bfcca42867398593062519b76653393bd4b1
Date:   Wed Aug 27 00:23:54 2025 +0000
sdk-99480fa3-0.0.322

Release SDK 99480fa3

---

core/cmd/registry_cmd.go

Summary
Add support for querying node registry at a specific River chain block number, enabling historical node state
analysis.
Changes
- Added --river-block flag to the registry nodes command to query node registry at a specific block
- Enhanced output formatting with a separator line (140 '=' characters) for improved readability
- Display the block number (and timestamp when available) in the output to clearly indicate the query point

node: add support to dump node registry at specific river block

---

packages/bot/src/bot.test.ts
packages/bot/src/bot.ts
packages/sdk/src/client-v2.ts

Enabling bots to delete other ppl messages / events.

bot-framework: add `adminRemoveEvent`

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 218f1c29b2fc49f5eed288ec70e7bbb78a59f39c
Date:   Thu Aug 28 00:25:34 2025 +0000
sdk-7e34295d-0.0.323

Release SDK 7e34295d

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit c5e2b2b3101ec1d9676f3b31cddf4b9b9ac41e77
Date:   Sat Aug 30 00:23:03 2025 +0000
sdk-613363d7-0.0.325

Release SDK 613363d7

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 0b6a4ac6df3769f1da9f42d3add78a9b5ca779d3
Date:   Sun Aug 31 00:25:39 2025 +0000
sdk-187433ef-0.0.326

Release SDK 187433ef

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 22fa8f23dd75dd7507ad3343f59f4c5ec8f5f79d
Date:   Tue Sep 2 00:23:40 2025 +0000
sdk-6a23f658-0.0.328

Release SDK 6a23f658

---

core/node/track_streams/streams_tracker.go

This will help to debug a stream that does not get any notifications

Added log when adding a stream to be trakced for notifications

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 91e3bc86a96ecd92c40a19ed4a3fbf70d427f0d3
Date:   Wed Sep 3 00:25:00 2025 +0000
sdk-f3ea35e1-0.0.329

Release SDK f3ea35e1

---

packages/dlog/src/utils.ts

this is used to retry some on chain transactions in tests

sdk Update isTest helper to pick up vitest

---

packages/sdk/src/streamStateView_User.ts

From miguel's tipping pr, looks like this was just missed in the original impl

Add app address to user stream

---

core/Dockerfile

Remove unused cargo and protobuf-dev package in dockerfile.

node: update protobuf-dev dependency in dockerfile

---

.prettierignore
AGENTS.md
core/AGENTS.md
core/node/app_registry/AGENTS.md
core/node/authentication/AGENTS.md
core/node/rpc/AGENTS.md
core/node/storage/AGENTS.md
packages/contracts/AGENTS.md
packages/stress/AGENTS.md
protocol/AGENTS.md

Make AGENTS.md for codex to be symlinks to CLAUDE.md

chore: add AGENTS.md symlinks to CLAUDE.md (9 dirs)

---

packages/contracts/src/factory/facets/feature/FeatureManagerBase.sol
packages/contracts/src/factory/facets/feature/FeatureManagerFacet.sol
packages/contracts/src/factory/facets/feature/FeatureManagerStorage.sol
packages/contracts/src/factory/facets/feature/IFeatureManagerFacet.sol

This PR optimizes the FeatureManager contract with gas-efficient patterns and improved code organization following the Solidity style guide. The changes focus on reducing gas costs through memory optimization techniques, efficient iteration patterns, and cleaner storage access while maintaining the same functionality.
- Added memory reclaim assembly optimization in `getFeatureCondition` to avoid unnecessary memory allocation
- Replaced `at()` with `values()` for full set iteration to eliminate bounds checking overhead
- Added comprehensive explanatory comments documenting gas optimization rationale
- Refactored conditional logic in `_upsertFeatureCondition` for cleaner flow
- Reorganized interface declarations following Solidity style guide (events before errors)
- Optimized storage …

perf(contract): optimize FeatureManager and adhere to Solidity style guide

---

packages/contracts/package.json
packages/contracts/scripts/deployments/diamonds/DeploySpace.s.sol
packages/contracts/scripts/deployments/diamonds/DeploySpaceFactory.s.sol
packages/contracts/scripts/interactions/InteractAlphaSparse.s.sol
packages/contracts/scripts/interactions/InteractBaseAlpha.s.sol
packages/contracts/scripts/interactions/helpers/AlphaHelper.sol
yarn.lock

The smart cuts system analyzes existing diamond state vs proposed changes to generate minimal required operations, significantly reducing gas costs and improving upgrade efficiency.
- Implemented `generateSmartCuts` for dynamic and minimal facet cuts.
- Refactored diamond upgrade scripts with enhanced selector management and removal logic.
- Adjusted facet deployment sequence for improved organization.
- Added logging for better debugging and upgrade tracking.
- Updated `@towns-protocol/diamond` to v0.6.3 and cleaned up dependencies in `yarn.lock`.

feat(contract): optimize diamond upgrades and update dependencies

---

packages/contracts/docker/run.sh
packages/contracts/docker/setup.sh
packages/contracts/docker/test.sh

sometimes we set it to a smaller number

Respect RIVER_BLOCK_TIME in the contracts docker container

---

CLAUDE.md
core/CLAUDE.md
core/node/storage/CLAUDE.md
packages/contracts/CLAUDE.md
packages/stress/CLAUDE.md

Fix up CLAUDE.md/AGENTS.md to be agent-neutral, clarify core intructions

Refactor: Update guidance files to remove Claude references and streamline instructions

---

packages/bot/src/bot.test.ts
packages/bot/src/bot.ts
packages/examples/bot-quickstart/src/index.ts

It was missing before. We can finally make a ping command

[bot-framework] add `createdAt` in base payload

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 0ad93e42f93eba4356839b148fa166a818cd0f9d
Date:   Sat Sep 13 00:22:09 2025 +0000
sdk-d31897d7-0.0.339

Release SDK d31897d7

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/config/deployments.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit bc68bd20b3176ef9ece012adf2c4a8dba0726032
Date:   Sun Sep 14 09:40:59 2025 +0000
sdk-1749eb32-0.0.342
commit ddd092f0e66044541db9cc1f31544bfed129acc5
Date:   Sun Sep 14 09:40:34 2025 +0000
deployments for version sdk-1749eb32-

Release SDK 1749eb32

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 39500326c9182544a5a31c12dad47462c88a87d4
Date:   Mon Sep 15 00:25:51 2025 +0000
sdk-d955f169-0.0.343

Release SDK d955f169

---

core/justfile

Optimize node setup performance with Multicall3 batch transfers and parallel execution. This PR significantly reduces setup time by replacing 40 individual ETH distribution calls with 2 efficient batch transactions and implementing proper parallel registration with transaction confirmation.
- **Multicall3 ETH Distribution**: Replace individual `anvil_setBalance` calls with efficient `aggregate3Value` batch transfers (40 calls → 2 transactions)
- **Parallel Registration**: Add `_parallel-just` helper function for concurrent node registration operations
- **Transaction Confirmation**: Use `--confirmations 0` instead of `--async` to ensure transactions complete before proceeding
- **Environment Management**: Implement automatic variable export with `set -a`/`set +a` for consistent …

perf(core): optimize node setup with Multicall3 and parallel execution

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 4afff25b4b9c972031048c4443f143a541fc6c6e
Date:   Tue Sep 16 14:51:36 2025 +0000
sdk-9a20458c-0.0.345

Release SDK 9a20458c

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 1ea11fbd7b5b473c1b2d929009fddbaa37cc8008
Date:   Tue Sep 16 16:31:41 2025 +0000
sdk-a834b5b4-0.0.346

Release SDK a834b5b4

---

packages/bot/src/bot.test.ts
packages/bot/src/bot.ts

chore(bots): remove dm / gdm support

---

.github/workflows/Towns_anvil_docker.yml
.github/workflows/ci.yml
core/justfile
packages/contracts/README.md
packages/contracts/docker/Dockerfile
packages/contracts/docker/setup.sh
scripts/bc-all-start.sh
scripts/bc-all-stop.sh
scripts/deploy-contracts.sh
scripts/run-local-ci.sh

This reverts commit 37c46a1c98965827c8de960ea81506bf0c4c1746.

Revert "feat(ci): optimize Docker workflows and act compatibility (#4109)"

---

packages/subgraph/package.json
packages/subgraph/turbo.json
packages/subgraph/utils/contractAddresses.ts

Fixes subgraph dependency management and contract address resolution to ensure reliable local development. Addresses issues where ponder commands would fail due to missing contract typings and incorrect deployment paths.
- Updated subgraph package.json scripts to chain typings build with ponder commands
- Added centralized typings script for building contracts and web3 dependencies
- Fixed contract address resolution to use correct generated deployments path

fix(subgraph): improve dependency management and contract address resolution

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/dlog/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 9d7daa617491dac9ea70b18ae5622b5ebb695119
Date:   Thu Sep 18 00:25:31 2025 +0000
sdk-c485a65c-0.0.348

Release SDK c485a65c

---

core/node/app_registry/cached_encrypted_message_queue.go

Use common.Address for cache key instead of a string.
common.Address is comparable and faster than string comparison and prevents mismatches due to case differences or a 0x prefix

App Registry: Use more performant cache key

---

packages/examples/bot-quickstart/esbuild.config.mjs
packages/metrics-discovery/esbuild.config.mjs
packages/stream-metadata/esbuild.config.mjs
packages/stress/esbuild.config.mjs
packages/xchain-monitor/esbuild.config.mjs

This reverts commit 4b474cae883bb060b7d30a26c14851daf8bd4dd9.

Revert "Silence import meta build warnings in esbuilds (#4139)"

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 70b93a91561828fdf48dabf6709d1cd73177ceff
Date:   Sat Sep 20 00:22:45 2025 +0000
sdk-3b4c9551-0.0.350

Release SDK 3b4c9551

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit b3b37f6306c5f111996218bd0772adfc03498fcd
Date:   Mon Sep 22 00:25:58 2025 +0000
sdk-7553142d-0.0.352

Release SDK 7553142d

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit a6dc807ec679a6507c2f1b10bb54af6adf78e01e
Date:   Wed Sep 24 00:24:38 2025 +0000
sdk-900e667b-0.0.354

Release SDK 900e667b

---

core/env/alpha/config.yaml
core/env/delta/config.yaml
core/env/gamma/config.yaml
core/env/omega/config.yaml

Update river chain endpoint in `core/env/*/config.yaml` after project was renamed from river to towns.

node: update river chain endpoint in env/*/config.yaml

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit f0192ebd59ae6a99003a0753d1821713e2407bc5
Date:   Wed Sep 24 19:59:52 2025 +0000
sdk-e13cd75e-0.0.355

Release SDK e13cd75e

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit c3283b1d3e158931ffaca0c745e36e76795965e1
Date:   Fri Sep 26 00:23:37 2025 +0000
sdk-61b88bbe-0.0.356

Release SDK 61b88bbe

---

.github/workflows/ci.yml

Revert to old github runners temporarily to debug build issues

Revert to old github runners temporarily

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit 31de81b8a6806f0c512f94b9602d6d099355a4d8
Date:   Mon Sep 29 00:25:05 2025 +0000
sdk-d5af3780-0.0.358

Release SDK d5af3780

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json

commit eaa0db40087afae546708c9a8846d9e5b35cda9a
Date:   Tue Sep 30 00:26:10 2025 +0000
sdk-78d36631-0.0.359

Release SDK 78d36631

---

packages/subgraph/ponder.config.beta.ts

Each environment has its own ponder file, this file is for the new beta env

add beta ponder file

---

core/config/config.go
core/env/alpha/config.yaml
core/env/delta/config.yaml
core/env/gamma/config.yaml
core/env/omega/config.yaml

Add missing base registry contract addresses to node pre-env configs.

Add entitlement_contract address entries to environment config files.

---

lerna.json
packages/bot/package.json
packages/contracts/package.json
packages/create-towns-protocol-app/package.json
packages/encryption/package.json
packages/eslint-config/package.json
packages/generated/package.json
packages/prettier-config/package.json
packages/proto/package.json
packages/react-sdk/package.json
packages/rpc-connector/package.json
packages/sdk-crypto/package.json
packages/sdk/package.json
packages/towns-bot-cli/package.json
packages/utils/package.json
packages/web3/package.json
packages/xchain-monitor/package.json
yarn.lock

commit a2731ca73b07a9b9e1588e655902f537364f56f5
Date:   Thu Oct 2 00:25:47 2025 +0000
sdk-6dcc2da2-0.0.360

Release SDK 6dcc2da2
